language: generic
dist: xenial

addons:
        apt:
                packages:
                        - libmp3lame-dev
                        - yasm

before_install:
        # C++17 / libboost
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo add-apt-repository -y ppa:mhier/libboost-latest
        - sudo apt-get update -qq
        # remove the invalid soundfile list (if any) and fail if the cache file exists (which it shouldn't)
        - rm -f invalid-soundfiles.txt
        - if [ -f chatsounds-preprocessor-cache ]; then >&2 echo -e "Precondition failed\x3A Preprocessor cache file exists in the repo."; false; fi

install:
        # C++17 / libboost
        - sudo apt-get remove -qq libstdc++-5-dev # because /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++fs.a causes undefined reference issues
        - sudo apt-get install -qq g++-8 libboost1.68-dev
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
        # build the preprocessor
        - git clone https://github.com/PotcFdk/chatsounds-preprocessor chatsounds-preprocessor.repo --depth 1 --branch v1.3.0
        - cd chatsounds-preprocessor.repo
        - cd libs && ./setup-ffmpeg-native.sh
        - cd .. && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
        - make && mv chatsounds-preprocessor ../../ && cd ../.. && rm -rf chatsounds-preprocessor.repo

before_script: ./chatsounds-preprocessor --version
script: ./chatsounds-preprocessor --full --non-interactive

after_success:
        - openssl aes-256-cbc -K $encrypted_1794e5363862_key -iv $encrypted_1794e5363862_iv -in .deploy_key.enc -out .deploy_key -d
          && eval "$(ssh-agent -s)" && chmod 600 .deploy_key && ssh-add .deploy_key
        - git config user.name "Meta Automator" && git config user.email MetaAutomator@users.noreply.github.com
        - git remote remove origin && git remote add origin git@github.com:Metastruct/garrysmod-chatsounds.git && git fetch --unshallow
        - if [ "$(git rev-parse origin/master)" == "$TRAVIS_COMMIT" ]; then
                git checkout master && git add lua && git commit -m "chatsounds preprocessor ($TRAVIS_COMMIT)" -m "[ci skip]";
                git push --set-upstream origin master;
          else
                echo "The commit this build was started for is not the one on master. Not pushing to master.";
          fi

after_failure: if [ -f invalid-soundfiles.txt ]; then >&2 echo "Invalid sound files list:" | cat - invalid-soundfiles.txt; fi
