c.StartList("26e")
L["benzo"]={{path="chatsounds/autoadd/26e/benzo.ogg",length=371.109}}
L["blueangel"]={{path="chatsounds/autoadd/26e/blueangel.ogg",length=1.875}}
L["burnthismoment"]={{path="chatsounds/autoadd/26e/burnthismoment.ogg",length=385.090}}
L["callmeit"]={{path="chatsounds/autoadd/26e/callmeit.ogg",length=170.017}}
L["natureofdying"]={{path="chatsounds/autoadd/26e/natureofdying.ogg",length=360.303}}
L["nestetrismusic1"]={{path="chatsounds/autoadd/26e/nestetrismusic1.ogg",length=54.817}}
L["nestetrismusic2"]={{path="chatsounds/autoadd/26e/nestetrismusic2.ogg",length=35.410}}
L["nestetrismusic3"]={{path="chatsounds/autoadd/26e/nestetrismusic3.ogg",length=24.231}}
L["noangelshere"]={{path="chatsounds/autoadd/26e/noangelshere.ogg",length=334.621}}
L["overtheflood"]={{path="chatsounds/autoadd/26e/overtheflood.ogg",length=383.014}}
L["windowsxpsongpart1"]={{path="chatsounds/autoadd/26e/windowsxpsongpart1.ogg",length=43.378}}
L["windowsxpsongpart2"]={{path="chatsounds/autoadd/26e/windowsxpsongpart2.ogg",length=4.457}}
L["windowsxpsongpart3"]={{path="chatsounds/autoadd/26e/windowsxpsongpart3.ogg",length=38.378}}
c.EndList()