c.StartList("android")
L["android aldebaran"]={{path="chatsounds/autoadd/android/android aldebaran.ogg",length=0.625}}
L["android altair"]={{path="chatsounds/autoadd/android/android altair.ogg",length=0.739}}
L["android andromeda"]={{path="chatsounds/autoadd/android/android andromeda.ogg",length=3.010}}
L["android antares"]={{path="chatsounds/autoadd/android/android antares.ogg",length=0.919}}
L["android aquila"]={{path="chatsounds/autoadd/android/android aquila.ogg",length=3.014}}
L["android arcturus"]={{path="chatsounds/autoadd/android/android arcturus.ogg",length=1.012}}
L["android argonavis"]={{path="chatsounds/autoadd/android/android argonavis.ogg",length=13.338}}
L["android backroad"]={{path="chatsounds/autoadd/android/android backroad.ogg",length=3.611}}
L["android beatboxandroid"]={{path="chatsounds/autoadd/android/android beatboxandroid.ogg",length=2.025}}
L["android beatplucker"]={{path="chatsounds/autoadd/android/android beatplucker.ogg",length=4.021}}
L["android bentleydubs"]={{path="chatsounds/autoadd/android/android bentleydubs.ogg",length=4.465}}
L["android betelgeuse"]={{path="chatsounds/autoadd/android/android betelgeuse.ogg",length=1.072}}
L["android bigeasy"]={{path="chatsounds/autoadd/android/android bigeasy.ogg",length=4.815}}
L["android birdloop"]={{path="chatsounds/autoadd/android/android birdloop.ogg",length=5.873}}
L["android bollywood"]={{path="chatsounds/autoadd/android/android bollywood.ogg",length=4.227}}
L["android bootes"]={{path="chatsounds/autoadd/android/android bootes.ogg",length=3.011}}
L["android bussamove"]={{path="chatsounds/autoadd/android/android bussamove.ogg",length=4.904}}
L["android caffeinesnake"]={{path="chatsounds/autoadd/android/android caffeinesnake.ogg",length=1.926}}
L["android cairo"]={{path="chatsounds/autoadd/android/android cairo.ogg",length=4.196}}
L["android calypsosteel"]={{path="chatsounds/autoadd/android/android calypsosteel.ogg",length=4.003}}
L["android canismajor"]={{path="chatsounds/autoadd/android/android canismajor.ogg",length=3.499}}
L["android canopus"]={{path="chatsounds/autoadd/android/android canopus.ogg",length=0.718}}
L["android capella"]={{path="chatsounds/autoadd/android/android capella.ogg",length=1.395}}
L["android caribbeanice"]={{path="chatsounds/autoadd/android/android caribbeanice.ogg",length=4.010}}
L["android carina"]={{path="chatsounds/autoadd/android/android carina.ogg",length=3.017}}
L["android cassiopeia"]={{path="chatsounds/autoadd/android/android cassiopeia.ogg",length=4.004}}
L["android castor"]={{path="chatsounds/autoadd/android/android castor.ogg",length=1.572}}
L["android centaurus"]={{path="chatsounds/autoadd/android/android centaurus.ogg",length=4.007}}
L["android cetialpha"]={{path="chatsounds/autoadd/android/android cetialpha.ogg",length=2.881}}
L["android champagneedition"]={{path="chatsounds/autoadd/android/android champagneedition.ogg",length=4.370}}
L["android clubcubano"]={{path="chatsounds/autoadd/android/android clubcubano.ogg",length=4.011}}
L["android crayonrock"]={{path="chatsounds/autoadd/android/android crayonrock.ogg",length=3.570}}
L["android crazydream"]={{path="chatsounds/autoadd/android/android crazydream.ogg",length=31.454}}
L["android cricket"]={{path="chatsounds/autoadd/android/android cricket.ogg",length=0.907}}
L["android curveball"]={{path="chatsounds/autoadd/android/android curveball.ogg",length=3.995}}
L["android cygnus"]={{path="chatsounds/autoadd/android/android cygnus.ogg",length=4.016}}
L["android dancinfool"]={{path="chatsounds/autoadd/android/android dancinfool.ogg",length=5.766}}
L["android deardeer"]={{path="chatsounds/autoadd/android/android deardeer.ogg",length=1.937}}
L["android deneb"]={{path="chatsounds/autoadd/android/android deneb.ogg",length=1.679}}
L["android ding"]={{path="chatsounds/autoadd/android/android ding.ogg",length=1.508}}
L["android doink"]={{path="chatsounds/autoadd/android/android doink.ogg",length=0.361}}
L["android donmesswivit"]={{path="chatsounds/autoadd/android/android donmesswivit.ogg",length=5.164}}
L["android dontpanic"]={{path="chatsounds/autoadd/android/android dontpanic.ogg",length=1.940}}
L["android draco"]={{path="chatsounds/autoadd/android/android draco.ogg",length=4.004}}
L["android dreamtheme"]={{path="chatsounds/autoadd/android/android dreamtheme.ogg",length=26.675}}
L["android drip"]={{path="chatsounds/autoadd/android/android drip.ogg",length=1.247}}
L["android easternsky"]={{path="chatsounds/autoadd/android/android easternsky.ogg",length=5.345}}
L["android electra"]={{path="chatsounds/autoadd/android/android electra.ogg",length=2.103}}
L["android enterthenexus"]={{path="chatsounds/autoadd/android/android enterthenexus.ogg",length=6.623}}
L["android eridani"]={{path="chatsounds/autoadd/android/android eridani.ogg",length=5.008}}
L["android ethershake"]={{path="chatsounds/autoadd/android/android ethershake.ogg",length=4.014}}
L["android f1missedcall"]={{path="chatsounds/autoadd/android/android f1missedcall.ogg",length=0.718}}
L["android f1newmms"]={{path="chatsounds/autoadd/android/android f1newmms.ogg",length=1.310}}
L["android f1newsms"]={{path="chatsounds/autoadd/android/android f1newsms.ogg",length=0.657}}
L["android fomalhaut"]={{path="chatsounds/autoadd/android/android fomalhaut.ogg",length=2.315}}
L["android freeflight"]={{path="chatsounds/autoadd/android/android freeflight.ogg",length=12.635}}
L["android friendlyghost"]={{path="chatsounds/autoadd/android/android friendlyghost.ogg",length=5.219}}
L["android funkyall"]={{path="chatsounds/autoadd/android/android funkyall.ogg",length=4.104}}
L["android gameoverguitar"]={{path="chatsounds/autoadd/android/android gameoverguitar.ogg",length=6.004}}
L["android gimmemotown"]={{path="chatsounds/autoadd/android/android gimmemotown.ogg",length=4.001}}
L["android glacialgroove"]={{path="chatsounds/autoadd/android/android glacialgroove.ogg",length=5.107}}
L["android growl"]={{path="chatsounds/autoadd/android/android growl.ogg",length=5.786}}
L["android halfwayhome"]={{path="chatsounds/autoadd/android/android halfwayhome.ogg",length=7.114}}
L["android heaven"]={{path="chatsounds/autoadd/android/android heaven.ogg",length=2.017}}
L["android highwire"]={{path="chatsounds/autoadd/android/android highwire.ogg",length=1.926}}
L["android hydra"]={{path="chatsounds/autoadd/android/android hydra.ogg",length=5.005}}
L["android insertcoin"]={{path="chatsounds/autoadd/android/android insertcoin.ogg",length=2.003}}
L["android kzurbsonar"]={{path="chatsounds/autoadd/android/android kzurbsonar.ogg",length=1.923}}
L["android loopylounge"]={{path="chatsounds/autoadd/android/android loopylounge.ogg",length=5.116}}
L["android loveflute"]={{path="chatsounds/autoadd/android/android loveflute.ogg",length=4.801}}
L["android lyra"]={{path="chatsounds/autoadd/android/android lyra.ogg",length=5.679}}
L["android machina"]={{path="chatsounds/autoadd/android/android machina.ogg",length=5.133}}
L["android merope"]={{path="chatsounds/autoadd/android/android merope.ogg",length=1.113}}
L["android mideviljaunt"]={{path="chatsounds/autoadd/android/android mideviljaunt.ogg",length=3.847}}
L["android mildlyalarming"]={{path="chatsounds/autoadd/android/android mildlyalarming.ogg",length=4.003}}
L["android moonbeam"]={{path="chatsounds/autoadd/android/android moonbeam.ogg",length=1.892}}
L["android nairobi"]={{path="chatsounds/autoadd/android/android nairobi.ogg",length=4.003}}
L["android nassau"]={{path="chatsounds/autoadd/android/android nassau.ogg",length=4.365}}
L["android newplayer"]={{path="chatsounds/autoadd/android/android newplayer.ogg",length=2.006}}
L["android noises1"]={{path="chatsounds/autoadd/android/android noises1.ogg",length=4.003}}
L["android noises2"]={{path="chatsounds/autoadd/android/android noises2.ogg",length=4.014}}
L["android noises3"]={{path="chatsounds/autoadd/android/android noises3.ogg",length=3.972}}
L["android nolimits"]={{path="chatsounds/autoadd/android/android nolimits.ogg",length=3.585}}
L["android onthehunt"]={{path="chatsounds/autoadd/android/android onthehunt.ogg",length=1.926}}
L["android organdub"]={{path="chatsounds/autoadd/android/android organdub.ogg",length=4.365}}
L["android orion"]={{path="chatsounds/autoadd/android/android orion.ogg",length=6.224}}
L["android paradiseisland"]={{path="chatsounds/autoadd/android/android paradiseisland.ogg",length=4.158}}
L["android pegasus"]={{path="chatsounds/autoadd/android/android pegasus.ogg",length=9.626}}
L["android perseus"]={{path="chatsounds/autoadd/android/android perseus.ogg",length=10.224}}
L["android pixiedust"]={{path="chatsounds/autoadd/android/android pixiedust.ogg",length=1.740}}
L["android pizzicato"]={{path="chatsounds/autoadd/android/android pizzicato.ogg",length=2.020}}
L["android plasticpipe"]={{path="chatsounds/autoadd/android/android plasticpipe.ogg",length=0.408}}
L["android playa"]={{path="chatsounds/autoadd/android/android playa.ogg",length=5.856}}
L["android polaris"]={{path="chatsounds/autoadd/android/android polaris.ogg",length=2.361}}
L["android pollux"]={{path="chatsounds/autoadd/android/android pollux.ogg",length=2.599}}
L["android procyon"]={{path="chatsounds/autoadd/android/android procyon.ogg",length=2.643}}
L["android pyxis"]={{path="chatsounds/autoadd/android/android pyxis.ogg",length=3.717}}
L["android regulus"]={{path="chatsounds/autoadd/android/android regulus.ogg",length=3.296}}
L["android rigel"]={{path="chatsounds/autoadd/android/android rigel.ogg",length=3.431}}
L["android ringclassic02"]={{path="chatsounds/autoadd/android/android ringclassic02.ogg",length=5.100}}
L["android ringdigital02"]={{path="chatsounds/autoadd/android/android ringdigital02.ogg",length=3.722}}
L["android ringsynth02"]={{path="chatsounds/autoadd/android/android ringsynth02.ogg",length=4.155}}
L["android ringsynth04"]={{path="chatsounds/autoadd/android/android ringsynth04.ogg",length=3.699}}
L["android roadtrip"]={{path="chatsounds/autoadd/android/android roadtrip.ogg",length=5.489}}
L["android romancingthetone"]={{path="chatsounds/autoadd/android/android romancingthetone.ogg",length=4.584}}
L["android safari"]={{path="chatsounds/autoadd/android/android safari.ogg",length=4.013}}
L["android scarabaeus"]={{path="chatsounds/autoadd/android/android scarabaeus.ogg",length=9.246}}
L["android sceptrum"]={{path="chatsounds/autoadd/android/android sceptrum.ogg",length=22.542}}
L["android seville"]={{path="chatsounds/autoadd/android/android seville.ogg",length=4.793}}
L["android shesallthat"]={{path="chatsounds/autoadd/android/android shesallthat.ogg",length=4.178}}
L["android silkyway"]={{path="chatsounds/autoadd/android/android silkyway.ogg",length=4.190}}
L["android sirius"]={{path="chatsounds/autoadd/android/android sirius.ogg",length=4.306}}
L["android sirrah"]={{path="chatsounds/autoadd/android/android sirrah.ogg",length=1.310}}
L["android sitarvssitar"]={{path="chatsounds/autoadd/android/android sitarvssitar.ogg",length=4.021}}
L["android solarium"]={{path="chatsounds/autoadd/android/android solarium.ogg",length=7.902}}
L["android spaceseed"]={{path="chatsounds/autoadd/android/android spaceseed.ogg",length=2.881}}
L["android springyjalopy"]={{path="chatsounds/autoadd/android/android springyjalopy.ogg",length=4.003}}
L["android steppinout"]={{path="chatsounds/autoadd/android/android steppinout.ogg",length=3.995}}
L["android tada"]={{path="chatsounds/autoadd/android/android tada.ogg",length=3.297}}
L["android terminated"]={{path="chatsounds/autoadd/android/android terminated.ogg",length=5.328}}
L["android testudo"]={{path="chatsounds/autoadd/android/android testudo.ogg",length=7.647}}
L["android thirdeye"]={{path="chatsounds/autoadd/android/android thirdeye.ogg",length=4.003}}
L["android tinkerbell"]={{path="chatsounds/autoadd/android/android tinkerbell.ogg",length=1.113}}
L["android tweeters"]={{path="chatsounds/autoadd/android/android tweeters.ogg",length=0.799}}
L["android twirlaway"]={{path="chatsounds/autoadd/android/android twirlaway.ogg",length=4.021}}
L["android ursaminor"]={{path="chatsounds/autoadd/android/android ursaminor.ogg",length=12.957}}
L["android vega"]={{path="chatsounds/autoadd/android/android vega.ogg",length=4.387}}
L["android veryalarmed"]={{path="chatsounds/autoadd/android/android veryalarmed.ogg",length=4.003}}
L["android vespa"]={{path="chatsounds/autoadd/android/android vespa.ogg",length=6.857}}
L["android voila"]={{path="chatsounds/autoadd/android/android voila.ogg",length=1.920}}
L["android world"]={{path="chatsounds/autoadd/android/android world.ogg",length=4.181}}
c.EndList()