c.StartList("android")
L["android aldebaran"]={{path="chatsounds/autoadd/android/android aldebaran.ogg",length=0.625}}
L["android altair"]={{path="chatsounds/autoadd/android/android altair.ogg",length=0.739}}
L["android antares"]={{path="chatsounds/autoadd/android/android antares.ogg",length=0.919}}
L["android arcturus"]={{path="chatsounds/autoadd/android/android arcturus.ogg",length=1.012}}
L["android beatboxandroid"]={{path="chatsounds/autoadd/android/android beatboxandroid.ogg",length=2.025}}
L["android betelgeuse"]={{path="chatsounds/autoadd/android/android betelgeuse.ogg",length=1.072}}
L["android caffeinesnake"]={{path="chatsounds/autoadd/android/android caffeinesnake.ogg",length=1.926}}
L["android canopus"]={{path="chatsounds/autoadd/android/android canopus.ogg",length=0.718}}
L["android capella"]={{path="chatsounds/autoadd/android/android capella.ogg",length=1.395}}
L["android castor"]={{path="chatsounds/autoadd/android/android castor.ogg",length=1.572}}
L["android cetialpha"]={{path="chatsounds/autoadd/android/android cetialpha.ogg",length=2.881}}
L["android cricket"]={{path="chatsounds/autoadd/android/android cricket.ogg",length=0.907}}
L["android deardeer"]={{path="chatsounds/autoadd/android/android deardeer.ogg",length=1.937}}
L["android deneb"]={{path="chatsounds/autoadd/android/android deneb.ogg",length=1.679}}
L["android doink"]={{path="chatsounds/autoadd/android/android doink.ogg",length=0.361}}
L["android dontpanic"]={{path="chatsounds/autoadd/android/android dontpanic.ogg",length=1.940}}
L["android drip"]={{path="chatsounds/autoadd/android/android drip.ogg",length=1.247}}
L["android electra"]={{path="chatsounds/autoadd/android/android electra.ogg",length=2.103}}
L["android f1missedcall"]={{path="chatsounds/autoadd/android/android f1missedcall.ogg",length=0.718}}
L["android f1new_mms"]={{path="chatsounds/autoadd/android/android f1new_mms.ogg",length=1.310}}
L["android f1newsms"]={{path="chatsounds/autoadd/android/android f1newsms.ogg",length=0.657}}
L["android fomalhaut"]={{path="chatsounds/autoadd/android/android fomalhaut.ogg",length=2.315}}
L["android heaven"]={{path="chatsounds/autoadd/android/android heaven.ogg",length=2.017}}
L["android highwire"]={{path="chatsounds/autoadd/android/android highwire.ogg",length=1.926}}
L["android kzurbsonar"]={{path="chatsounds/autoadd/android/android kzurbsonar.ogg",length=1.923}}
L["android merope"]={{path="chatsounds/autoadd/android/android merope.ogg",length=1.113}}
L["android moonbeam"]={{path="chatsounds/autoadd/android/android moonbeam.ogg",length=1.892}}
L["android onthehunt"]={{path="chatsounds/autoadd/android/android onthehunt.ogg",length=1.926}}
L["android pixiedust"]={{path="chatsounds/autoadd/android/android pixiedust.ogg",length=1.740}}
L["android pizzicato"]={{path="chatsounds/autoadd/android/android pizzicato.ogg",length=2.020}}
L["android plasticpipe"]={{path="chatsounds/autoadd/android/android plasticpipe.ogg",length=0.408}}
L["android polaris"]={{path="chatsounds/autoadd/android/android polaris.ogg",length=2.361}}
L["android pollux"]={{path="chatsounds/autoadd/android/android pollux.ogg",length=2.599}}
L["android procyon"]={{path="chatsounds/autoadd/android/android procyon.ogg",length=2.643}}
L["android regulus"]={{path="chatsounds/autoadd/android/android regulus.ogg",length=3.296}}
L["android sirius"]={{path="chatsounds/autoadd/android/android sirius.ogg",length=4.306}}
L["android sirrah"]={{path="chatsounds/autoadd/android/android sirrah.ogg",length=1.310}}
L["android spaceseed"]={{path="chatsounds/autoadd/android/android spaceseed.ogg",length=2.881}}
L["android tada"]={{path="chatsounds/autoadd/android/android tada.ogg",length=3.297}}
L["android tinkerbell"]={{path="chatsounds/autoadd/android/android tinkerbell.ogg",length=1.113}}
L["android tweeters"]={{path="chatsounds/autoadd/android/android tweeters.ogg",length=0.799}}
L["android vega"]={{path="chatsounds/autoadd/android/android vega.ogg",length=4.387}}
L["android voila"]={{path="chatsounds/autoadd/android/android voila.ogg",length=1.920}}
c.EndList()