c.StartList("animalcrossing")
L["0"]={{path="chatsounds/autoadd/animalcrossing/0.ogg",length=0.193}}
L["1"]={{path="chatsounds/autoadd/animalcrossing/1.ogg",length=0.193}}
L["2"]={{path="chatsounds/autoadd/animalcrossing/2.ogg",length=0.193}}
L["3"]={{path="chatsounds/autoadd/animalcrossing/3.ogg",length=0.225}}
L["4"]={{path="chatsounds/autoadd/animalcrossing/4.ogg",length=0.193}}
L["5"]={{path="chatsounds/autoadd/animalcrossing/5.ogg",length=0.225}}
L["6"]={{path="chatsounds/autoadd/animalcrossing/6.ogg",length=0.225}}
L["7"]={{path="chatsounds/autoadd/animalcrossing/7.ogg",length=0.257}}
L["8"]={{path="chatsounds/autoadd/animalcrossing/8.ogg",length=0.225}}
L["9"]={{path="chatsounds/autoadd/animalcrossing/9.ogg",length=0.225}}
L["ac whistle"]={{path="chatsounds/autoadd/animalcrossing/ac whistle.ogg",length=2.006}}
L["c"]={{path="chatsounds/autoadd/animalcrossing/c.ogg",length=0.225}}
L["d"]={{path="chatsounds/autoadd/animalcrossing/d.ogg",length=0.225}}
L["i"]={{path="chatsounds/autoadd/animalcrossing/i.ogg",length=0.161}}
L["k"]={{path="chatsounds/autoadd/animalcrossing/k.ogg",length=0.193}}
L["kkslider"]={{path="chatsounds/autoadd/animalcrossing/kkslider/hm.ogg",length=0.111},{path="chatsounds/autoadd/animalcrossing/kkslider/hn.ogg",length=0.099},{path="chatsounds/autoadd/animalcrossing/kkslider/ki.ogg",length=0.068},{path="chatsounds/autoadd/animalcrossing/kkslider/me.ogg",length=0.239},{path="chatsounds/autoadd/animalcrossing/kkslider/mee.ogg",length=0.340},{path="chatsounds/autoadd/animalcrossing/kkslider/na.ogg",length=0.163},{path="chatsounds/autoadd/animalcrossing/kkslider/now.ogg",length=0.350},{path="chatsounds/autoadd/animalcrossing/kkslider/oh.ogg",length=0.414},{path="chatsounds/autoadd/animalcrossing/kkslider/oo.ogg",length=0.263},{path="chatsounds/autoadd/animalcrossing/kkslider/ooo.ogg",length=0.238},{path="chatsounds/autoadd/animalcrossing/kkslider/ow.ogg",length=0.114},{path="chatsounds/autoadd/animalcrossing/kkslider/pa.ogg",length=0.118},{path="chatsounds/autoadd/animalcrossing/kkslider/ti.ogg",length=0.064},{path="chatsounds/autoadd/animalcrossing/kkslider/wa.ogg",length=0.172}}
L["l"]={{path="chatsounds/autoadd/animalcrossing/l.ogg",length=0.193}}
L["m"]={{path="chatsounds/autoadd/animalcrossing/m.ogg",length=0.193}}
L["n"]={{path="chatsounds/autoadd/animalcrossing/n.ogg",length=0.193}}
L["o"]={{path="chatsounds/autoadd/animalcrossing/o.ogg",length=0.161}}
L["p"]={{path="chatsounds/autoadd/animalcrossing/p.ogg",length=0.193}}
L["q"]={{path="chatsounds/autoadd/animalcrossing/q.ogg",length=0.225}}
L["r"]={{path="chatsounds/autoadd/animalcrossing/r.ogg",length=0.193}}
L["s"]={{path="chatsounds/autoadd/animalcrossing/s.ogg",length=0.225}}
L["t"]={{path="chatsounds/autoadd/animalcrossing/t.ogg",length=0.193}}
L["u"]={{path="chatsounds/autoadd/animalcrossing/u.ogg",length=0.193}}
L["v"]={{path="chatsounds/autoadd/animalcrossing/v.ogg",length=0.161}}
L["w"]={{path="chatsounds/autoadd/animalcrossing/w.ogg",length=0.225}}
L["y"]={{path="chatsounds/autoadd/animalcrossing/y.ogg",length=0.225}}
L["z"]={{path="chatsounds/autoadd/animalcrossing/z.ogg",length=0.193}}
c.EndList()