c.StartList("animal_crossing")
L["0"]={{path="chatsounds/autoadd/animal_crossing/0.ogg",length=0.193}}
L["1"]={{path="chatsounds/autoadd/animal_crossing/1.ogg",length=0.193}}
L["2"]={{path="chatsounds/autoadd/animal_crossing/2.ogg",length=0.193}}
L["3"]={{path="chatsounds/autoadd/animal_crossing/3.ogg",length=0.225}}
L["4"]={{path="chatsounds/autoadd/animal_crossing/4.ogg",length=0.193}}
L["5"]={{path="chatsounds/autoadd/animal_crossing/5.ogg",length=0.225}}
L["6"]={{path="chatsounds/autoadd/animal_crossing/6.ogg",length=0.225}}
L["7"]={{path="chatsounds/autoadd/animal_crossing/7.ogg",length=0.257}}
L["8"]={{path="chatsounds/autoadd/animal_crossing/8.ogg",length=0.225}}
L["9"]={{path="chatsounds/autoadd/animal_crossing/9.ogg",length=0.225}}
L["ac whistle"]={{path="chatsounds/autoadd/animal_crossing/ac whistle.ogg",length=2.006}}
L["c"]={{path="chatsounds/autoadd/animal_crossing/c.ogg",length=0.225}}
L["d"]={{path="chatsounds/autoadd/animal_crossing/d.ogg",length=0.225}}
L["i"]={{path="chatsounds/autoadd/animal_crossing/i.ogg",length=0.161}}
L["k"]={{path="chatsounds/autoadd/animal_crossing/k.ogg",length=0.193}}
L["kkslider"]={{path="chatsounds/autoadd/animal_crossing/kkslider/hm.ogg",length=0.111},{path="chatsounds/autoadd/animal_crossing/kkslider/hn.ogg",length=0.099},{path="chatsounds/autoadd/animal_crossing/kkslider/ki.ogg",length=0.068},{path="chatsounds/autoadd/animal_crossing/kkslider/me.ogg",length=0.239},{path="chatsounds/autoadd/animal_crossing/kkslider/mee.ogg",length=0.340},{path="chatsounds/autoadd/animal_crossing/kkslider/na.ogg",length=0.163},{path="chatsounds/autoadd/animal_crossing/kkslider/now.ogg",length=0.350},{path="chatsounds/autoadd/animal_crossing/kkslider/oh.ogg",length=0.414},{path="chatsounds/autoadd/animal_crossing/kkslider/oo.ogg",length=0.263},{path="chatsounds/autoadd/animal_crossing/kkslider/ooo.ogg",length=0.238},{path="chatsounds/autoadd/animal_crossing/kkslider/ow.ogg",length=0.114},{path="chatsounds/autoadd/animal_crossing/kkslider/pa.ogg",length=0.118},{path="chatsounds/autoadd/animal_crossing/kkslider/ti.ogg",length=0.064},{path="chatsounds/autoadd/animal_crossing/kkslider/wa.ogg",length=0.172}}
L["l"]={{path="chatsounds/autoadd/animal_crossing/l.ogg",length=0.193}}
L["m"]={{path="chatsounds/autoadd/animal_crossing/m.ogg",length=0.193}}
L["n"]={{path="chatsounds/autoadd/animal_crossing/n.ogg",length=0.193}}
L["o"]={{path="chatsounds/autoadd/animal_crossing/o.ogg",length=0.161}}
L["p"]={{path="chatsounds/autoadd/animal_crossing/p.ogg",length=0.193}}
L["q"]={{path="chatsounds/autoadd/animal_crossing/q.ogg",length=0.225}}
L["r"]={{path="chatsounds/autoadd/animal_crossing/r.ogg",length=0.193}}
L["s"]={{path="chatsounds/autoadd/animal_crossing/s.ogg",length=0.225}}
L["t"]={{path="chatsounds/autoadd/animal_crossing/t.ogg",length=0.193}}
L["u"]={{path="chatsounds/autoadd/animal_crossing/u.ogg",length=0.193}}
L["v"]={{path="chatsounds/autoadd/animal_crossing/v.ogg",length=0.161}}
L["w"]={{path="chatsounds/autoadd/animal_crossing/w.ogg",length=0.225}}
L["y"]={{path="chatsounds/autoadd/animal_crossing/y.ogg",length=0.225}}
L["z"]={{path="chatsounds/autoadd/animal_crossing/z.ogg",length=0.193}}
c.EndList()