c.StartList("awesomenauts")
L["an enemy has been killed"]={{path="chatsounds/autoadd/awesomenauts/an enemy has been killed.ogg",length=4.323}}
L["aylataunt"]={{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt1.ogg",length=1.494},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt10.ogg",length=1.550},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt11.ogg",length=7.830},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt12.ogg",length=1.749},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt2.ogg",length=1.193},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt3.ogg",length=2.144},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt4.ogg",length=5.080},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt5.ogg",length=2.501},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt6.ogg",length=1.561},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt7.ogg",length=2.208},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt8.ogg",length=1.612},{path="chatsounds/autoadd/awesomenauts/aylataunt/aylataunt9.ogg",length=2.037}}
L["blue team dominating"]={{path="chatsounds/autoadd/awesomenauts/blue team dominating.ogg",length=4.069}}
L["clunktaunt"]={{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt1.ogg",length=2.121},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt2.ogg",length=2.310},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt3.ogg",length=1.934},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt4.ogg",length=2.328},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt5.ogg",length=2.793},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt6.ogg",length=3.122},{path="chatsounds/autoadd/awesomenauts/clunktaunt/v-cl-taunt7.ogg",length=3.184}}
L["derpltaunt"]={{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt1.ogg",length=3.645},{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt2.ogg",length=4.233},{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt3.ogg",length=3.941},{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt4.ogg",length=4.142},{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt5.ogg",length=3.880},{path="chatsounds/autoadd/awesomenauts/derpltaunt/v-dz-taunt6.ogg",length=2.258}}
L["froggygtaunt"]={{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt1.ogg",length=1.625},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt2.ogg",length=1.058},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt3.ogg",length=1.820},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt4.ogg",length=1.303},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt5.ogg",length=2.606},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt6.ogg",length=2.805},{path="chatsounds/autoadd/awesomenauts/froggygtaunt/v-fg-taunt7.ogg",length=1.390}}
L["genjitaunt"]={{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt1.ogg",length=2.525},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt10.ogg",length=3.099},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt2.ogg",length=1.317},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt3.ogg",length=3.184},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt4.ogg",length=3.037},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt5.ogg",length=3.293},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt6.ogg",length=3.869},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt7.ogg",length=3.183},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt8.ogg",length=2.419},{path="chatsounds/autoadd/awesomenauts/genjitaunt/v-bf-taunt9.ogg",length=4.075}}
L["gnawtaunt"]={{path="chatsounds/autoadd/awesomenauts/gnawtaunt/v-gn-taunt1.ogg",length=1.412},{path="chatsounds/autoadd/awesomenauts/gnawtaunt/v-gn-taunt2.ogg",length=2.003},{path="chatsounds/autoadd/awesomenauts/gnawtaunt/v-gn-taunt3.ogg",length=2.261},{path="chatsounds/autoadd/awesomenauts/gnawtaunt/v-gn-taunt4.ogg",length=1.665},{path="chatsounds/autoadd/awesomenauts/gnawtaunt/v-gn-taunt5.ogg",length=2.190}}
L["leontaunt"]={{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt1.ogg",length=1.049},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt2.ogg",length=1.907},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt3.ogg",length=2.139},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt4.ogg",length=1.127},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt5.ogg",length=2.076},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt6.ogg",length=2.638},{path="chatsounds/autoadd/awesomenauts/leontaunt/v-lc-taunt7.ogg",length=2.694}}
L["lonestartaunt"]={{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt1.ogg",length=1.635},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt2.ogg",length=1.796},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt3.ogg",length=0.953},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt4.ogg",length=1.226},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt5.ogg",length=1.267},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt6.ogg",length=0.892},{path="chatsounds/autoadd/awesomenauts/lonestartaunt/v-sl-taunt7.ogg",length=1.038}}
L["raelynntaunt"]={{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt1.ogg",length=3.518},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt2.ogg",length=2.167},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt3.ogg",length=1.691},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt4.ogg",length=2.229},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt5.ogg",length=3.142},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt6.ogg",length=2.513},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt7.ogg",length=2.322},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt8.ogg",length=2.530},{path="chatsounds/autoadd/awesomenauts/raelynntaunt/v-rl-taunt9.ogg",length=2.320}}
L["red team dominating"]={{path="chatsounds/autoadd/awesomenauts/red team dominating.ogg",length=3.864}}
L["vinnietaunt"]={{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt1.ogg",length=2.481},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt2.ogg",length=2.489},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt3.ogg",length=2.729},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt4.ogg",length=2.428},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt5.ogg",length=1.795},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt6.ogg",length=3.882},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt7.ogg",length=2.814},{path="chatsounds/autoadd/awesomenauts/vinnietaunt/v-vs-taunt8.ogg",length=1.764}}
L["voltartaunt"]={{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt1.ogg",length=3.192},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt2.ogg",length=3.174},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt3.ogg",length=2.609},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt4.ogg",length=1.845},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt5.ogg",length=2.353},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt6.ogg",length=2.864},{path="chatsounds/autoadd/awesomenauts/voltartaunt/v-vo-taunt7.ogg",length=2.983}}
L["you have killed a enemy"]={{path="chatsounds/autoadd/awesomenauts/you have killed a enemy.ogg",length=4.706}}
L["your base is under attack"]={{path="chatsounds/autoadd/awesomenauts/your base is under attack.ogg",length=4.498}}
L["yuritaunt"]={{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt1.ogg",length=2.519},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt2.ogg",length=2.303},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt3.ogg",length=2.849},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt4.ogg",length=2.533},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt5.ogg",length=3.728},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt6.ogg",length=2.529},{path="chatsounds/autoadd/awesomenauts/yuritaunt/v-yr-taunt7.ogg",length=3.251}}
c.EndList()