c.StartList("bejeweledtwist")
L["badloop"]={{path="chatsounds/autoadd/bejeweledtwist/badloop.ogg",length=3.123}}
L["badmove"]={{path="chatsounds/autoadd/bejeweledtwist/badmove.ogg",length=0.627}}
L["blitzcountup"]={{path="chatsounds/autoadd/bejeweledtwist/blitzcountup.ogg",length=0.442}}
L["bombexplode"]={{path="chatsounds/autoadd/bejeweledtwist/bombexplode.ogg",length=1.980}}
L["chainparticle1"]={{path="chatsounds/autoadd/bejeweledtwist/chainparticle1.ogg",length=0.782}}
L["challengecompleted"]={{path="chatsounds/autoadd/bejeweledtwist/challengecompleted.ogg",length=6.661}}
L["challengeunlock"]={{path="chatsounds/autoadd/bejeweledtwist/challengeunlock.ogg",length=2.769}}
L["coalblasted"]={{path="chatsounds/autoadd/bejeweledtwist/coalblasted.ogg",length=1.379}}
L["combo"]={{path="chatsounds/autoadd/bejeweledtwist/combo/1.ogg",length=0.836},{path="chatsounds/autoadd/bejeweledtwist/combo/2.ogg",length=0.836},{path="chatsounds/autoadd/bejeweledtwist/combo/3.ogg",length=2.105},{path="chatsounds/autoadd/bejeweledtwist/combo/4.ogg",length=2.105},{path="chatsounds/autoadd/bejeweledtwist/combo/5.ogg",length=2.105},{path="chatsounds/autoadd/bejeweledtwist/combo/6.ogg",length=2.105},{path="chatsounds/autoadd/bejeweledtwist/combo/7.ogg",length=2.105}}
L["counterwarning"]={{path="chatsounds/autoadd/bejeweledtwist/counterwarning.ogg",length=2.501}}
L["doomgemappears"]={{path="chatsounds/autoadd/bejeweledtwist/doomgemappears.ogg",length=3.154}}
L["doomgemcountdown"]={{path="chatsounds/autoadd/bejeweledtwist/doomgemcountdown.ogg",length=2.356}}
L["doomgemdestroyed"]={{path="chatsounds/autoadd/bejeweledtwist/doomgemdestroyed.ogg",length=6.647}}
L["doomgemgameover"]={{path="chatsounds/autoadd/bejeweledtwist/doomgemgameover.ogg",length=7.938}}
L["doubleset"]={{path="chatsounds/autoadd/bejeweledtwist/doubleset.ogg",length=1.404}}
L["electroexplode"]={{path="chatsounds/autoadd/bejeweledtwist/electroexplode.ogg",length=3.830}}
L["electrogemcreated"]={{path="chatsounds/autoadd/bejeweledtwist/electrogemcreated.ogg",length=2.896}}
L["endfinal"]={{path="chatsounds/autoadd/bejeweledtwist/endfinal.ogg",length=8.323}}
L["flamelightning"]={{path="chatsounds/autoadd/bejeweledtwist/flamelightning.ogg",length=3.707}}
L["fruitappears"]={{path="chatsounds/autoadd/bejeweledtwist/fruitappears.ogg",length=4.531}}
L["fruitbonuscount"]={{path="chatsounds/autoadd/bejeweledtwist/fruitbonuscount.ogg",length=1.873}}
L["gameunlocked"]={{path="chatsounds/autoadd/bejeweledtwist/gameunlocked.ogg",length=5.838}}
L["gemcountdown"]={{path="chatsounds/autoadd/bejeweledtwist/gemcountdown.ogg",length=2.636}}
L["gemcountdowndestroyed"]={{path="chatsounds/autoadd/bejeweledtwist/gemcountdowndestroyed.ogg",length=2.424}}
L["gemfruitdestroyed"]={{path="chatsounds/autoadd/bejeweledtwist/gemfruitdestroyed.ogg",length=8.125}}
L["gemhit"]={{path="chatsounds/autoadd/bejeweledtwist/gemhit.ogg",length=0.483}}
L["gemlockbreak"]={{path="chatsounds/autoadd/bejeweledtwist/gemlockbreak.ogg",length=2.508}}
L["gemlockend"]={{path="chatsounds/autoadd/bejeweledtwist/gemlockend.ogg",length=1.848}}
L["gemlockstart"]={{path="chatsounds/autoadd/bejeweledtwist/gemlockstart.ogg",length=0.837}}
L["gemprelock"]={{path="chatsounds/autoadd/bejeweledtwist/gemprelock.ogg",length=1.355}}
L["gemshatters"]={{path="chatsounds/autoadd/bejeweledtwist/gemshatters.ogg",length=1.870}}
L["geode"]={{path="chatsounds/autoadd/bejeweledtwist/geode.ogg",length=0.400}}
L["goodloop"]={{path="chatsounds/autoadd/bejeweledtwist/goodloop.ogg",length=12.946}}
L["multiplierup2"]={{path="chatsounds/autoadd/bejeweledtwist/multiplierup2/1.ogg",length=1.641},{path="chatsounds/autoadd/bejeweledtwist/multiplierup2/2.ogg",length=1.549},{path="chatsounds/autoadd/bejeweledtwist/multiplierup2/3.ogg",length=1.462},{path="chatsounds/autoadd/bejeweledtwist/multiplierup2/4.ogg",length=1.380}}
L["powergemcreated"]={{path="chatsounds/autoadd/bejeweledtwist/powergemcreated.ogg",length=2.937}}
L["purr"]={{path="chatsounds/autoadd/bejeweledtwist/purr.ogg",length=8.005}}
L["rankcompletion"]={{path="chatsounds/autoadd/bejeweledtwist/rankcompletion.ogg",length=2.325}}
L["rewind"]={{path="chatsounds/autoadd/bejeweledtwist/rewind.ogg",length=2.861}}
L["siren"]={{path="chatsounds/autoadd/bejeweledtwist/siren.ogg",length=1.110}}
L["sixmatch"]={{path="chatsounds/autoadd/bejeweledtwist/sixmatch.ogg",length=2.704}}
L["skulladded"]={{path="chatsounds/autoadd/bejeweledtwist/skulladded.ogg",length=1.206}}
L["speedbonus"]={{path="chatsounds/autoadd/bejeweledtwist/speedbonus.ogg",length=3.590}}
L["spinnerappears"]={{path="chatsounds/autoadd/bejeweledtwist/spinnerappears.ogg",length=3.404}}
L["spinnerunlock"]={{path="chatsounds/autoadd/bejeweledtwist/spinnerunlock.ogg",length=1.609}}
L["spinsequencer"]={{path="chatsounds/autoadd/bejeweledtwist/spinsequencer.ogg",length=2.352}}
L["supergemcreate"]={{path="chatsounds/autoadd/bejeweledtwist/supergemcreate.ogg",length=3.550}}
L["tallyzoomin"]={{path="chatsounds/autoadd/bejeweledtwist/tallyzoomin.ogg",length=1.518}}
L["transarrival"]={{path="chatsounds/autoadd/bejeweledtwist/transarrival.ogg",length=4.131}}
L["transengineignition"]={{path="chatsounds/autoadd/bejeweledtwist/transengineignition.ogg",length=3.159}}
L["transengineloop"]={{path="chatsounds/autoadd/bejeweledtwist/transengineloop.ogg",length=2.513}}
L["transfer"]={{path="chatsounds/autoadd/bejeweledtwist/transfer.ogg",length=0.833}}
L["transpreignition"]={{path="chatsounds/autoadd/bejeweledtwist/transpreignition.ogg",length=1.405}}
L["transspacenoise"]={{path="chatsounds/autoadd/bejeweledtwist/transspacenoise.ogg",length=6.035}}
L["triallimit"]={{path="chatsounds/autoadd/bejeweledtwist/triallimit.ogg",length=3.101}}
L["trialunlock"]={{path="chatsounds/autoadd/bejeweledtwist/trialunlock.ogg",length=3.768}}
L["trophyawarded"]={{path="chatsounds/autoadd/bejeweledtwist/trophyawarded.ogg",length=5.421}}
L["tutorialcomplete"]={{path="chatsounds/autoadd/bejeweledtwist/tutorialcomplete.ogg",length=4.206}}
L["tutorialmatch"]={{path="chatsounds/autoadd/bejeweledtwist/tutorialmatch.ogg",length=1.114}}
L["tutorialsnap"]={{path="chatsounds/autoadd/bejeweledtwist/tutorialsnap.ogg",length=1.219}}
L["xlose"]={{path="chatsounds/autoadd/bejeweledtwist/xlose.ogg",length=4.764}}
L["xwheelspin"]={{path="chatsounds/autoadd/bejeweledtwist/xwheelspin/1.ogg",length=0.063},{path="chatsounds/autoadd/bejeweledtwist/xwheelspin/2.ogg",length=0.053}}
L["xwin"]={{path="chatsounds/autoadd/bejeweledtwist/xwin/1.ogg",length=3.227},{path="chatsounds/autoadd/bejeweledtwist/xwin/2.ogg",length=2.530}}
L["zen"]={{path="chatsounds/autoadd/bejeweledtwist/zen.ogg",length=1.636}}
L["zenstart"]={{path="chatsounds/autoadd/bejeweledtwist/zenstart.ogg",length=3.999}}
L["zentransition"]={{path="chatsounds/autoadd/bejeweledtwist/zentransition/1.ogg",length=3.919},{path="chatsounds/autoadd/bejeweledtwist/zentransition/2.ogg",length=3.143},{path="chatsounds/autoadd/bejeweledtwist/zentransition/3.ogg",length=5.162}}
c.EndList()