c.StartList("classicdoom")
L["archvile"]={{path="chatsounds/autoadd/classicdoom/archvile.ogg",length=1.719}}
L["archviledeath"]={{path="chatsounds/autoadd/classicdoom/archviledeath.ogg",length=1.719}}
L["baronofhell"]={{path="chatsounds/autoadd/classicdoom/baronofhell.ogg",length=1.719}}
L["baronofhelldeath"]={{path="chatsounds/autoadd/classicdoom/baronofhelldeath.ogg",length=1.719}}
L["damage"]={{path="chatsounds/autoadd/classicdoom/damage.ogg",length=1.719}}
L["death"]={{path="chatsounds/autoadd/classicdoom/death.ogg",length=1.719}}
L["grunt"]={{path="chatsounds/autoadd/classicdoom/grunt.ogg",length=1.719}}
L["imp"]={{path="chatsounds/autoadd/classicdoom/imp.ogg",length=1.719}}
L["teleport"]={{path="chatsounds/autoadd/classicdoom/teleport.ogg",length=1.719}}
c.EndList()