c.StartList("combat_arms")
L["doublekill"]={{path="chatsounds/autoadd/combat_arms/doublekill.ogg",length=1.408}}
L["eight"]={{path="chatsounds/autoadd/combat_arms/eight.ogg",length=1.361}}
L["fantastic"]={{path="chatsounds/autoadd/combat_arms/fantastic.ogg",length=1.672}}
L["five"]={{path="chatsounds/autoadd/combat_arms/five.ogg",length=1.245}}
L["four"]={{path="chatsounds/autoadd/combat_arms/four.ogg",length=1.192}}
L["headshot"]={{path="chatsounds/autoadd/combat_arms/headshot.ogg",length=0.929}}
L["multikill"]={{path="chatsounds/autoadd/combat_arms/multikill.ogg",length=1.474}}
L["nine"]={{path="chatsounds/autoadd/combat_arms/nine.ogg",length=1.307}}
L["one"]={{path="chatsounds/autoadd/combat_arms/one.ogg",length=1.243}}
L["planting a mine"]={{path="chatsounds/autoadd/combat_arms/planting a mine.ogg",length=1.756}}
L["quarantinecountdownmusic"]={{path="chatsounds/autoadd/combat_arms/quarantinecountdownmusic.ogg",length=12.684}}
L["seven"]={{path="chatsounds/autoadd/combat_arms/seven.ogg",length=1.155}}
L["six"]={{path="chatsounds/autoadd/combat_arms/six.ogg",length=1.091}}
L["ten"]={{path="chatsounds/autoadd/combat_arms/ten.ogg",length=0.961}}
L["three"]={{path="chatsounds/autoadd/combat_arms/three.ogg",length=1.227}}
L["two"]={{path="chatsounds/autoadd/combat_arms/two.ogg",length=0.998}}
L["ultrakill"]={{path="chatsounds/autoadd/combat_arms/ultrakill.ogg",length=1.398}}
L["unbelievable"]={{path="chatsounds/autoadd/combat_arms/unbelievable.ogg",length=1.810}}
c.EndList()