c.StartList("console_startups")
L["dreamcaststartup"]={{path="chatsounds/autoadd/console_startups/dreamcaststartup.ogg",length=7.765}}
L["dsstartup"]={{path="chatsounds/autoadd/console_startups/dsstartup/1.ogg",length=1.280},{path="chatsounds/autoadd/console_startups/dsstartup/2.ogg",length=0.954}}
L["gamecubestartup"]={{path="chatsounds/autoadd/console_startups/gamecubestartup/1.ogg",length=4.818},{path="chatsounds/autoadd/console_startups/gamecubestartup/2.ogg",length=5.076},{path="chatsounds/autoadd/console_startups/gamecubestartup/3.ogg",length=5.591}}
L["gbastartup"]={{path="chatsounds/autoadd/console_startups/gbastartup.ogg",length=3.709}}
L["n64startup"]={{path="chatsounds/autoadd/console_startups/n64startup.ogg",length=3.729}}
L["neogeostartup"]={{path="chatsounds/autoadd/console_startups/neogeostartup.ogg",length=7.372}}
L["ps1startup"]={{path="chatsounds/autoadd/console_startups/ps1startup.ogg",length=14.233}}
L["ps2buttonpress"]={{path="chatsounds/autoadd/console_startups/ps2buttonpress.ogg",length=0.785}}
L["ps2diskerror"]={{path="chatsounds/autoadd/console_startups/ps2diskerror.ogg",length=7.020}}
L["ps2gomenu"]={{path="chatsounds/autoadd/console_startups/ps2gomenu.ogg",length=12.074}}
L["ps2scroll"]={{path="chatsounds/autoadd/console_startups/ps2scroll.ogg",length=0.080}}
L["ps2startup"]={{path="chatsounds/autoadd/console_startups/ps2startup.ogg",length=10.447}}
L["ps3startup"]={{path="chatsounds/autoadd/console_startups/ps3startup/1.ogg",length=8.049},{path="chatsounds/autoadd/console_startups/ps3startup/2.ogg",length=8.562}}
L["pspstartupfull"]={{path="chatsounds/autoadd/console_startups/pspstartupfull.ogg",length=5.619}}
L["segasaturnstartup"]={{path="chatsounds/autoadd/console_startups/segasaturnstartup/1.ogg",length=7.596},{path="chatsounds/autoadd/console_startups/segasaturnstartup/2.ogg",length=5.727}}
L["wiistartup"]={{path="chatsounds/autoadd/console_startups/wiistartup.ogg",length=4.484}}
L["wiiustartup"]={{path="chatsounds/autoadd/console_startups/wiiustartup.ogg",length=11.530}}
L["xbox360startup"]={{path="chatsounds/autoadd/console_startups/xbox360startup/1.ogg",length=6.565},{path="chatsounds/autoadd/console_startups/xbox360startup/2.ogg",length=7.412}}
L["xboxonestartup"]={{path="chatsounds/autoadd/console_startups/xboxonestartup.ogg",length=2.068}}
L["xboxstartup"]={{path="chatsounds/autoadd/console_startups/xboxstartup.ogg",length=7.262}}
c.EndList()