c.StartList("csgo")
L["arm bomb"]={{path="chatsounds/autoadd/csgo/arm bomb.ogg",length=1.240}}
L["bombplanted"]={{path="chatsounds/autoadd/csgo/bombplanted/bombplanted.ogg",length=41.131},{path="chatsounds/autoadd/csgo/bombplanted/bombplanted2.ogg",length=37.944}}
L["bombtenseccount"]={{path="chatsounds/autoadd/csgo/bombtenseccount/bombtenseccount.ogg",length=12.736},{path="chatsounds/autoadd/csgo/bombtenseccount/bombtenseccount2.ogg",length=13.206}}
L["csgocheer"]={{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer01 2.ogg",length=0.949},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer01 3.ogg",length=1.572},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer01.ogg",length=0.833},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer02 2.ogg",length=1.163},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer02 3.ogg",length=1.384},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer02.ogg",length=1.394},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer03 2.ogg",length=1.009},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer03.ogg",length=0.641},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer04 2.ogg",length=1.268},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer04.ogg",length=1.642},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer05 2.ogg",length=1.159},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer05.ogg",length=0.812},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer06 2.ogg",length=1.658},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer06.ogg",length=1.074},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer08 2.ogg",length=1.112},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer08.ogg",length=1.188},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer09.ogg",length=0.825},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer11.ogg",length=0.959},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer12.ogg",length=1.824},{path="chatsounds/autoadd/csgo/csgocheer/radiobotcheer13.ogg",length=1.909}}
L["deathcam"]={{path="chatsounds/autoadd/csgo/deathcam/deathcam.ogg",length=5.082},{path="chatsounds/autoadd/csgo/deathcam/deathcam2.ogg",length=3.462}}
L["hawk"]={{path="chatsounds/autoadd/csgo/hawk/hawk_01.ogg",length=1.731},{path="chatsounds/autoadd/csgo/hawk/hawk_02.ogg",length=1.746},{path="chatsounds/autoadd/csgo/hawk/hawk_05.ogg",length=1.696},{path="chatsounds/autoadd/csgo/hawk/hawk_06.ogg",length=1.743}}
L["i dont know what to do"]={{path="chatsounds/autoadd/csgo/i dont know what to do.ogg",length=1.182}}
L["loon"]={{path="chatsounds/autoadd/csgo/loon/loon_01.ogg",length=0.729},{path="chatsounds/autoadd/csgo/loon/loon_02.ogg",length=0.751},{path="chatsounds/autoadd/csgo/loon/loon_03.ogg",length=0.810},{path="chatsounds/autoadd/csgo/loon/loon_04.ogg",length=1.010},{path="chatsounds/autoadd/csgo/loon/loon_05.ogg",length=0.755}}
L["lostround"]={{path="chatsounds/autoadd/csgo/lostround/lostround.ogg",length=17.908},{path="chatsounds/autoadd/csgo/lostround/lostround2.ogg",length=12.213}}
L["mainmenu"]={{path="chatsounds/autoadd/csgo/mainmenu/mainmenu2.ogg",length=51.110}}
L["selectteam"]={{path="chatsounds/autoadd/csgo/selectteam/selectteam.ogg",length=21.696},{path="chatsounds/autoadd/csgo/selectteam/selectteam2.ogg",length=18.483}}
L["startaction"]={{path="chatsounds/autoadd/csgo/startaction/startaction_01.ogg",length=39.093},{path="chatsounds/autoadd/csgo/startaction/startaction_012.ogg",length=36.455}}
L["startround"]={{path="chatsounds/autoadd/csgo/startround/startround_01.ogg",length=25.588},{path="chatsounds/autoadd/csgo/startround/startround_012.ogg",length=34.026},{path="chatsounds/autoadd/csgo/startround/startround_02.ogg",length=23.629},{path="chatsounds/autoadd/csgo/startround/startround_03.ogg",length=23.159}}
L["tenseccount"]={{path="chatsounds/autoadd/csgo/tenseccount/tenseccount.ogg",length=15.609},{path="chatsounds/autoadd/csgo/tenseccount/tenseccount2.ogg",length=19.841}}
L["this is over"]={{path="chatsounds/autoadd/csgo/this is over.ogg",length=1.949}}
L["wah"]={{path="chatsounds/autoadd/csgo/wah.ogg",length=0.544}}
L["who will protect me"]={{path="chatsounds/autoadd/csgo/who will protect me.ogg",length=0.829}}
L["wonround"]={{path="chatsounds/autoadd/csgo/wonround/wonround.ogg",length=33.477},{path="chatsounds/autoadd/csgo/wonround/wonround2.ogg",length=12.553}}
L["woof"]={{path="chatsounds/autoadd/csgo/woof/dog_med_inside_bark_1.ogg",length=0.363},{path="chatsounds/autoadd/csgo/woof/dog_med_inside_bark_3.ogg",length=0.391},{path="chatsounds/autoadd/csgo/woof/dog_med_inside_bark_4.ogg",length=0.342},{path="chatsounds/autoadd/csgo/woof/dog_med_inside_bark_5.ogg",length=0.422}}
c.EndList()