c.StartList("dannyblackguy")
L["911"]={{path="chatsounds/autoadd/dannyblackguy/911.ogg",length=0.667}}
L["barack obama"]={{path="chatsounds/autoadd/dannyblackguy/barack obama.ogg",length=0.959}}
L["biglezshow"]={{path="chatsounds/autoadd/dannyblackguy/biglezshow/clarence shut the fuck up.ogg",length=1.426},{path="chatsounds/autoadd/dannyblackguy/biglezshow/donnys ya man.ogg",length=1.000},{path="chatsounds/autoadd/dannyblackguy/biglezshow/fuckin pussie.ogg",length=2.127},{path="chatsounds/autoadd/dannyblackguy/biglezshow/i ant going back.ogg",length=1.871},{path="chatsounds/autoadd/dannyblackguy/biglezshow/if its not made of paper i cant help.ogg",length=2.356},{path="chatsounds/autoadd/dannyblackguy/biglezshow/im donny the dealer.ogg",length=1.514},{path="chatsounds/autoadd/dannyblackguy/biglezshow/its called the stealthy fucka.ogg",length=1.720},{path="chatsounds/autoadd/dannyblackguy/biglezshow/save your breath you feathered fuck.ogg",length=1.985},{path="chatsounds/autoadd/dannyblackguy/biglezshow/what are ya talkin to me.ogg",length=0.730},{path="chatsounds/autoadd/dannyblackguy/biglezshow/yeah shut the fuck up clarence.ogg",length=1.958},{path="chatsounds/autoadd/dannyblackguy/biglezshow/your fuckin joken.ogg",length=1.871},{path="chatsounds/autoadd/dannyblackguy/biglezshow/your fucking going straight to prision.ogg",length=1.780}}
L["but you must be some kind of retard"]={{path="chatsounds/autoadd/dannyblackguy/but you must be some kind of retard.ogg",length=1.900}}
L["cyka"]={{path="chatsounds/autoadd/dannyblackguy/cyka.ogg",length=0.550}}
L["danny"]={{path="chatsounds/autoadd/dannyblackguy/danny.ogg",length=0.315}}
L["japanese people can fly"]={{path="chatsounds/autoadd/dannyblackguy/japanese people can fly.ogg",length=1.811}}
L["look at my fucking car"]={{path="chatsounds/autoadd/dannyblackguy/look at my fucking car.ogg",length=1.881}}
L["rated rp"]={{path="chatsounds/autoadd/dannyblackguy/rated rp.ogg",length=1.906}}
L["senator armstrong"]={{path="chatsounds/autoadd/dannyblackguy/senator armstrong/checked the internet lately.ogg",length=1.297},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/dont fuck with this senitor.ogg",length=1.760},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/fuck the media.ogg",length=1.350},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/making the mother of all omelets here jack.ogg",length=4.150},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/played college ball ya know.ogg",length=1.996},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/they will make america great again.ogg",length=3.023},{path="chatsounds/autoadd/dannyblackguy/senator armstrong/well if it isnt saucy jack.ogg",length=2.552}}
L["steamnames"]={{path="chatsounds/autoadd/dannyblackguy/steamnames/bazzinga xd.ogg",length=2.748},{path="chatsounds/autoadd/dannyblackguy/steamnames/beating off in church with dad.ogg",length=3.207},{path="chatsounds/autoadd/dannyblackguy/steamnames/congratulations future cumlords.ogg",length=3.240},{path="chatsounds/autoadd/dannyblackguy/steamnames/crying to radiohead isnt lame.ogg",length=3.658},{path="chatsounds/autoadd/dannyblackguy/steamnames/dont call it a cumback.ogg",length=2.300},{path="chatsounds/autoadd/dannyblackguy/steamnames/famous dog porn.ogg",length=2.846},{path="chatsounds/autoadd/dannyblackguy/steamnames/first the kiss then the cum.ogg",length=3.000},{path="chatsounds/autoadd/dannyblackguy/steamnames/get paid money to worship satan.ogg",length=3.356},{path="chatsounds/autoadd/dannyblackguy/steamnames/i cum slamed ya mum.ogg",length=2.478},{path="chatsounds/autoadd/dannyblackguy/steamnames/illegal dubstep mixtape.ogg",length=2.637},{path="chatsounds/autoadd/dannyblackguy/steamnames/the fatal cum thought.ogg",length=2.000},{path="chatsounds/autoadd/dannyblackguy/steamnames/true badass anime dad.ogg",length=3.137},{path="chatsounds/autoadd/dannyblackguy/steamnames/we jedi sniper.ogg",length=2.200}}
L["this stuff is your history"]={{path="chatsounds/autoadd/dannyblackguy/this stuff is your history.ogg",length=1.525}}
L["welcome home"]={{path="chatsounds/autoadd/dannyblackguy/welcome home.ogg",length=0.986}}
L["what the fuck"]={{path="chatsounds/autoadd/dannyblackguy/what the fuck.ogg",length=1.119}}
L["you son of a bitch"]={{path="chatsounds/autoadd/dannyblackguy/you son of a bitch.ogg",length=1.073}}
L["zap zap mother fucker"]={{path="chatsounds/autoadd/dannyblackguy/zap zap mother fucker.ogg",length=1.589}}
c.EndList()