c.StartList("drumkit")
L["bd"]={{path="chatsounds/autoadd/drumkit/bd/bd1.ogg",length=0.171},{path="chatsounds/autoadd/drumkit/bd/bd2.ogg",length=0.171},{path="chatsounds/autoadd/drumkit/bd/bd3.ogg",length=0.171},{path="chatsounds/autoadd/drumkit/bd/bd4.ogg",length=0.171}}
L["crsh1"]={{path="chatsounds/autoadd/drumkit/crsh1.ogg",length=4.533}}
L["crsh2"]={{path="chatsounds/autoadd/drumkit/crsh2.ogg",length=7.537}}
L["hc"]={{path="chatsounds/autoadd/drumkit/hc/ch1.ogg",length=0.328},{path="chatsounds/autoadd/drumkit/hc/ch2.ogg",length=0.301},{path="chatsounds/autoadd/drumkit/hc/ch3.ogg",length=0.563},{path="chatsounds/autoadd/drumkit/hc/ch4.ogg",length=0.301},{path="chatsounds/autoadd/drumkit/hc/chm1.ogg",length=0.563},{path="chatsounds/autoadd/drumkit/hc/chm2.ogg",length=0.537},{path="chatsounds/autoadd/drumkit/hc/chm3.ogg",length=0.380},{path="chatsounds/autoadd/drumkit/hc/chm4.ogg",length=0.484}}
L["ho"]={{path="chatsounds/autoadd/drumkit/ho/coh1.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/ho/coh2.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/ho/coh3.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/ho/coh4.ogg",length=1.529}}
L["rde1"]={{path="chatsounds/autoadd/drumkit/rde1.ogg",length=3.044}}
L["rde2"]={{path="chatsounds/autoadd/drumkit/rde2.ogg",length=4.533}}
L["rim"]={{path="chatsounds/autoadd/drumkit/rim.ogg",length=0.145}}
L["snr"]={{path="chatsounds/autoadd/drumkit/snr/snare1.ogg",length=0.380},{path="chatsounds/autoadd/drumkit/snr/snare2.ogg",length=0.275},{path="chatsounds/autoadd/drumkit/snr/snare3.ogg",length=0.249},{path="chatsounds/autoadd/drumkit/snr/snare4.ogg",length=0.354}}
L["tmh"]={{path="chatsounds/autoadd/drumkit/tmh/tomhigh1.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/tmh/tomhigh2.ogg",length=1.529}}
L["tml"]={{path="chatsounds/autoadd/drumkit/tml/tomlow1.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/tml/tomlow2.ogg",length=1.529}}
L["tmm"]={{path="chatsounds/autoadd/drumkit/tmm/tommid1.ogg",length=1.529},{path="chatsounds/autoadd/drumkit/tmm/tommid2.ogg",length=1.529}}
c.EndList()