c.StartList("gta_sa_carl_johnson")
L["ah shit here we go again"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/ah shit here we go again.ogg",length=2.780}}
L["cj death"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/1.ogg",length=0.387},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/2.ogg",length=0.288},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/3.ogg",length=0.406},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/4.ogg",length=0.541},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/5.ogg",length=0.610},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/6.ogg",length=0.556},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/7.ogg",length=0.710},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/8.ogg",length=0.515},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj death/9.ogg",length=0.384}}
L["cj drowning"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/1.ogg",length=0.388},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/2.ogg",length=0.311},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/3.ogg",length=0.415},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/4.ogg",length=0.575},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/5.ogg",length=0.337},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj drowning/6.ogg",length=0.496}}
L["cj onfire"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/1.ogg",length=0.410},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/2.ogg",length=0.303},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/3.ogg",length=0.436},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/4.ogg",length=0.629},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/5.ogg",length=0.749},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/6.ogg",length=0.647},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/7.ogg",length=0.457},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj onfire/8.ogg",length=0.392}}
L["cj painbig"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/1.ogg",length=0.531},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/10.ogg",length=0.322},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/11.ogg",length=0.594},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/12.ogg",length=0.603},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/13.ogg",length=0.629},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/14.ogg",length=0.360},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/2.ogg",length=0.493},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/3.ogg",length=0.389},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/4.ogg",length=0.349},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/5.ogg",length=0.501},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/6.ogg",length=0.316},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/7.ogg",length=0.284},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/8.ogg",length=0.343},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painbig/9.ogg",length=0.554}}
L["cj painimpact"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/1.ogg",length=0.431},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/10.ogg",length=0.324},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/11.ogg",length=0.332},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/12.ogg",length=0.300},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/13.ogg",length=0.324},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/14.ogg",length=0.220},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/15.ogg",length=0.362},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/16.ogg",length=0.225},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/17.ogg",length=0.266},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/18.ogg",length=0.392},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/19.ogg",length=0.294},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/2.ogg",length=0.295},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/20.ogg",length=0.238},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/21.ogg",length=0.200},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/3.ogg",length=0.472},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/4.ogg",length=0.227},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/5.ogg",length=0.355},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/6.ogg",length=0.180},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/7.ogg",length=0.270},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/8.ogg",length=0.239},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painimpact/9.ogg",length=0.216}}
L["cj painsmall"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/1.ogg",length=0.360},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/10.ogg",length=0.311},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/11.ogg",length=0.270},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/12.ogg",length=0.396},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/13.ogg",length=0.294},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/14.ogg",length=0.296},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/15.ogg",length=0.231},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/16.ogg",length=0.324},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/17.ogg",length=0.379},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/18.ogg",length=0.240},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/19.ogg",length=0.311},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/2.ogg",length=0.331},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/20.ogg",length=0.298},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/21.ogg",length=0.273},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/22.ogg",length=0.202},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/23.ogg",length=0.298},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/24.ogg",length=0.652},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/3.ogg",length=0.227},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/4.ogg",length=0.189},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/5.ogg",length=0.205},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/6.ogg",length=0.228},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/7.ogg",length=0.240},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/8.ogg",length=0.257},{path="chatsounds/autoadd/gta_sa_carl_johnson/cj painsmall/9.ogg",length=0.212}}
L["damn"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/damn.ogg",length=0.472}}
L["i dont need this shit"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/i dont need this shit.ogg",length=0.962}}
L["i hate gravity"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/i hate gravity.ogg",length=0.988}}
L["oh fuck"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/oh fuck.ogg",length=0.815}}
L["oh hell no"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/oh hell no.ogg",length=0.907}}
L["oh no"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/oh no.ogg",length=0.664}}
L["shit"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/shit/1.ogg",length=0.639},{path="chatsounds/autoadd/gta_sa_carl_johnson/shit/2.ogg",length=0.637}}
L["what fuckin book"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/what fuckin book.ogg",length=1.213}}
L["what the fuck"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/what the fuck.ogg",length=0.607}}
L["wtf"]={{path="chatsounds/autoadd/gta_sa_carl_johnson/wtf.ogg",length=0.607}}
c.EndList()