c.StartList("halo_announcer")
L["haloinfinite"]={{path="chatsounds/autoadd/halo_announcer/haloinfinite/adios.ogg",length=1.209},{path="chatsounds/autoadd/halo_announcer/haloinfinite/double kill.ogg",length=1.340},{path="chatsounds/autoadd/halo_announcer/haloinfinite/extra crispy.ogg",length=2.434},{path="chatsounds/autoadd/halo_announcer/haloinfinite/hail mary.ogg",length=2.127},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killamanjaro.ogg",length=1.791},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killing frenzy.ogg",length=2.204},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killing spree.ogg",length=1.985},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killionaire.ogg",length=2.028},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killpocalypse.ogg",length=2.020},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killtacular.ogg",length=1.807},{path="chatsounds/autoadd/halo_announcer/haloinfinite/killtrocity.ogg",length=1.929},{path="chatsounds/autoadd/halo_announcer/haloinfinite/overkill.ogg",length=1.327},{path="chatsounds/autoadd/halo_announcer/haloinfinite/rampage.ogg",length=2.131},{path="chatsounds/autoadd/halo_announcer/haloinfinite/running riot.ogg",length=1.649},{path="chatsounds/autoadd/halo_announcer/haloinfinite/triple kill.ogg",length=1.953}}
L["haloreach"]={{path="chatsounds/autoadd/halo_announcer/haloreach/double kill.ogg",length=1.399},{path="chatsounds/autoadd/halo_announcer/haloreach/extermination.ogg",length=2.391},{path="chatsounds/autoadd/halo_announcer/haloreach/first strike.ogg",length=1.660},{path="chatsounds/autoadd/halo_announcer/haloreach/killamanjaro.ogg",length=1.843},{path="chatsounds/autoadd/halo_announcer/haloreach/killing frenzy.ogg",length=1.399},{path="chatsounds/autoadd/halo_announcer/haloreach/killing spree.ogg",length=1.399},{path="chatsounds/autoadd/halo_announcer/haloreach/killionaire.ogg",length=1.346},{path="chatsounds/autoadd/halo_announcer/haloreach/killjoy.ogg",length=1.477},{path="chatsounds/autoadd/halo_announcer/haloreach/killpocalypse.ogg",length=1.555},{path="chatsounds/autoadd/halo_announcer/haloreach/killtacular.ogg",length=1.843},{path="chatsounds/autoadd/halo_announcer/haloreach/killtastrophe.ogg",length=1.947},{path="chatsounds/autoadd/halo_announcer/haloreach/killtrocity.ogg",length=1.608},{path="chatsounds/autoadd/halo_announcer/haloreach/overkill.ogg",length=1.346},{path="chatsounds/autoadd/halo_announcer/haloreach/rampage.ogg",length=1.738},{path="chatsounds/autoadd/halo_announcer/haloreach/running riot.ogg",length=1.346},{path="chatsounds/autoadd/halo_announcer/haloreach/triple kill.ogg",length=1.242},{path="chatsounds/autoadd/halo_announcer/haloreach/yoink.ogg",length=1.399}}
L["mommy milkers"]={{path="chatsounds/autoadd/halo_announcer/mommy milkers.ogg",length=2.127}}
L["no maidens"]={{path="chatsounds/autoadd/halo_announcer/no maidens.ogg",length=2.813}}
L["redditor"]={{path="chatsounds/autoadd/halo_announcer/redditor.ogg",length=1.309}}
L["skill issue"]={{path="chatsounds/autoadd/halo_announcer/skill issue.ogg",length=2.449}}
L["social credit deducted"]={{path="chatsounds/autoadd/halo_announcer/social credit deducted.ogg",length=3.445}}
L["that was sus"]={{path="chatsounds/autoadd/halo_announcer/that was sus.ogg",length=2.575}}
c.EndList()