c.StartList("lisathepainful")
L["bell"]={{path="chatsounds/autoadd/lisathepainful/bell.ogg",length=3.433}}
L["booong"]={{path="chatsounds/autoadd/lisathepainful/booong.ogg",length=1.825}}
L["bradyell"]={{path="chatsounds/autoadd/lisathepainful/bradyell.ogg",length=1.260}}
L["confuse"]={{path="chatsounds/autoadd/lisathepainful/confuse/1.ogg",length=1.867},{path="chatsounds/autoadd/lisathepainful/confuse/2.ogg",length=0.975}}
L["cutesy"]={{path="chatsounds/autoadd/lisathepainful/cutesy.ogg",length=3.736}}
L["damage"]={{path="chatsounds/autoadd/lisathepainful/damage.ogg",length=0.596}}
L["darkness"]={{path="chatsounds/autoadd/lisathepainful/darkness.ogg",length=1.913}}
L["dolphin"]={{path="chatsounds/autoadd/lisathepainful/dolphin.ogg",length=0.902}}
L["echohit"]={{path="chatsounds/autoadd/lisathepainful/echohit.ogg",length=2.046}}
L["fish"]={{path="chatsounds/autoadd/lisathepainful/fish/1.ogg",length=0.275},{path="chatsounds/autoadd/lisathepainful/fish/2.ogg",length=0.415},{path="chatsounds/autoadd/lisathepainful/fish/3.ogg",length=0.697}}
L["fishconsult"]={{path="chatsounds/autoadd/lisathepainful/fishconsult.ogg",length=2.358}}
L["gottadiesometime"]={{path="chatsounds/autoadd/lisathepainful/gottadiesometime.ogg",length=6.722}}
L["joymutantscream"]={{path="chatsounds/autoadd/lisathepainful/joymutantscream.ogg",length=2.230}}
L["misslisa"]={{path="chatsounds/autoadd/lisathepainful/misslisa.ogg",length=0.408}}
L["semihorn"]={{path="chatsounds/autoadd/lisathepainful/semihorn.ogg",length=3.683}}
L["stun"]={{path="chatsounds/autoadd/lisathepainful/stun.ogg",length=1.222}}
L["success"]={{path="chatsounds/autoadd/lisathepainful/success/1.ogg",length=1.954},{path="chatsounds/autoadd/lisathepainful/success/2.ogg",length=4.108}}
L["uh hough"]={{path="chatsounds/autoadd/lisathepainful/uh hough.ogg",length=1.105}}
L["wally"]={{path="chatsounds/autoadd/lisathepainful/wally.ogg",length=3.286}}
L["what"]={{path="chatsounds/autoadd/lisathepainful/what.ogg",length=1.744}}
L["whoa"]={{path="chatsounds/autoadd/lisathepainful/whoa.ogg",length=1.744}}
L["wiggle"]={{path="chatsounds/autoadd/lisathepainful/wiggle.ogg",length=0.496}}
L["woo"]={{path="chatsounds/autoadd/lisathepainful/woo.ogg",length=3.711}}
L["yell"]={{path="chatsounds/autoadd/lisathepainful/yell.ogg",length=1.172}}
L["yoo"]={{path="chatsounds/autoadd/lisathepainful/yoo.ogg",length=1.766}}
c.EndList()