c.StartList("lisa_the_painful")
L["beastyell"]={{path="chatsounds/autoadd/lisa_the_painful/beastyell.ogg",length=3.036}}
L["bell"]={{path="chatsounds/autoadd/lisa_the_painful/bell.ogg",length=3.433}}
L["booong"]={{path="chatsounds/autoadd/lisa_the_painful/booong.ogg",length=1.825}}
L["bradyell"]={{path="chatsounds/autoadd/lisa_the_painful/bradyell.ogg",length=1.260}}
L["confuse"]={{path="chatsounds/autoadd/lisa_the_painful/confuse/1.ogg",length=1.867},{path="chatsounds/autoadd/lisa_the_painful/confuse/2.ogg",length=0.975}}
L["cutesy"]={{path="chatsounds/autoadd/lisa_the_painful/cutesy.ogg",length=3.736}}
L["damage"]={{path="chatsounds/autoadd/lisa_the_painful/damage.ogg",length=0.596}}
L["darkness"]={{path="chatsounds/autoadd/lisa_the_painful/darkness.ogg",length=1.913}}
L["dolphin"]={{path="chatsounds/autoadd/lisa_the_painful/dolphin.ogg",length=0.902}}
L["echohit"]={{path="chatsounds/autoadd/lisa_the_painful/echohit.ogg",length=2.046}}
L["fish"]={{path="chatsounds/autoadd/lisa_the_painful/fish/1.ogg",length=0.275},{path="chatsounds/autoadd/lisa_the_painful/fish/2.ogg",length=0.415},{path="chatsounds/autoadd/lisa_the_painful/fish/3.ogg",length=0.697}}
L["fishconsult"]={{path="chatsounds/autoadd/lisa_the_painful/fishconsult.ogg",length=2.358}}
L["gottadiesometime"]={{path="chatsounds/autoadd/lisa_the_painful/gottadiesometime.ogg",length=6.722}}
L["joymutantscream"]={{path="chatsounds/autoadd/lisa_the_painful/joymutantscream.ogg",length=2.230}}
L["misslisa"]={{path="chatsounds/autoadd/lisa_the_painful/misslisa.ogg",length=0.408}}
L["semihorn"]={{path="chatsounds/autoadd/lisa_the_painful/semihorn.ogg",length=3.683}}
L["stun"]={{path="chatsounds/autoadd/lisa_the_painful/stun.ogg",length=1.222}}
L["success"]={{path="chatsounds/autoadd/lisa_the_painful/success/1.ogg",length=1.954},{path="chatsounds/autoadd/lisa_the_painful/success/2.ogg",length=4.108}}
L["summerbreeze"]={{path="chatsounds/autoadd/lisa_the_painful/summerbreeze.ogg",length=17.545}}
L["uh hough"]={{path="chatsounds/autoadd/lisa_the_painful/uh hough.ogg",length=1.105}}
L["wally"]={{path="chatsounds/autoadd/lisa_the_painful/wally.ogg",length=3.286}}
L["what"]={{path="chatsounds/autoadd/lisa_the_painful/what.ogg",length=1.744}}
L["whoa"]={{path="chatsounds/autoadd/lisa_the_painful/whoa.ogg",length=1.744}}
L["wiggle"]={{path="chatsounds/autoadd/lisa_the_painful/wiggle.ogg",length=0.496}}
L["woo"]={{path="chatsounds/autoadd/lisa_the_painful/woo.ogg",length=3.711}}
L["yell"]={{path="chatsounds/autoadd/lisa_the_painful/yell.ogg",length=1.172}}
L["yoo"]={{path="chatsounds/autoadd/lisa_the_painful/yoo.ogg",length=1.766}}
c.EndList()