c.StartList("minecraft")
L["anvil"]={{path="chatsounds/autoadd/minecraft/anvil.ogg",length=0.814}}
L["cave ambience"]={{path="chatsounds/autoadd/minecraft/cave ambience/cave1.ogg",length=3.564},{path="chatsounds/autoadd/minecraft/cave ambience/cave10.ogg",length=2.556},{path="chatsounds/autoadd/minecraft/cave ambience/cave11.ogg",length=4.860},{path="chatsounds/autoadd/minecraft/cave ambience/cave12.ogg",length=2.448},{path="chatsounds/autoadd/minecraft/cave ambience/cave13.ogg",length=3.816},{path="chatsounds/autoadd/minecraft/cave ambience/cave2.ogg",length=7.020},{path="chatsounds/autoadd/minecraft/cave ambience/cave3.ogg",length=7.812},{path="chatsounds/autoadd/minecraft/cave ambience/cave4.ogg",length=6.444},{path="chatsounds/autoadd/minecraft/cave ambience/cave5.ogg",length=9.252},{path="chatsounds/autoadd/minecraft/cave ambience/cave6.ogg",length=6.444},{path="chatsounds/autoadd/minecraft/cave ambience/cave7.ogg",length=6.156},{path="chatsounds/autoadd/minecraft/cave ambience/cave8.ogg",length=5.040},{path="chatsounds/autoadd/minecraft/cave ambience/cave9.ogg",length=4.068}}
L["chicken"]={{path="chatsounds/autoadd/minecraft/chicken/1.ogg",length=0.563},{path="chatsounds/autoadd/minecraft/chicken/2.ogg",length=0.750},{path="chatsounds/autoadd/minecraft/chicken/3.ogg",length=0.500}}
L["chickenhurt"]={{path="chatsounds/autoadd/minecraft/chickenhurt/1.ogg",length=0.563},{path="chatsounds/autoadd/minecraft/chickenhurt/2.ogg",length=0.375}}
L["cow"]={{path="chatsounds/autoadd/minecraft/cow/1.ogg",length=1.370},{path="chatsounds/autoadd/minecraft/cow/2.ogg",length=1.370},{path="chatsounds/autoadd/minecraft/cow/3.ogg",length=2.000},{path="chatsounds/autoadd/minecraft/cow/4.ogg",length=1.699}}
L["cowhurt"]={{path="chatsounds/autoadd/minecraft/cowhurt/1.ogg",length=0.452},{path="chatsounds/autoadd/minecraft/cowhurt/2.ogg",length=0.452},{path="chatsounds/autoadd/minecraft/cowhurt/3.ogg",length=0.507}}
L["creeper"]={{path="chatsounds/autoadd/minecraft/creeper/1.ogg",length=0.461},{path="chatsounds/autoadd/minecraft/creeper/2.ogg",length=0.485},{path="chatsounds/autoadd/minecraft/creeper/3.ogg",length=0.461},{path="chatsounds/autoadd/minecraft/creeper/4.ogg",length=0.516}}
L["donkey"]={{path="chatsounds/autoadd/minecraft/donkey/idle1.ogg",length=0.397},{path="chatsounds/autoadd/minecraft/donkey/idle2.ogg",length=0.376},{path="chatsounds/autoadd/minecraft/donkey/idle3.ogg",length=0.972}}
L["donkey angry"]={{path="chatsounds/autoadd/minecraft/donkey angry/angry1.ogg",length=1.156},{path="chatsounds/autoadd/minecraft/donkey angry/angry2.ogg",length=0.972}}
L["donkey death"]={{path="chatsounds/autoadd/minecraft/donkey death.ogg",length=1.378}}
L["donkeyhurt"]={{path="chatsounds/autoadd/minecraft/donkeyhurt/hit1.ogg",length=0.520},{path="chatsounds/autoadd/minecraft/donkeyhurt/hit2.ogg",length=0.325},{path="chatsounds/autoadd/minecraft/donkeyhurt/hit3.ogg",length=0.520}}
L["dragongrowl"]={{path="chatsounds/autoadd/minecraft/dragongrowl/growl1.ogg",length=3.000},{path="chatsounds/autoadd/minecraft/dragongrowl/growl2.ogg",length=3.000},{path="chatsounds/autoadd/minecraft/dragongrowl/growl3.ogg",length=3.000},{path="chatsounds/autoadd/minecraft/dragongrowl/growl4.ogg",length=3.000}}
L["enderman"]={{path="chatsounds/autoadd/minecraft/enderman/idle1.ogg",length=0.432},{path="chatsounds/autoadd/minecraft/enderman/idle2.ogg",length=0.540},{path="chatsounds/autoadd/minecraft/enderman/idle3.ogg",length=0.792},{path="chatsounds/autoadd/minecraft/enderman/idle4.ogg",length=0.972},{path="chatsounds/autoadd/minecraft/enderman/idle5.ogg",length=0.792}}
L["enderman death"]={{path="chatsounds/autoadd/minecraft/enderman death.ogg",length=1.620}}
L["enderman hit"]={{path="chatsounds/autoadd/minecraft/enderman hit/hit1.ogg",length=0.576},{path="chatsounds/autoadd/minecraft/enderman hit/hit2.ogg",length=0.540},{path="chatsounds/autoadd/minecraft/enderman hit/hit3.ogg",length=0.576},{path="chatsounds/autoadd/minecraft/enderman hit/hit4.ogg",length=0.396}}
L["enderman portal"]={{path="chatsounds/autoadd/minecraft/enderman portal/portal.ogg",length=0.972},{path="chatsounds/autoadd/minecraft/enderman portal/portal2.ogg",length=0.576}}
L["enderman scream"]={{path="chatsounds/autoadd/minecraft/enderman scream/scream1.ogg",length=1.044},{path="chatsounds/autoadd/minecraft/enderman scream/scream2.ogg",length=1.044},{path="chatsounds/autoadd/minecraft/enderman scream/scream3.ogg",length=0.900},{path="chatsounds/autoadd/minecraft/enderman scream/scream4.ogg",length=0.900}}
L["enderman stare"]={{path="chatsounds/autoadd/minecraft/enderman stare.ogg",length=14.508}}
L["endsfx"]={{path="chatsounds/autoadd/minecraft/endsfx.ogg",length=18.000}}
L["fire"]={{path="chatsounds/autoadd/minecraft/fire.ogg",length=1.872}}
L["gallop"]={{path="chatsounds/autoadd/minecraft/gallop/gallop1.ogg",length=0.537},{path="chatsounds/autoadd/minecraft/gallop/gallop2.ogg",length=0.563},{path="chatsounds/autoadd/minecraft/gallop/gallop3.ogg",length=0.500},{path="chatsounds/autoadd/minecraft/gallop/gallop4.ogg",length=0.531}}
L["horse"]={{path="chatsounds/autoadd/minecraft/horse/idle1.ogg",length=0.861},{path="chatsounds/autoadd/minecraft/horse/idle2.ogg",length=0.669},{path="chatsounds/autoadd/minecraft/horse/idle3.ogg",length=1.040}}
L["horse angry"]={{path="chatsounds/autoadd/minecraft/horse angry.ogg",length=0.891}}
L["horse death"]={{path="chatsounds/autoadd/minecraft/horse death.ogg",length=1.560}}
L["horsehurt"]={{path="chatsounds/autoadd/minecraft/horsehurt/hit1.ogg",length=0.313},{path="chatsounds/autoadd/minecraft/horsehurt/hit2.ogg",length=0.313},{path="chatsounds/autoadd/minecraft/horsehurt/hit3.ogg",length=0.375},{path="chatsounds/autoadd/minecraft/horsehurt/hit4.ogg",length=0.438}}
L["hurt"]={{path="chatsounds/autoadd/minecraft/hurt.ogg",length=1.044}}
L["ignite"]={{path="chatsounds/autoadd/minecraft/ignite.ogg",length=0.360}}
L["mcwater"]={{path="chatsounds/autoadd/minecraft/mcwater.ogg",length=2.628}}
L["nether portal"]={{path="chatsounds/autoadd/minecraft/nether portal.ogg",length=5.040}}
L["nether travel"]={{path="chatsounds/autoadd/minecraft/nether travel.ogg",length=9.540}}
L["nether trigger"]={{path="chatsounds/autoadd/minecraft/nether trigger.ogg",length=4.068}}
L["noteblock"]={{path="chatsounds/autoadd/minecraft/noteblock/!banjo.ogg",length=0.464},{path="chatsounds/autoadd/minecraft/noteblock/!bdrum.ogg",length=0.125},{path="chatsounds/autoadd/minecraft/noteblock/!bell.ogg",length=0.435},{path="chatsounds/autoadd/minecraft/noteblock/!bit.ogg",length=0.380},{path="chatsounds/autoadd/minecraft/noteblock/!click.ogg",length=0.063},{path="chatsounds/autoadd/minecraft/noteblock/!cowbell.ogg",length=0.173},{path="chatsounds/autoadd/minecraft/noteblock/!dbass.ogg",length=0.468},{path="chatsounds/autoadd/minecraft/noteblock/!didgeridoo.ogg",length=0.428},{path="chatsounds/autoadd/minecraft/noteblock/!flute.ogg",length=0.603},{path="chatsounds/autoadd/minecraft/noteblock/!guitar.ogg",length=0.515},{path="chatsounds/autoadd/minecraft/noteblock/!harp.ogg",length=0.563},{path="chatsounds/autoadd/minecraft/noteblock/!icechime.ogg",length=1.083},{path="chatsounds/autoadd/minecraft/noteblock/!iron xylophone.ogg",length=0.584},{path="chatsounds/autoadd/minecraft/noteblock/!pling.ogg",length=0.625},{path="chatsounds/autoadd/minecraft/noteblock/!sdrum.ogg",length=0.063},{path="chatsounds/autoadd/minecraft/noteblock/!xylobone.ogg",length=0.123}}
L["pig"]={{path="chatsounds/autoadd/minecraft/pig/1.ogg",length=0.344},{path="chatsounds/autoadd/minecraft/pig/2.ogg",length=0.656},{path="chatsounds/autoadd/minecraft/pig/3.ogg",length=0.375}}
L["pigdeath"]={{path="chatsounds/autoadd/minecraft/pigdeath.ogg",length=0.527}}
L["rabbit"]={{path="chatsounds/autoadd/minecraft/rabbit/1.ogg",length=0.342},{path="chatsounds/autoadd/minecraft/rabbit/2.ogg",length=0.500},{path="chatsounds/autoadd/minecraft/rabbit/3.ogg",length=0.340},{path="chatsounds/autoadd/minecraft/rabbit/4.ogg",length=0.750}}
L["rabbitdeath"]={{path="chatsounds/autoadd/minecraft/rabbitdeath.ogg",length=0.418}}
L["rabbithurt"]={{path="chatsounds/autoadd/minecraft/rabbithurt/1.ogg",length=0.418},{path="chatsounds/autoadd/minecraft/rabbithurt/2.ogg",length=0.338},{path="chatsounds/autoadd/minecraft/rabbithurt/3.ogg",length=0.331},{path="chatsounds/autoadd/minecraft/rabbithurt/4.ogg",length=0.380}}
L["sheep"]={{path="chatsounds/autoadd/minecraft/sheep/1.ogg",length=1.000},{path="chatsounds/autoadd/minecraft/sheep/2.ogg",length=0.875},{path="chatsounds/autoadd/minecraft/sheep/3.ogg",length=1.000}}
L["skeleton"]={{path="chatsounds/autoadd/minecraft/skeleton/1.ogg",length=0.645},{path="chatsounds/autoadd/minecraft/skeleton/2.ogg",length=0.645},{path="chatsounds/autoadd/minecraft/skeleton/3.ogg",length=0.565}}
L["skeletondeath"]={{path="chatsounds/autoadd/minecraft/skeletondeath.ogg",length=0.590}}
L["skeletonhurt"]={{path="chatsounds/autoadd/minecraft/skeletonhurt/1.ogg",length=0.486},{path="chatsounds/autoadd/minecraft/skeletonhurt/2.ogg",length=0.484},{path="chatsounds/autoadd/minecraft/skeletonhurt/3.ogg",length=0.498},{path="chatsounds/autoadd/minecraft/skeletonhurt/4.ogg",length=0.540}}
L["spider"]={{path="chatsounds/autoadd/minecraft/spider/spider1.ogg",length=0.704},{path="chatsounds/autoadd/minecraft/spider/spider2.ogg",length=0.528},{path="chatsounds/autoadd/minecraft/spider/spider3.ogg",length=0.528},{path="chatsounds/autoadd/minecraft/spider/spider4.ogg",length=0.352}}
L["spiderdeath"]={{path="chatsounds/autoadd/minecraft/spiderdeath.ogg",length=1.375}}
L["sss"]={{path="chatsounds/autoadd/minecraft/sss.ogg",length=5.662}}
L["zombie"]={{path="chatsounds/autoadd/minecraft/zombie/1.ogg",length=1.500},{path="chatsounds/autoadd/minecraft/zombie/2.ogg",length=1.375},{path="chatsounds/autoadd/minecraft/zombie/3.ogg",length=2.125}}
L["zombiedeath"]={{path="chatsounds/autoadd/minecraft/zombiedeath.ogg",length=0.750}}
L["zombiehurt"]={{path="chatsounds/autoadd/minecraft/zombiehurt/1.ogg",length=0.938},{path="chatsounds/autoadd/minecraft/zombiehurt/2.ogg",length=1.000}}
c.EndList()