c.StartList("octosound")
L["aaaapun"]={{path="chatsounds/autoadd/octosound/aaaapun.ogg",length=2.204}}
L["ahohno"]={{path="chatsounds/autoadd/octosound/ahohno.ogg",length=2.066}}
L["aholewhatsthat"]={{path="chatsounds/autoadd/octosound/aholewhatsthat.ogg",length=3.340}}
L["better try the other one here"]={{path="chatsounds/autoadd/octosound/better try the other one here.ogg",length=2.617}}
L["bighead"]={{path="chatsounds/autoadd/octosound/bighead.ogg",length=6.611}}
L["breathing"]={{path="chatsounds/autoadd/octosound/breathing.ogg",length=2.720}}
L["comebackparents"]={{path="chatsounds/autoadd/octosound/comebackparents.ogg",length=3.925}}
L["crying"]={{path="chatsounds/autoadd/octosound/crying.ogg",length=2.582}}
L["findingmyparents"]={{path="chatsounds/autoadd/octosound/findingmyparents.ogg",length=3.891}}
L["gettingbiggerohno"]={{path="chatsounds/autoadd/octosound/gettingbiggerohno.ogg",length=2.272}}
L["gosh"]={{path="chatsounds/autoadd/octosound/gosh.ogg",length=3.650}}
L["growling"]={{path="chatsounds/autoadd/octosound/growling.ogg",length=2.100}}
L["havealookatthatplaceagain"]={{path="chatsounds/autoadd/octosound/havealookatthatplaceagain.ogg",length=4.338}}
L["hmmnicecupoftea"]={{path="chatsounds/autoadd/octosound/hmmnicecupoftea.ogg",length=2.135}}
L["hmmwhatsdownhere"]={{path="chatsounds/autoadd/octosound/hmmwhatsdownhere.ogg",length=2.617}}
L["hmmwhatsinthatboxbetteropen"]={{path="chatsounds/autoadd/octosound/hmmwhatsinthatboxbetteropen.ogg",length=2.066}}
L["idohaveparents"]={{path="chatsounds/autoadd/octosound/idohaveparents.ogg",length=12.429}}
L["iloveyou"]={{path="chatsounds/autoadd/octosound/iloveyou.ogg",length=6.197}}
L["imgonnagetyou"]={{path="chatsounds/autoadd/octosound/imgonnagetyou.ogg",length=1.928}}
L["ireallymissmyparents"]={{path="chatsounds/autoadd/octosound/ireallymissmyparents.ogg",length=3.718}}
L["iwillfindmyparents"]={{path="chatsounds/autoadd/octosound/iwillfindmyparents.ogg",length=4.545}}
L["kindaweirdalittlebitdifferent"]={{path="chatsounds/autoadd/octosound/kindaweirdalittlebitdifferent.ogg",length=8.263}}
L["lookslikesomechicken"]={{path="chatsounds/autoadd/octosound/lookslikesomechicken.ogg",length=5.853}}
L["loudscream"]={{path="chatsounds/autoadd/octosound/loudscream.ogg",length=0.964}}
L["maybeifitouchit"]={{path="chatsounds/autoadd/octosound/maybeifitouchit.ogg",length=3.064}}
L["maybeimrelaxing"]={{path="chatsounds/autoadd/octosound/maybeimrelaxing.ogg",length=2.135}}
L["notagoodoneletmetrythisone"]={{path="chatsounds/autoadd/octosound/notagoodoneletmetrythisone.ogg",length=2.204}}
L["octocatsaveus"]={{path="chatsounds/autoadd/octosound/octocatsaveus.ogg",length=8.160}}
L["octocatyoudonthaveanyparents"]={{path="chatsounds/autoadd/octosound/octocatyoudonthaveanyparents.ogg",length=3.512}}
L["octosplode"]={{path="chatsounds/autoadd/octosound/octosplode.ogg",length=10.226}}
L["ohitsafenceijust"]={{path="chatsounds/autoadd/octosound/ohitsafenceijust.ogg",length=1.446}}
L["omgmomdad"]={{path="chatsounds/autoadd/octosound/omgmomdad.ogg",length=1.653}}
L["pleasedont"]={{path="chatsounds/autoadd/octosound/pleasedont.ogg",length=2.135}}
L["runreallyfast"]={{path="chatsounds/autoadd/octosound/runreallyfast.ogg",length=4.682}}
L["sadmusic"]={{path="chatsounds/autoadd/octosound/sadmusic.ogg",length=52.437}}
L["screaming"]={{path="chatsounds/autoadd/octosound/screaming.ogg",length=7.575}}
L["somedoors"]={{path="chatsounds/autoadd/octosound/somedoors.ogg",length=1.825}}
L["sonicscream"]={{path="chatsounds/autoadd/octosound/sonicscream.ogg",length=8.332}}
L["takebreath"]={{path="chatsounds/autoadd/octosound/takebreath.ogg",length=0.998}}
L["uhhcupoftea"]={{path="chatsounds/autoadd/octosound/uhhcupoftea.ogg",length=1.584}}
L["walkoverit"]={{path="chatsounds/autoadd/octosound/walkoverit.ogg",length=1.308}}
L["whatshappening"]={{path="chatsounds/autoadd/octosound/whatshappening.ogg",length=1.377}}
L["whatshouldido"]={{path="chatsounds/autoadd/octosound/whatshouldido.ogg",length=5.750}}
L["whatsinhere"]={{path="chatsounds/autoadd/octosound/whatsinhere.ogg",length=3.168}}
L["whatsinthisdooribetteropenitandsee"]={{path="chatsounds/autoadd/octosound/whatsinthisdooribetteropenitandsee.ogg",length=2.892}}
L["woahaahwhatsoverthere"]={{path="chatsounds/autoadd/octosound/woahaahwhatsoverthere.ogg",length=2.169}}
c.EndList()