c.StartList("onion_sony")
L["a labyrinth themed maze of indecipherable topics of use to fucking no one"]={{path="chatsounds/autoadd/onion_sony/a labyrinth themed maze of indecipherable topics of use to fucking no one.ogg",length=3.750}}
L["a whole bunch more memory and megapixels and what not than any of the other tv shit that i already have"]={{path="chatsounds/autoadd/onion_sony/a whole bunch more memory and megapixels and what not than any of the other tv shit that i already have.ogg",length=6.352}}
L["and being goddamned ass backward as fuck"]={{path="chatsounds/autoadd/onion_sony/and being goddamned ass backward as fuck.ogg",length=2.125}}
L["and then we pumped out this impossible to use fucking piece of shit"]={{path="chatsounds/autoadd/onion_sony/and then we pumped out this impossible to use fucking piece of shit.ogg",length=3.977}}
L["anyone mystified by the devices numerous extraneous features can scroll through the interactive help menu"]={{path="chatsounds/autoadd/onion_sony/anyone mystified by the devices numerous extraneous features can scroll through the interactive help menu.ogg",length=5.147}}
L["can figure out this motherfucking time vampire"]={{path="chatsounds/autoadd/onion_sony/can figure out this motherfucking time vampire.ogg",length=2.545}}
L["doesnt do the goddamn thing its fucking supposed to"]={{path="chatsounds/autoadd/onion_sony/doesnt do the goddamn thing its fucking supposed to.ogg",length=2.477}}
L["flashing random fucking words and numbers on its display screen"]={{path="chatsounds/autoadd/onion_sony/flashing random fucking words and numbers on its display screen.ogg",length=3.136}}
L["for the onion news network im jeff tate"]={{path="chatsounds/autoadd/onion_sony/for the onion news network im jeff tate.ogg",length=2.545}}
L["i cant wait to get home and spend my whole fucking night trying to figure the goddamn thing out"]={{path="chatsounds/autoadd/onion_sony/i cant wait to get home and spend my whole fucking night trying to figure the goddamn thing out.ogg",length=3.841}}
L["i love bullshit like this basically ill buy any goddamn thing that i see in an ad"]={{path="chatsounds/autoadd/onion_sony/i love bullshit like this basically ill buy any goddamn thing that i see in an ad.ogg",length=5.772}}
L["if you can somehow claw and bite your way through the impossible to open packaging"]={{path="chatsounds/autoadd/onion_sony/if you can somehow claw and bite your way through the impossible to open packaging.ogg",length=3.795}}
L["if you dont want to feel like a toothless hillbilly living in some hillbilly shack somewhere"]={{path="chatsounds/autoadd/onion_sony/if you dont want to feel like a toothless hillbilly living in some hillbilly shack somewhere.ogg",length=3.875}}
L["it never ends this shit"]={{path="chatsounds/autoadd/onion_sony/it never ends this shit.ogg",length=1.716}}
L["its being called the biggest fucking waste of your hard earned money to come along in years"]={{path="chatsounds/autoadd/onion_sony/its being called the biggest fucking waste of your hard earned money to come along in years.ogg",length=4.216}}
L["just when you figured out the goddamn remote control for this one"]={{path="chatsounds/autoadd/onion_sony/just when you figured out the goddamn remote control for this one.ogg",length=3.409}}
L["not coming with the fucking little do hickey thing its supposed to"]={{path="chatsounds/autoadd/onion_sony/not coming with the fucking little do hickey thing its supposed to.ogg",length=2.761}}
L["of use to fucking no one"]={{path="chatsounds/autoadd/onion_sony/of use to fucking no one.ogg",length=1.341}}
L["onion news network tech trends reporter jeff tate has more"]={{path="chatsounds/autoadd/onion_sony/onion news network tech trends reporter jeff tate has more.ogg",length=4.091}}
L["so run out and pick one up and invite all of your friends over to see if any of therm"]={{path="chatsounds/autoadd/onion_sony/so run out and pick one up and invite all of your friends over to see if any of therm.ogg",length=3.818}}
L["sony is expecting it to become the next fucking gizmo you absolutely have to fucking own"]={{path="chatsounds/autoadd/onion_sony/sony is expecting it to become the next fucking gizmo you absolutely have to fucking own.ogg",length=5.056}}
L["sony says they plan to release an upgraded 800 gb version of this piece of shit by the end of the year"]={{path="chatsounds/autoadd/onion_sony/sony says they plan to release an upgraded 800 gb version of this piece of shit by the end of the year.ogg",length=5.886}}
L["sonys brand new stupid piece of shit that doesnt do the goddamn thing its fucking supposed to"]={{path="chatsounds/autoadd/onion_sony/sonys brand new stupid piece of shit that doesnt do the goddamn thing its fucking supposed to.ogg",length=5.068}}
L["sonys new stupid box thing hit the shelves at crowded malls and overpriced electronic stores"]={{path="chatsounds/autoadd/onion_sony/sonys new stupid box thing hit the shelves at crowded malls and overpriced electronic stores.ogg",length=6.499}}
L["stupid box thing"]={{path="chatsounds/autoadd/onion_sony/stupid box thing.ogg",length=1.125}}
L["sucking fucking goddamn thing"]={{path="chatsounds/autoadd/onion_sony/sucking fucking goddamn thing.ogg",length=1.542}}
L["sucking fucking goddamn thing to make everyone in the modern home want to tear their fucking eyeballs out"]={{path="chatsounds/autoadd/onion_sony/sucking fucking goddamn thing to make everyone in the modern home want to tear their fucking eyeballs out.ogg",length=8.408}}
L["tech savvy consumers are lining up today to be the first to purchase"]={{path="chatsounds/autoadd/onion_sony/tech savvy consumers are lining up today to be the first to purchase.ogg",length=3.807}}
L["thanks brandon"]={{path="chatsounds/autoadd/onion_sony/thanks brandon.ogg",length=1.091}}
L["the fucking piece of shit is available now"]={{path="chatsounds/autoadd/onion_sony/the fucking piece of shit is available now.ogg",length=1.954}}
L["this stupid piece of shit offers a wide variety of fustrating as hell functions including"]={{path="chatsounds/autoadd/onion_sony/this stupid piece of shit offers a wide variety of fustrating as hell functions including.ogg",length=4.238}}
L["unless one of them is a rocket scientist sony pretty much guaran fucking tees theyll have no chance"]={{path="chatsounds/autoadd/onion_sony/unless one of them is a rocket scientist sony pretty much guaran fucking tees theyll have no chance.ogg",length=4.886}}
L["we listened hard to what our customers said they wanted the most out of their own home entertainment system"]={{path="chatsounds/autoadd/onion_sony/we listened hard to what our customers said they wanted the most out of their own home entertainment system.ogg",length=5.250}}
L["we want people to be screaming in unison from houses across the country"]={{path="chatsounds/autoadd/onion_sony/we want people to be screaming in unison from houses across the country.ogg",length=4.147}}
L["with a 100 million dollar nationwide campaign to plaster irritating ass advertisements"]={{path="chatsounds/autoadd/onion_sony/with a 100 million dollar nationwide campaign to plaster irritating ass advertisements.ogg",length=7.920}}
L["work work you cock sucking piece of shit what is wrong with you why cant you work like a normal machine"]={{path="chatsounds/autoadd/onion_sony/work work you cock sucking piece of shit what is wrong with you why cant you work like a normal machine.ogg",length=5.647}}
L["work you cocksucking piece of shit"]={{path="chatsounds/autoadd/onion_sony/work you cocksucking piece of shit.ogg",length=1.986}}
c.EndList()