c.StartList("Onion Sony")
L["a labyrinth themed maze of indecipherable topics of use to fucking no one"]={{path="chatsounds/autoadd/Onion Sony/a labyrinth themed maze of indecipherable topics of use to fucking no one.ogg",length=3.749705215419501},}
L["a whole bunch more memory and megapixels and what not than any of the other tv shit that i already have"]={{path="chatsounds/autoadd/Onion Sony/a whole bunch more memory and megapixels and what not than any of the other tv shit that i already have.ogg",length=6.3517687074829929},}
L["and being goddamned ass backward as fuck"]={{path="chatsounds/autoadd/Onion Sony/and being goddamned ass backward as fuck.ogg",length=2.1248299319727892},}
L["and then we pumped out this impossible to use fucking piece of shit"]={{path="chatsounds/autoadd/Onion Sony/and then we pumped out this impossible to use fucking piece of shit.ogg",length=3.9769614512471656},}
L["anyone mystified by the devices numerous extraneous features can scroll through the interactive help menu"]={{path="chatsounds/autoadd/Onion Sony/anyone mystified by the devices numerous extraneous features can scroll through the interactive help menu.ogg",length=5.1473015873015875},}
L["can figure out this motherfucking time vampire"]={{path="chatsounds/autoadd/Onion Sony/can figure out this motherfucking time vampire.ogg",length=2.5452607709750565},}
L["doesnt do the goddamn thing its fucking supposed to"]={{path="chatsounds/autoadd/Onion Sony/doesnt do the goddamn thing its fucking supposed to.ogg",length=2.4770521541950115},}
L["flashing random fucking words and numbers on its display screen"]={{path="chatsounds/autoadd/Onion Sony/flashing random fucking words and numbers on its display screen.ogg",length=3.1360997732426306},}
L["for the onion news network im jeff tate"]={{path="chatsounds/autoadd/Onion Sony/for the onion news network im jeff tate.ogg",length=2.5452380952380951},}
L["i cant wait to get home and spend my whole fucking night trying to figure the goddamn thing out"]={{path="chatsounds/autoadd/Onion Sony/i cant wait to get home and spend my whole fucking night trying to figure the goddamn thing out.ogg",length=3.8405895691609979},}
L["i love bullshit like this basically ill buy any goddamn thing that i see in an ad"]={{path="chatsounds/autoadd/Onion Sony/i love bullshit like this basically ill buy any goddamn thing that i see in an ad.ogg",length=5.7722675736961451},}
L["if you can somehow claw and bite your way through the impossible to open packaging"]={{path="chatsounds/autoadd/Onion Sony/if you can somehow claw and bite your way through the impossible to open packaging.ogg",length=3.7951473922902492},}
L["if you dont want to feel like a toothless hillbilly living in some hillbilly shack somewhere"]={{path="chatsounds/autoadd/Onion Sony/if you dont want to feel like a toothless hillbilly living in some hillbilly shack somewhere.ogg",length=3.874671201814059},}
L["it never ends this shit"]={{path="chatsounds/autoadd/Onion Sony/it never ends this shit.ogg",length=1.7157596371882087},}
L["its being called the biggest fucking waste of your hard earned money to come along in years"]={{path="chatsounds/autoadd/Onion Sony/its being called the biggest fucking waste of your hard earned money to come along in years.ogg",length=4.2155555555555555},}
L["just when you figured out the goddamn remote control for this one"]={{path="chatsounds/autoadd/Onion Sony/just when you figured out the goddamn remote control for this one.ogg",length=3.4088208616780045},}
L["not coming with the fucking little do hickey thing its supposed to"]={{path="chatsounds/autoadd/Onion Sony/not coming with the fucking little do hickey thing its supposed to.ogg",length=2.7611337868480725},}
L["of use to fucking no one"]={{path="chatsounds/autoadd/Onion Sony/of use to fucking no one.ogg",length=1.3408163265306123},}
L["onion news network tech trends reporter jeff tate has more"]={{path="chatsounds/autoadd/Onion Sony/onion news network tech trends reporter jeff tate has more.ogg",length=4.0905895691609979},}
L["so run out and pick one up and invite all of your friends over to see if any of therm"]={{path="chatsounds/autoadd/Onion Sony/so run out and pick one up and invite all of your friends over to see if any of therm.ogg",length=3.8178684807256236},}
L["sony is expecting it to become the next fucking gizmo you absolutely have to fucking own"]={{path="chatsounds/autoadd/Onion Sony/sony is expecting it to become the next fucking gizmo you absolutely have to fucking own.ogg",length=5.056417233560091},}
L["sony says they plan to release an upgraded 800 gb version of this piece of shit by the end of the year"]={{path="chatsounds/autoadd/Onion Sony/sony says they plan to release an upgraded 800 gb version of this piece of shit by the end of the year.ogg",length=5.8858956916099769},}
L["sonys brand new stupid piece of shit that doesnt do the goddamn thing its fucking supposed to"]={{path="chatsounds/autoadd/Onion Sony/sonys brand new stupid piece of shit that doesnt do the goddamn thing its fucking supposed to.ogg",length=5.0677777777777777},}
L["sonys new stupid box thing hit the shelves at crowded malls and overpriced electronic stores"]={{path="chatsounds/autoadd/Onion Sony/sonys new stupid box thing hit the shelves at crowded malls and overpriced electronic stores.ogg",length=6.4994784580498868},}
L["stupid box thing"]={{path="chatsounds/autoadd/Onion Sony/stupid box thing.ogg",length=1.1249206349206349},}
L["sucking fucking goddamn thing to make everyone in the modern home want to tear their fucking eyeballs out"]={{path="chatsounds/autoadd/Onion Sony/sucking fucking goddamn thing to make everyone in the modern home want to tear their fucking eyeballs out.ogg",length=8.4084126984126986},}
L["sucking fucking goddamn thing"]={{path="chatsounds/autoadd/Onion Sony/sucking fucking goddamn thing.ogg",length=1.5424943310657597},}
L["tech savvy consumers are lining up today to be the first to purchase"]={{path="chatsounds/autoadd/Onion Sony/tech savvy consumers are lining up today to be the first to purchase.ogg",length=3.8065079365079364},}
L["thanks brandon"]={{path="chatsounds/autoadd/Onion Sony/thanks brandon.ogg",length=1.0908163265306123},}
L["the fucking piece of shit is available now"]={{path="chatsounds/autoadd/Onion Sony/the fucking piece of shit is available now.ogg",length=1.95437641723356},}
L["this stupid piece of shit offers a wide variety of fustrating as hell functions including"]={{path="chatsounds/autoadd/Onion Sony/this stupid piece of shit offers a wide variety of fustrating as hell functions including.ogg",length=4.2382993197278909},}
L["unless one of them is a rocket scientist sony pretty much guaran fucking tees theyll have no chance"]={{path="chatsounds/autoadd/Onion Sony/unless one of them is a rocket scientist sony pretty much guaran fucking tees theyll have no chance.ogg",length=4.8859637188208618},}
L["we listened hard to what our customers said they wanted the most out of their own home entertainment system"]={{path="chatsounds/autoadd/Onion Sony/we listened hard to what our customers said they wanted the most out of their own home entertainment system.ogg",length=5.2495691609977326},}
L["we want people to be screaming in unison from houses across the country"]={{path="chatsounds/autoadd/Onion Sony/we want people to be screaming in unison from houses across the country.ogg",length=4.1473922902494333},}
L["with a 100 million dollar nationwide campaign to plaster irritating ass advertisements"]={{path="chatsounds/autoadd/Onion Sony/with a 100 million dollar nationwide campaign to plaster irritating ass advertisements.ogg",length=7.9198185941043082},}
L["work work you cock sucking piece of shit what is wrong with you why cant you work like a normal machine"]={{path="chatsounds/autoadd/Onion Sony/work work you cock sucking piece of shit what is wrong with you why cant you work like a normal machine.ogg",length=5.6472562358276646},}
L["work you cocksucking piece of shit"]={{path="chatsounds/autoadd/Onion Sony/work you cocksucking piece of shit.ogg",length=1.9856235827664399},}
c.EndList()