c.StartList("player_names")
L["capsadmin"]={{path="chatsounds/autoadd/player_names/capsadmin.ogg",length=0.836}}
L["carlos"]={{path="chatsounds/autoadd/player_names/carlos.ogg",length=1.148}}
L["flex"]={{path="chatsounds/autoadd/player_names/flex.ogg",length=0.900}}
L["lixquid"]={{path="chatsounds/autoadd/player_names/lixquid.ogg",length=1.698}}
L["mitterdoo"]={{path="chatsounds/autoadd/player_names/mitterdoo/1.ogg",length=0.480},{path="chatsounds/autoadd/player_names/mitterdoo/2.ogg",length=0.557}}
L["python"]={{path="chatsounds/autoadd/player_names/python.ogg",length=0.601}}
L["verbal"]={{path="chatsounds/autoadd/player_names/verbal.ogg",length=0.808}}
c.EndList()