c.StartList("quake3_announce")
L["anarki"]={{path="chatsounds/autoadd/quake3_announce/anarki.ogg",length=0.919}}
L["angel"]={{path="chatsounds/autoadd/quake3_announce/angel.ogg",length=0.626}}
L["biker"]={{path="chatsounds/autoadd/quake3_announce/biker.ogg",length=0.676}}
L["bitterman"]={{path="chatsounds/autoadd/quake3_announce/bitterman.ogg",length=0.780}}
L["bones"]={{path="chatsounds/autoadd/quake3_announce/bones.ogg",length=0.778}}
L["cadavre"]={{path="chatsounds/autoadd/quake3_announce/cadavre.ogg",length=0.725}}
L["crash"]={{path="chatsounds/autoadd/quake3_announce/crash.ogg",length=0.751}}
L["daemia"]={{path="chatsounds/autoadd/quake3_announce/daemia.ogg",length=0.638}}
L["doom"]={{path="chatsounds/autoadd/quake3_announce/doom.ogg",length=0.762}}
L["gorre"]={{path="chatsounds/autoadd/quake3_announce/gorre.ogg",length=0.634}}
L["grunt"]={{path="chatsounds/autoadd/quake3_announce/grunt.ogg",length=0.692}}
L["hossman"]={{path="chatsounds/autoadd/quake3_announce/hossman.ogg",length=0.842}}
L["hunter"]={{path="chatsounds/autoadd/quake3_announce/hunter.ogg",length=0.629}}
L["keel"]={{path="chatsounds/autoadd/quake3_announce/keel.ogg",length=0.665}}
L["klesk"]={{path="chatsounds/autoadd/quake3_announce/klesk.ogg",length=0.651}}
L["lucy"]={{path="chatsounds/autoadd/quake3_announce/lucy.ogg",length=0.727}}
L["major"]={{path="chatsounds/autoadd/quake3_announce/major.ogg",length=0.692}}
L["mynx"]={{path="chatsounds/autoadd/quake3_announce/mynx.ogg",length=0.723}}
L["orbb"]={{path="chatsounds/autoadd/quake3_announce/orbb.ogg",length=0.621}}
L["patriot"]={{path="chatsounds/autoadd/quake3_announce/patriot.ogg",length=0.825}}
L["phobos"]={{path="chatsounds/autoadd/quake3_announce/phobos.ogg",length=0.810}}
L["ranger"]={{path="chatsounds/autoadd/quake3_announce/ranger.ogg",length=0.791}}
L["razor"]={{path="chatsounds/autoadd/quake3_announce/razor.ogg",length=0.749}}
L["sarge"]={{path="chatsounds/autoadd/quake3_announce/sarge.ogg",length=0.868}}
L["slash"]={{path="chatsounds/autoadd/quake3_announce/slash.ogg",length=0.787}}
L["sorlag"]={{path="chatsounds/autoadd/quake3_announce/sorlag.ogg",length=0.955}}
L["stripe"]={{path="chatsounds/autoadd/quake3_announce/stripe.ogg",length=0.826}}
L["tank junior"]={{path="chatsounds/autoadd/quake3_announce/tank junior.ogg",length=1.116}}
L["uriel"]={{path="chatsounds/autoadd/quake3_announce/uriel.ogg",length=0.769}}
L["visor"]={{path="chatsounds/autoadd/quake3_announce/visor.ogg",length=0.811}}
L["wrack"]={{path="chatsounds/autoadd/quake3_announce/wrack.ogg",length=0.619}}
L["xaero"]={{path="chatsounds/autoadd/quake3_announce/xaero.ogg",length=0.931}}
L["you win"]={{path="chatsounds/autoadd/quake3_announce/you win.ogg",length=1.148}}
c.EndList()