c.StartList("risk_of_rain_2")
L["brasscontraptiondeath"]={{path="chatsounds/autoadd/risk_of_rain_2/brasscontraptiondeath.ogg",length=4.852}}
L["brasscontraptionspawn"]={{path="chatsounds/autoadd/risk_of_rain_2/brasscontraptionspawn.ogg",length=3.258}}
L["celestinespawn"]={{path="chatsounds/autoadd/risk_of_rain_2/celestinespawn.ogg",length=5.667}}
L["imptalk"]={{path="chatsounds/autoadd/risk_of_rain_2/imptalk/1.ogg",length=1.482},{path="chatsounds/autoadd/risk_of_rain_2/imptalk/2.ogg",length=1.618},{path="chatsounds/autoadd/risk_of_rain_2/imptalk/3.ogg",length=1.663},{path="chatsounds/autoadd/risk_of_rain_2/imptalk/4.ogg",length=1.856},{path="chatsounds/autoadd/risk_of_rain_2/imptalk/5.ogg",length=1.538},{path="chatsounds/autoadd/risk_of_rain_2/imptalk/6.ogg",length=1.717}}
L["malachitespawn"]={{path="chatsounds/autoadd/risk_of_rain_2/malachitespawn.ogg",length=5.368}}
L["mithrixstealitem"]={{path="chatsounds/autoadd/risk_of_rain_2/mithrixstealitem/1.ogg",length=1.865},{path="chatsounds/autoadd/risk_of_rain_2/mithrixstealitem/2.ogg",length=1.769},{path="chatsounds/autoadd/risk_of_rain_2/mithrixstealitem/3.ogg",length=1.830},{path="chatsounds/autoadd/risk_of_rain_2/mithrixstealitem/4.ogg",length=1.728},{path="chatsounds/autoadd/risk_of_rain_2/mithrixstealitem/5.ogg",length=1.676}}
L["mithrixtalk"]={{path="chatsounds/autoadd/risk_of_rain_2/mithrixtalk/1.ogg",length=2.869},{path="chatsounds/autoadd/risk_of_rain_2/mithrixtalk/2.ogg",length=3.008},{path="chatsounds/autoadd/risk_of_rain_2/mithrixtalk/3.ogg",length=3.008}}
L["newttalk"]={{path="chatsounds/autoadd/risk_of_rain_2/newttalk/1.ogg",length=1.561},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/10.ogg",length=2.754},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/11.ogg",length=2.951},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/2.ogg",length=1.695},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/3.ogg",length=1.728},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/4.ogg",length=1.893},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/5.ogg",length=1.531},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/6.ogg",length=2.253},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/7.ogg",length=2.952},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/8.ogg",length=2.350},{path="chatsounds/autoadd/risk_of_rain_2/newttalk/9.ogg",length=1.999}}
L["player death"]={{path="chatsounds/autoadd/risk_of_rain_2/player death.ogg",length=1.776}}
L["voidlingtalk"]={{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/01.ogg",length=4.842},{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/02.ogg",length=3.000},{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/03.ogg",length=3.200},{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/04.ogg",length=3.200},{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/05.ogg",length=2.861},{path="chatsounds/autoadd/risk_of_rain_2/voidlingtalk/06.ogg",length=3.000}}
L["voidreaverdeath"]={{path="chatsounds/autoadd/risk_of_rain_2/voidreaverdeath.ogg",length=8.280}}
c.EndList()