c.StartList("sailormoon")
L["mooncosmicpowermakeup"]={{path="chatsounds/autoadd/sailormoon/mooncosmicpowermakeup.ogg",length=31.442}}
L["mooncosmicpowermakeupfx"]={{path="chatsounds/autoadd/sailormoon/mooncosmicpowermakeupfx.ogg",length=30.310}}
L["mooncrisismakeup"]={{path="chatsounds/autoadd/sailormoon/mooncrisismakeup.ogg",length=31.200}}
L["mooncrisismakeupfx"]={{path="chatsounds/autoadd/sailormoon/mooncrisismakeupfx.ogg",length=29.850}}
L["mooncrystalpowermakeup"]={{path="chatsounds/autoadd/sailormoon/mooncrystalpowermakeup.ogg",length=36.466}}
L["mooncrystalpowermakeupfx"]={{path="chatsounds/autoadd/sailormoon/mooncrystalpowermakeupfx.ogg",length=42.739}}
L["mooneternalmakeup"]={{path="chatsounds/autoadd/sailormoon/mooneternalmakeup.ogg",length=37.204}}
L["mooneternalmakeupfx"]={{path="chatsounds/autoadd/sailormoon/mooneternalmakeupfx.ogg",length=35.450}}
L["moonprismpowermakeup"]={{path="chatsounds/autoadd/sailormoon/moonprismpowermakeup.ogg",length=37.650}}
L["moonprismpowermakeupfx"]={{path="chatsounds/autoadd/sailormoon/moonprismpowermakeupfx.ogg",length=40.700}}
c.EndList()