c.StartList("sailor_moon")
L["mooncosmicpowermakeup"]={{path="chatsounds/autoadd/sailor_moon/mooncosmicpowermakeup.ogg",length=31.442}}
L["mooncosmicpowermakeupfx"]={{path="chatsounds/autoadd/sailor_moon/mooncosmicpowermakeupfx.ogg",length=30.310}}
L["mooncrisismakeup"]={{path="chatsounds/autoadd/sailor_moon/mooncrisismakeup.ogg",length=31.200}}
L["mooncrisismakeupfx"]={{path="chatsounds/autoadd/sailor_moon/mooncrisismakeupfx.ogg",length=29.850}}
L["mooncrystalpowermakeup"]={{path="chatsounds/autoadd/sailor_moon/mooncrystalpowermakeup.ogg",length=36.466}}
L["mooncrystalpowermakeupfx"]={{path="chatsounds/autoadd/sailor_moon/mooncrystalpowermakeupfx.ogg",length=42.739}}
L["mooneternalmakeup"]={{path="chatsounds/autoadd/sailor_moon/mooneternalmakeup.ogg",length=37.204}}
L["mooneternalmakeupfx"]={{path="chatsounds/autoadd/sailor_moon/mooneternalmakeupfx.ogg",length=35.450}}
L["moonprismpowermakeup"]={{path="chatsounds/autoadd/sailor_moon/moonprismpowermakeup.ogg",length=37.650}}
L["moonprismpowermakeupfx"]={{path="chatsounds/autoadd/sailor_moon/moonprismpowermakeupfx.ogg",length=40.700}}
c.EndList()