c.StartList("screaming")
L["daisy screaming"]={{path="chatsounds/autoadd/screaming/daisy screaming/1.ogg",length=16.181},{path="chatsounds/autoadd/screaming/daisy screaming/2.ogg",length=18.049},{path="chatsounds/autoadd/screaming/daisy screaming/3.ogg",length=20.885},{path="chatsounds/autoadd/screaming/daisy screaming/4.ogg",length=11.710},{path="chatsounds/autoadd/screaming/daisy screaming/5.ogg",length=22.353}}
L["link screaming"]={{path="chatsounds/autoadd/screaming/link screaming/1.ogg",length=33.297},{path="chatsounds/autoadd/screaming/link screaming/2.ogg",length=75.512},{path="chatsounds/autoadd/screaming/link screaming/3.ogg",length=59.412}}
L["luigi screaming"]={{path="chatsounds/autoadd/screaming/luigi screaming/1.ogg",length=64.001},{path="chatsounds/autoadd/screaming/luigi screaming/2.ogg",length=26.983},{path="chatsounds/autoadd/screaming/luigi screaming/3.ogg",length=25.802},{path="chatsounds/autoadd/screaming/luigi screaming/4.ogg",length=24.359}}
L["maamaa"]={{path="chatsounds/autoadd/screaming/maamaa.ogg",length=4.138}}
L["mario screaming"]={{path="chatsounds/autoadd/screaming/mario screaming/1.ogg",length=19.695},{path="chatsounds/autoadd/screaming/mario screaming/2.ogg",length=45.247},{path="chatsounds/autoadd/screaming/mario screaming/3.ogg",length=28.520},{path="chatsounds/autoadd/screaming/mario screaming/4.ogg",length=50.620},{path="chatsounds/autoadd/screaming/mario screaming/5.ogg",length=23.030},{path="chatsounds/autoadd/screaming/mario screaming/6.ogg",length=8.497},{path="chatsounds/autoadd/screaming/mario screaming/7.ogg",length=34.875},{path="chatsounds/autoadd/screaming/mario screaming/8.ogg",length=54.913}}
L["next level gaaaaaaay"]={{path="chatsounds/autoadd/screaming/next level gaaaaaaay.ogg",length=4.462}}
L["scientist screaming"]={{path="chatsounds/autoadd/screaming/scientist screaming/1.ogg",length=55.626},{path="chatsounds/autoadd/screaming/scientist screaming/2.ogg",length=21.221}}
L["toad screaming"]={{path="chatsounds/autoadd/screaming/toad screaming/1.ogg",length=36.182},{path="chatsounds/autoadd/screaming/toad screaming/2.ogg",length=27.710},{path="chatsounds/autoadd/screaming/toad screaming/3.ogg",length=47.478},{path="chatsounds/autoadd/screaming/toad screaming/4.ogg",length=42.360}}
L["vinny screaming"]={{path="chatsounds/autoadd/screaming/vinny screaming/1.ogg",length=32.123},{path="chatsounds/autoadd/screaming/vinny screaming/2.ogg",length=19.902},{path="chatsounds/autoadd/screaming/vinny screaming/3.ogg",length=16.721}}
L["waluigi screaming"]={{path="chatsounds/autoadd/screaming/waluigi screaming/1.ogg",length=22.359},{path="chatsounds/autoadd/screaming/waluigi screaming/2.ogg",length=34.064},{path="chatsounds/autoadd/screaming/waluigi screaming/3.ogg",length=46.175}}
L["wario screaming"]={{path="chatsounds/autoadd/screaming/wario screaming/1.ogg",length=18.741},{path="chatsounds/autoadd/screaming/wario screaming/2.ogg",length=93.769},{path="chatsounds/autoadd/screaming/wario screaming/3.ogg",length=10.479},{path="chatsounds/autoadd/screaming/wario screaming/4.ogg",length=33.544},{path="chatsounds/autoadd/screaming/wario screaming/5.ogg",length=34.910}}
c.EndList()