c.StartList("sfx_misc")
L["air blower"]={{path="chatsounds/autoadd/sfx_misc/air blower/air blower 1.ogg",length=1.101},{path="chatsounds/autoadd/sfx_misc/air blower/air blower 2.ogg",length=1.068}}
L["angrycat"]={{path="chatsounds/autoadd/sfx_misc/angrycat/1.ogg",length=6.415},{path="chatsounds/autoadd/sfx_misc/angrycat/10.ogg",length=3.834},{path="chatsounds/autoadd/sfx_misc/angrycat/11.ogg",length=3.348},{path="chatsounds/autoadd/sfx_misc/angrycat/12.ogg",length=4.182},{path="chatsounds/autoadd/sfx_misc/angrycat/13.ogg",length=2.219},{path="chatsounds/autoadd/sfx_misc/angrycat/14.ogg",length=1.992},{path="chatsounds/autoadd/sfx_misc/angrycat/15.ogg",length=3.276},{path="chatsounds/autoadd/sfx_misc/angrycat/16.ogg",length=2.124},{path="chatsounds/autoadd/sfx_misc/angrycat/17.ogg",length=2.181},{path="chatsounds/autoadd/sfx_misc/angrycat/18.ogg",length=2.100},{path="chatsounds/autoadd/sfx_misc/angrycat/19.ogg",length=3.063},{path="chatsounds/autoadd/sfx_misc/angrycat/2.ogg",length=4.466},{path="chatsounds/autoadd/sfx_misc/angrycat/20.ogg",length=9.152},{path="chatsounds/autoadd/sfx_misc/angrycat/21.ogg",length=1.647},{path="chatsounds/autoadd/sfx_misc/angrycat/22.ogg",length=6.394},{path="chatsounds/autoadd/sfx_misc/angrycat/23.ogg",length=3.099},{path="chatsounds/autoadd/sfx_misc/angrycat/24.ogg",length=2.836},{path="chatsounds/autoadd/sfx_misc/angrycat/25.ogg",length=2.405},{path="chatsounds/autoadd/sfx_misc/angrycat/3.ogg",length=4.574},{path="chatsounds/autoadd/sfx_misc/angrycat/4.ogg",length=2.191},{path="chatsounds/autoadd/sfx_misc/angrycat/5.ogg",length=3.371},{path="chatsounds/autoadd/sfx_misc/angrycat/6.ogg",length=3.261},{path="chatsounds/autoadd/sfx_misc/angrycat/7.ogg",length=2.352},{path="chatsounds/autoadd/sfx_misc/angrycat/8.ogg",length=2.290},{path="chatsounds/autoadd/sfx_misc/angrycat/9.ogg",length=2.987}}
L["bottle pop"]={{path="chatsounds/autoadd/sfx_misc/bottle pop/bottle pop 1.ogg",length=0.834},{path="chatsounds/autoadd/sfx_misc/bottle pop/bottle pop 2.ogg",length=0.400},{path="chatsounds/autoadd/sfx_misc/bottle pop/bottle pop 3.ogg",length=0.354},{path="chatsounds/autoadd/sfx_misc/bottle pop/champagne bottle pop 1.ogg",length=3.000}}
L["clank"]={{path="chatsounds/autoadd/sfx_misc/clank.ogg",length=0.509}}
L["coconut"]={{path="chatsounds/autoadd/sfx_misc/coconut.ogg",length=0.739}}
L["cricket"]={{path="chatsounds/autoadd/sfx_misc/cricket.ogg",length=3.472}}
L["crumbling plastic bag"]={{path="chatsounds/autoadd/sfx_misc/crumbling plastic bag.ogg",length=3.270}}
L["cutting paper"]={{path="chatsounds/autoadd/sfx_misc/cutting paper/cutting paper 1.ogg",length=8.217},{path="chatsounds/autoadd/sfx_misc/cutting paper/cutting paper 2.ogg",length=1.477}}
L["dj scratch"]={{path="chatsounds/autoadd/sfx_misc/dj scratch.ogg",length=2.435}}
L["dog barking"]={{path="chatsounds/autoadd/sfx_misc/dog barking/dog barking 1.ogg",length=2.002},{path="chatsounds/autoadd/sfx_misc/dog barking/dog barking 2.ogg",length=1.902},{path="chatsounds/autoadd/sfx_misc/dog barking/dogs barking 1.ogg",length=13.310},{path="chatsounds/autoadd/sfx_misc/dog barking/dogs barking 2.ogg",length=9.679}}
L["gta wasted"]={{path="chatsounds/autoadd/sfx_misc/gta wasted.ogg",length=7.530}}
L["hair mousse"]={{path="chatsounds/autoadd/sfx_misc/hair mousse.ogg",length=2.402}}
L["intruder alert"]={{path="chatsounds/autoadd/sfx_misc/intruder alert.ogg",length=2.400}}
L["knocking"]={{path="chatsounds/autoadd/sfx_misc/knocking/knocking 1.ogg",length=1.173},{path="chatsounds/autoadd/sfx_misc/knocking/knocking 2.ogg",length=1.707},{path="chatsounds/autoadd/sfx_misc/knocking/knocking 3.ogg",length=0.810},{path="chatsounds/autoadd/sfx_misc/knocking/knocking 4.ogg",length=1.108},{path="chatsounds/autoadd/sfx_misc/knocking/knocking 5.ogg",length=2.269},{path="chatsounds/autoadd/sfx_misc/knocking/knocking 6.ogg",length=1.335}}
L["knocking window"]={{path="chatsounds/autoadd/sfx_misc/knocking window.ogg",length=3.697}}
L["page turn"]={{path="chatsounds/autoadd/sfx_misc/page turn/page turn 1.ogg",length=1.268},{path="chatsounds/autoadd/sfx_misc/page turn/page turn 2.ogg",length=1.335},{path="chatsounds/autoadd/sfx_misc/page turn/page turn 3.ogg",length=1.101},{path="chatsounds/autoadd/sfx_misc/page turn/page turn 4.ogg",length=0.895},{path="chatsounds/autoadd/sfx_misc/page turn/page turn 5.ogg",length=1.322}}
L["paper crumbling"]={{path="chatsounds/autoadd/sfx_misc/paper crumbling/paper crumbling 1.ogg",length=5.630},{path="chatsounds/autoadd/sfx_misc/paper crumbling/paper crumbling 2.ogg",length=3.251},{path="chatsounds/autoadd/sfx_misc/paper crumbling/paper crumbling 3.ogg",length=2.669}}
L["paper tearing"]={{path="chatsounds/autoadd/sfx_misc/paper tearing/paper tearing 1.ogg",length=1.768},{path="chatsounds/autoadd/sfx_misc/paper tearing/paper tearing 2.ogg",length=0.868}}
L["record scratch"]={{path="chatsounds/autoadd/sfx_misc/record scratch/record scratch 1.ogg",length=0.933},{path="chatsounds/autoadd/sfx_misc/record scratch/record scratch 2.ogg",length=1.215}}
L["shuffle cards"]={{path="chatsounds/autoadd/sfx_misc/shuffle cards/shuffle cards 1.ogg",length=1.193},{path="chatsounds/autoadd/sfx_misc/shuffle cards/shuffle cards 2.ogg",length=1.108}}
L["spraying"]={{path="chatsounds/autoadd/sfx_misc/spraying/spraying 1.ogg",length=3.437},{path="chatsounds/autoadd/sfx_misc/spraying/spraying 2.ogg",length=1.235}}
L["squeeze toy"]={{path="chatsounds/autoadd/sfx_misc/squeeze toy/squeeze toy 1.ogg",length=0.895},{path="chatsounds/autoadd/sfx_misc/squeeze toy/squeeze toy 2.ogg",length=0.456}}
L["striking a match"]={{path="chatsounds/autoadd/sfx_misc/striking a match.ogg",length=1.002}}
L["two pop"]={{path="chatsounds/autoadd/sfx_misc/two pop.ogg",length=0.100}}
L["water splash"]={{path="chatsounds/autoadd/sfx_misc/water splash/velcro strap 1.ogg",length=0.682},{path="chatsounds/autoadd/sfx_misc/water splash/water splash 1.ogg",length=1.372},{path="chatsounds/autoadd/sfx_misc/water splash/water splash 2.ogg",length=2.130}}
L["wind chime"]={{path="chatsounds/autoadd/sfx_misc/wind chime/wind chime 1.ogg",length=14.747},{path="chatsounds/autoadd/sfx_misc/wind chime/wind chime 2.ogg",length=8.164}}
L["writing"]={{path="chatsounds/autoadd/sfx_misc/writing/writing 1.ogg",length=9.105},{path="chatsounds/autoadd/sfx_misc/writing/writing 2.ogg",length=6.649}}
c.EndList()