c.StartList("soyokaze")
L["10do"]={{path="chatsounds/autoadd/soyokaze/10do.ogg",length=1.738}}
L["2007"]={{path="chatsounds/autoadd/soyokaze/2007.ogg",length=0.850}}
L["25do"]={{path="chatsounds/autoadd/soyokaze/25do.ogg",length=1.529}}
L["aaa"]={{path="chatsounds/autoadd/soyokaze/aaa.ogg",length=1.033}}
L["ahan"]={{path="chatsounds/autoadd/soyokaze/ahan.ogg",length=0.790}}
L["akemasite"]={{path="chatsounds/autoadd/soyokaze/akemasite.ogg",length=1.503}}
L["akemasite2"]={{path="chatsounds/autoadd/soyokaze/akemasite2.ogg",length=2.052}}
L["akira"]={{path="chatsounds/autoadd/soyokaze/akira.ogg",length=1.164}}
L["akira2"]={{path="chatsounds/autoadd/soyokaze/akira2.ogg",length=1.242}}
L["akirame"]={{path="chatsounds/autoadd/soyokaze/akirame.ogg",length=0.902}}
L["akirame2"]={{path="chatsounds/autoadd/soyokaze/akirame2.ogg",length=1.608}}
L["an"]={{path="chatsounds/autoadd/soyokaze/an.ogg",length=0.249}}
L["arigatou"]={{path="chatsounds/autoadd/soyokaze/arigatou.ogg",length=0.719}}
L["asera"]={{path="chatsounds/autoadd/soyokaze/asera.ogg",length=1.425}}
L["ato"]={{path="chatsounds/autoadd/soyokaze/ato.ogg",length=1.686}}
L["atui"]={{path="chatsounds/autoadd/soyokaze/atui.ogg",length=1.581}}
L["atuku"]={{path="chatsounds/autoadd/soyokaze/atuku.ogg",length=1.268}}
L["bokuno"]={{path="chatsounds/autoadd/soyokaze/bokuno.ogg",length=1.137}}
L["bokuno2"]={{path="chatsounds/autoadd/soyokaze/bokuno2.ogg",length=2.208}}
L["ccc"]={{path="chatsounds/autoadd/soyokaze/ccc.ogg",length=1.268}}
L["daijoubu"]={{path="chatsounds/autoadd/soyokaze/daijoubu.ogg",length=0.693}}
L["dakara"]={{path="chatsounds/autoadd/soyokaze/dakara.ogg",length=0.589}}
L["damedame"]={{path="chatsounds/autoadd/soyokaze/damedame.ogg",length=1.712}}
L["dekiruyo"]={{path="chatsounds/autoadd/soyokaze/dekiruyo.ogg",length=0.876}}
L["donnaie"]={{path="chatsounds/autoadd/soyokaze/donnaie.ogg",length=1.007}}
L["dont worry"]={{path="chatsounds/autoadd/soyokaze/dont worry.ogg",length=0.719}}
L["dounika"]={{path="chatsounds/autoadd/soyokaze/dounika.ogg",length=1.190}}
L["dousite"]={{path="chatsounds/autoadd/soyokaze/dousite.ogg",length=1.790}}
L["douzo"]={{path="chatsounds/autoadd/soyokaze/douzo.ogg",length=0.380}}
L["fukitu"]={{path="chatsounds/autoadd/soyokaze/fukitu.ogg",length=3.358}}
L["fuu"]={{path="chatsounds/autoadd/soyokaze/fuu.ogg",length=3.671}}
L["fuzisan"]={{path="chatsounds/autoadd/soyokaze/fuzisan.ogg",length=1.529}}
L["fuzisan2"]={{path="chatsounds/autoadd/soyokaze/fuzisan2.ogg",length=1.320}}
L["fuzisanda"]={{path="chatsounds/autoadd/soyokaze/fuzisanda.ogg",length=0.955}}
L["gake1"]={{path="chatsounds/autoadd/soyokaze/gake1.ogg",length=1.634}}
L["gake2"]={{path="chatsounds/autoadd/soyokaze/gake2.ogg",length=1.190}}
L["gake3"]={{path="chatsounds/autoadd/soyokaze/gake3.ogg",length=0.928}}
L["ganba"]={{path="chatsounds/autoadd/soyokaze/ganba.ogg",length=1.399}}
L["ganbare"]={{path="chatsounds/autoadd/soyokaze/ganbare.ogg",length=3.227}}
L["genbawo"]={{path="chatsounds/autoadd/soyokaze/genbawo.ogg",length=2.287}}
L["gorenraku"]={{path="chatsounds/autoadd/soyokaze/gorenraku.ogg",length=1.503}}
L["happy"]={{path="chatsounds/autoadd/soyokaze/happy.ogg",length=1.268}}
L["haretemo"]={{path="chatsounds/autoadd/soyokaze/haretemo.ogg",length=0.902}}
L["hi1"]={{path="chatsounds/autoadd/soyokaze/hi1.ogg",length=1.529}}
L["hito"]={{path="chatsounds/autoadd/soyokaze/hito.ogg",length=1.973}}
L["hitotu"]={{path="chatsounds/autoadd/soyokaze/hitotu.ogg",length=1.999}}
L["honki"]={{path="chatsounds/autoadd/soyokaze/honki.ogg",length=0.850}}
L["honki2"]={{path="chatsounds/autoadd/soyokaze/honki2.ogg",length=1.790}}
L["honkini1"]={{path="chatsounds/autoadd/soyokaze/honkini1.ogg",length=1.294}}
L["honkini2"]={{path="chatsounds/autoadd/soyokaze/honkini2.ogg",length=1.190}}
L["ieieie"]={{path="chatsounds/autoadd/soyokaze/ieieie.ogg",length=2.417}}
L["ieyo"]={{path="chatsounds/autoadd/soyokaze/ieyo.ogg",length=0.641}}
L["ii"]={{path="chatsounds/autoadd/soyokaze/ii.ogg",length=0.537}}
L["ikasi"]={{path="chatsounds/autoadd/soyokaze/ikasi.ogg",length=1.372}}
L["ikuzo"]={{path="chatsounds/autoadd/soyokaze/ikuzo.ogg",length=0.615}}
L["issyou"]={{path="chatsounds/autoadd/soyokaze/issyou.ogg",length=0.746}}
L["issyou2"]={{path="chatsounds/autoadd/soyokaze/issyou2.ogg",length=1.843}}
L["itiban"]={{path="chatsounds/autoadd/soyokaze/itiban.ogg",length=1.660}}
L["ittai"]={{path="chatsounds/autoadd/soyokaze/ittai.ogg",length=1.947}}
L["janai"]={{path="chatsounds/autoadd/soyokaze/janai.ogg",length=4.089}}
L["kaisei"]={{path="chatsounds/autoadd/soyokaze/kaisei.ogg",length=2.130}}
L["kakugo"]={{path="chatsounds/autoadd/soyokaze/kakugo.ogg",length=1.111}}
L["kanarazu"]={{path="chatsounds/autoadd/soyokaze/kanarazu.ogg",length=1.425}}
L["kawareru"]={{path="chatsounds/autoadd/soyokaze/kawareru.ogg",length=0.615}}
L["kimino"]={{path="chatsounds/autoadd/soyokaze/kimino.ogg",length=0.981}}
L["kimino2"]={{path="chatsounds/autoadd/soyokaze/kimino2.ogg",length=1.059}}
L["kini"]={{path="chatsounds/autoadd/soyokaze/kini.ogg",length=1.059}}
L["kirei"]={{path="chatsounds/autoadd/soyokaze/kirei.ogg",length=1.503}}
L["kirei2"]={{path="chatsounds/autoadd/soyokaze/kirei2.ogg",length=0.798}}
L["kokorode"]={{path="chatsounds/autoadd/soyokaze/kokorode.ogg",length=1.581}}
L["kokoronone"]={{path="chatsounds/autoadd/soyokaze/kokoronone.ogg",length=0.955}}
L["konokawa"]={{path="chatsounds/autoadd/soyokaze/konokawa.ogg",length=1.111}}
L["konokawa2"]={{path="chatsounds/autoadd/soyokaze/konokawa2.ogg",length=1.085}}
L["konotiwo"]={{path="chatsounds/autoadd/soyokaze/konotiwo.ogg",length=2.444}}
L["kore"]={{path="chatsounds/autoadd/soyokaze/kore.ogg",length=0.615}}
L["koremite"]={{path="chatsounds/autoadd/soyokaze/koremite.ogg",length=1.007}}
L["kotosimo"]={{path="chatsounds/autoadd/soyokaze/kotosimo.ogg",length=1.425}}
L["kumori"]={{path="chatsounds/autoadd/soyokaze/kumori.ogg",length=2.052}}
L["kuyokuyo"]={{path="chatsounds/autoadd/soyokaze/kuyokuyo.ogg",length=1.503}}
L["kyoukara"]={{path="chatsounds/autoadd/soyokaze/kyoukara.ogg",length=1.216}}
L["matte"]={{path="chatsounds/autoadd/soyokaze/matte.ogg",length=0.772}}
L["matuoka"]={{path="chatsounds/autoadd/soyokaze/matuoka.ogg",length=0.693}}
L["mietekita"]={{path="chatsounds/autoadd/soyokaze/mietekita.ogg",length=1.660}}
L["minasan"]={{path="chatsounds/autoadd/soyokaze/minasan.ogg",length=1.164}}
L["mite"]={{path="chatsounds/autoadd/soyokaze/mite.ogg",length=0.928}}
L["miteyo"]={{path="chatsounds/autoadd/soyokaze/miteyo.ogg",length=0.667}}
L["mousukosi"]={{path="chatsounds/autoadd/soyokaze/mousukosi.ogg",length=1.581}}
L["mukasi"]={{path="chatsounds/autoadd/soyokaze/mukasi.ogg",length=1.817}}
L["muri"]={{path="chatsounds/autoadd/soyokaze/muri.ogg",length=1.843}}
L["nae"]={{path="chatsounds/autoadd/soyokaze/nae.ogg",length=0.876}}
L["nae2"]={{path="chatsounds/autoadd/soyokaze/nae2.ogg",length=1.738}}
L["nandayo"]={{path="chatsounds/autoadd/soyokaze/nandayo.ogg",length=1.085}}
L["nandayo2"]={{path="chatsounds/autoadd/soyokaze/nandayo2.ogg",length=0.641}}
L["nande"]={{path="chatsounds/autoadd/soyokaze/nande.ogg",length=2.208}}
L["nanika"]={{path="chatsounds/autoadd/soyokaze/nanika.ogg",length=1.895}}
L["nanimo"]={{path="chatsounds/autoadd/soyokaze/nanimo.ogg",length=1.895}}
L["nanno"]={{path="chatsounds/autoadd/soyokaze/nanno.ogg",length=2.261}}
L["nanteumi"]={{path="chatsounds/autoadd/soyokaze/nanteumi.ogg",length=1.660}}
L["naraba"]={{path="chatsounds/autoadd/soyokaze/naraba.ogg",length=0.615}}
L["nekko"]={{path="chatsounds/autoadd/soyokaze/nekko.ogg",length=2.496}}
L["nekko2"]={{path="chatsounds/autoadd/soyokaze/nekko2.ogg",length=1.738}}
L["nekko3"]={{path="chatsounds/autoadd/soyokaze/nekko3.ogg",length=1.294}}
L["nene"]={{path="chatsounds/autoadd/soyokaze/nene.ogg",length=0.380}}
L["nippon"]={{path="chatsounds/autoadd/soyokaze/nippon.ogg",length=1.790}}
L["nipponiti"]={{path="chatsounds/autoadd/soyokaze/nipponiti.ogg",length=1.033}}
L["nomi"]={{path="chatsounds/autoadd/soyokaze/nomi.ogg",length=1.085}}
L["okome"]={{path="chatsounds/autoadd/soyokaze/okome.ogg",length=1.059}}
L["omouyo"]={{path="chatsounds/autoadd/soyokaze/omouyo.ogg",length=1.164}}
L["ooame"]={{path="chatsounds/autoadd/soyokaze/ooame.ogg",length=1.790}}
L["oreno"]={{path="chatsounds/autoadd/soyokaze/oreno.ogg",length=0.955}}
L["ouen"]={{path="chatsounds/autoadd/soyokaze/ouen.ogg",length=2.104}}
L["outbreak"]={{path="chatsounds/autoadd/soyokaze/outbreak.ogg",length=0.365}}
L["owakari"]={{path="chatsounds/autoadd/soyokaze/owakari.ogg",length=1.686}}
L["owakari2"]={{path="chatsounds/autoadd/soyokaze/owakari2.ogg",length=1.895}}
L["owakari3"]={{path="chatsounds/autoadd/soyokaze/owakari3.ogg",length=2.104}}
L["pekin"]={{path="chatsounds/autoadd/soyokaze/pekin.ogg",length=1.555}}
L["pyua"]={{path="chatsounds/autoadd/soyokaze/pyua.ogg",length=1.216}}
L["saa"]={{path="chatsounds/autoadd/soyokaze/saa.ogg",length=0.928}}
L["sagasite"]={{path="chatsounds/autoadd/soyokaze/sagasite.ogg",length=1.503}}
L["sibaraku"]={{path="chatsounds/autoadd/soyokaze/sibaraku.ogg",length=2.208}}
L["sikkarisita"]={{path="chatsounds/autoadd/soyokaze/sikkarisita.ogg",length=2.026}}
L["sinsou"]={{path="chatsounds/autoadd/soyokaze/sinsou.ogg",length=3.802}}
L["sitto"]={{path="chatsounds/autoadd/soyokaze/sitto.ogg",length=0.563}}
L["sizenga"]={{path="chatsounds/autoadd/soyokaze/sizenga.ogg",length=1.007}}
L["sizimi"]={{path="chatsounds/autoadd/soyokaze/sizimi.ogg",length=1.790}}
L["sokoda"]={{path="chatsounds/autoadd/soyokaze/sokoda.ogg",length=1.320}}
L["sonnano"]={{path="chatsounds/autoadd/soyokaze/sonnano.ogg",length=1.529}}
L["sonotame"]={{path="chatsounds/autoadd/soyokaze/sonotame.ogg",length=0.928}}
L["soredeha"]={{path="chatsounds/autoadd/soyokaze/soredeha.ogg",length=5.004}}
L["soredeha2"]={{path="chatsounds/autoadd/soyokaze/soredeha2.ogg",length=2.156}}
L["sou"]={{path="chatsounds/autoadd/soyokaze/sou.ogg",length=0.328}}
L["sou2"]={{path="chatsounds/autoadd/soyokaze/sou2.ogg",length=0.746}}
L["soudayo"]={{path="chatsounds/autoadd/soyokaze/soudayo.ogg",length=1.790}}
L["subetega"]={{path="chatsounds/autoadd/soyokaze/subetega.ogg",length=1.660}}
L["sugu"]={{path="chatsounds/autoadd/soyokaze/sugu.ogg",length=1.242}}
L["suzusiku"]={{path="chatsounds/autoadd/soyokaze/suzusiku.ogg",length=1.843}}
L["suzusiku2"]={{path="chatsounds/autoadd/soyokaze/suzusiku2.ogg",length=0.746}}
L["suzusiku3"]={{path="chatsounds/autoadd/soyokaze/suzusiku3.ogg",length=0.902}}
L["syuu"]={{path="chatsounds/autoadd/soyokaze/syuu.ogg",length=1.712}}
L["taihuu"]={{path="chatsounds/autoadd/soyokaze/taihuu.ogg",length=1.190}}
L["ti n"]={{path="chatsounds/autoadd/soyokaze/ti n.ogg",length=3.697}}
L["tikara"]={{path="chatsounds/autoadd/soyokaze/tikara.ogg",length=1.790}}
L["to"]={{path="chatsounds/autoadd/soyokaze/to.ogg",length=0.249}}
L["todemo"]={{path="chatsounds/autoadd/soyokaze/todemo.ogg",length=1.817}}
L["trr"]={{path="chatsounds/autoadd/soyokaze/trr.ogg",length=0.301}}
L["tuyoi"]={{path="chatsounds/autoadd/soyokaze/tuyoi.ogg",length=1.503}}
L["tyansu"]={{path="chatsounds/autoadd/soyokaze/tyansu.ogg",length=1.608}}
L["tyanto"]={{path="chatsounds/autoadd/soyokaze/tyanto.ogg",length=0.928}}
L["umimi"]={{path="chatsounds/autoadd/soyokaze/umimi.ogg",length=1.190}}
L["unun"]={{path="chatsounds/autoadd/soyokaze/unun.ogg",length=0.432}}
L["wakaru"]={{path="chatsounds/autoadd/soyokaze/wakaru.ogg",length=0.667}}
L["wakatta"]={{path="chatsounds/autoadd/soyokaze/wakatta.ogg",length=1.294}}
L["wakatta2"]={{path="chatsounds/autoadd/soyokaze/wakatta2.ogg",length=0.850}}
L["waruguti"]={{path="chatsounds/autoadd/soyokaze/waruguti.ogg",length=0.641}}
L["yareru"]={{path="chatsounds/autoadd/soyokaze/yareru.ogg",length=1.294}}
L["yoku"]={{path="chatsounds/autoadd/soyokaze/yoku.ogg",length=0.589}}
L["yorosiku"]={{path="chatsounds/autoadd/soyokaze/yorosiku.ogg",length=1.399}}
L["zettai"]={{path="chatsounds/autoadd/soyokaze/zettai.ogg",length=1.712}}
L["zettaini"]={{path="chatsounds/autoadd/soyokaze/zettaini.ogg",length=2.757}}
L["zibunga"]={{path="chatsounds/autoadd/soyokaze/zibunga.ogg",length=1.320}}
L["zibunno"]={{path="chatsounds/autoadd/soyokaze/zibunno.ogg",length=1.660}}
L["zibunno2"]={{path="chatsounds/autoadd/soyokaze/zibunno2.ogg",length=1.712}}
L["zo"]={{path="chatsounds/autoadd/soyokaze/zo.ogg",length=1.764}}
L["zutto"]={{path="chatsounds/autoadd/soyokaze/zutto.ogg",length=0.876}}
c.EndList()