c.StartList("spongebob")
L["could we interest you in some chocolate"]={{path="chatsounds/autoadd/spongebob/could we interest you in some chocolate.ogg",length=3.029}}
L["deuueaugh"]={{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh.ogg",length=1.968},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh10.ogg",length=1.493},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh11.ogg",length=1.354},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh12.ogg",length=1.196},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh13.ogg",length=0.769},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh14.ogg",length=1.647},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh15.ogg",length=1.204},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh2.ogg",length=1.765},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh3.ogg",length=1.623},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh4.ogg",length=1.497},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh5.ogg",length=1.346},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh6.ogg",length=1.472},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh7.ogg",length=1.358},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh8.ogg",length=2.412},{path="chatsounds/autoadd/spongebob/deuueaugh/deuueaugh9.ogg",length=1.399}}
L["deuuueaughhhhhhh"]={{path="chatsounds/autoadd/spongebob/deuuueaughhhhhhh.ogg",length=3.641}}
L["did you say chocolate"]={{path="chatsounds/autoadd/spongebob/did you say chocolate.ogg",length=2.731}}
L["dude put that thing away there are like children here"]={{path="chatsounds/autoadd/spongebob/dude put that thing away there are like children here.ogg",length=3.617}}
L["hahahahahahahahohohohohohohohihihihihihihihahaha"]={{path="chatsounds/autoadd/spongebob/hahahahahahahahohohohohohohohihihihihihihihahaha.ogg",length=8.045}}
L["is this the krusty krab"]={{path="chatsounds/autoadd/spongebob/is this the krusty krab/1.ogg",length=1.357},{path="chatsounds/autoadd/spongebob/is this the krusty krab/2.ogg",length=1.184},{path="chatsounds/autoadd/spongebob/is this the krusty krab/3.ogg",length=1.332}}
L["ive been trying to catch you boys all day"]={{path="chatsounds/autoadd/spongebob/ive been trying to catch you boys all day.ogg",length=3.898}}
L["leedle leedle leedle lee"]={{path="chatsounds/autoadd/spongebob/leedle leedle leedle lee.ogg",length=1.750}}
L["life is but a walking shadow"]={{path="chatsounds/autoadd/spongebob/life is but a walking shadow.ogg",length=3.516}}
L["no this is patrick"]={{path="chatsounds/autoadd/spongebob/no this is patrick/1.ogg",length=1.460},{path="chatsounds/autoadd/spongebob/no this is patrick/2.ogg",length=2.615},{path="chatsounds/autoadd/spongebob/no this is patrick/3.ogg",length=3.059}}
L["now that ive got you right where i want you id like to buy all your chocolate"]={{path="chatsounds/autoadd/spongebob/now that ive got you right where i want you id like to buy all your chocolate.ogg",length=5.461}}
L["sb chocolate"]={{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate1.ogg",length=1.638},{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate2.ogg",length=1.390},{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate3.ogg",length=1.452},{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate4.ogg",length=2.284},{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate5.ogg",length=2.358},{path="chatsounds/autoadd/spongebob/sb chocolate/chocolate6.ogg",length=2.433}}
L["sb finally"]={{path="chatsounds/autoadd/spongebob/sb finally.ogg",length=1.092}}
L["sb laugh"]={{path="chatsounds/autoadd/spongebob/sb laugh.ogg",length=2.160}}
L["sb squidward"]={{path="chatsounds/autoadd/spongebob/sb squidward.ogg",length=1.312}}
L["sb squidward distorted"]={{path="chatsounds/autoadd/spongebob/sb squidward distorted/sb squidward distorted 1.ogg",length=1.321},{path="chatsounds/autoadd/spongebob/sb squidward distorted/sb squidward distorted 2.ogg",length=1.150}}
L["six and a half"]={{path="chatsounds/autoadd/spongebob/six and a half.ogg",length=1.529}}
L["squiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiidward"]={{path="chatsounds/autoadd/spongebob/squiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiidward.ogg",length=5.100}}
L["thank you for your patronage"]={{path="chatsounds/autoadd/spongebob/thank you for your patronage.ogg",length=1.862}}
c.EndList()