c.StartList("steam")
L["activation"]={{path="chatsounds/autoadd/steam/activation.ogg",length=0.834}}
L["activationchangefail"]={{path="chatsounds/autoadd/steam/activationchangefail.ogg",length=0.639}}
L["addfavorite"]={{path="chatsounds/autoadd/steam/addfavorite.ogg",length=0.578}}
L["focuschange"]={{path="chatsounds/autoadd/steam/focuschange.ogg",length=1.040}}
L["focuschangefail"]={{path="chatsounds/autoadd/steam/focuschangefail.ogg",length=0.420}}
L["focuschangefastscroll"]={{path="chatsounds/autoadd/steam/focuschangefastscroll.ogg",length=0.740}}
L["friendjoin"]={{path="chatsounds/autoadd/steam/friendjoin.ogg",length=2.763}}
L["friendonline"]={{path="chatsounds/autoadd/steam/friendonline.ogg",length=1.514}}
L["pagescrollleft"]={{path="chatsounds/autoadd/steam/pagescrollleft.ogg",length=0.896}}
L["pagescrollright"]={{path="chatsounds/autoadd/steam/pagescrollright.ogg",length=1.077}}
L["steammessage"]={{path="chatsounds/autoadd/steam/steammessage.ogg",length=0.721}}
L["txtingcursorend"]={{path="chatsounds/autoadd/steam/txtingcursorend.ogg",length=0.169}}
L["txtingcursorhome"]={{path="chatsounds/autoadd/steam/txtingcursorhome.ogg",length=0.147}}
L["txtingcursorleft"]={{path="chatsounds/autoadd/steam/txtingcursorleft.ogg",length=0.371}}
L["txtingcursorright"]={{path="chatsounds/autoadd/steam/txtingcursorright.ogg",length=0.332}}
L["txtingfocus"]={{path="chatsounds/autoadd/steam/txtingfocus.ogg",length=0.213}}
L["txtinggroupdefocus"]={{path="chatsounds/autoadd/steam/txtinggroupdefocus.ogg",length=0.383}}
L["txtinggroupfocus"]={{path="chatsounds/autoadd/steam/txtinggroupfocus.ogg",length=0.213}}
L["txtingpressa"]={{path="chatsounds/autoadd/steam/txtingpressa.ogg",length=0.490}}
L["txtingpressb"]={{path="chatsounds/autoadd/steam/txtingpressb.ogg",length=0.877}}
L["txtingpressx"]={{path="chatsounds/autoadd/steam/txtingpressx.ogg",length=0.849}}
L["txtingpressy"]={{path="chatsounds/autoadd/steam/txtingpressy.ogg",length=0.681}}
L["txtingtypebackspace"]={{path="chatsounds/autoadd/steam/txtingtypebackspace.ogg",length=0.226}}
L["txtingtypecaps"]={{path="chatsounds/autoadd/steam/txtingtypecaps.ogg",length=0.654}}
L["txtingtypeextra"]={{path="chatsounds/autoadd/steam/txtingtypeextra.ogg",length=0.864}}
L["txtingtypefail"]={{path="chatsounds/autoadd/steam/txtingtypefail.ogg",length=0.420}}
L["txtingtypemain"]={{path="chatsounds/autoadd/steam/txtingtypemain.ogg",length=0.583}}
L["txtingtypenumbers"]={{path="chatsounds/autoadd/steam/txtingtypenumbers.ogg",length=0.400}}
L["txtingtypespacebar"]={{path="chatsounds/autoadd/steam/txtingtypespacebar.ogg",length=0.329}}
L["voicehangup"]={{path="chatsounds/autoadd/steam/voicehangup.ogg",length=0.952}}
L["volumechange"]={{path="chatsounds/autoadd/steam/volumechange.ogg",length=0.388}}
L["zoomin"]={{path="chatsounds/autoadd/steam/zoomin.ogg",length=1.052}}
c.EndList()