c.StartList("steam_monster_game")
L["clickattack"]={{path="chatsounds/autoadd/steam_monster_game/clickattack/clickattack.ogg",length=0.200},{path="chatsounds/autoadd/steam_monster_game/clickattack/clickattack2.ogg",length=0.760}}
L["clusterbomb"]={{path="chatsounds/autoadd/steam_monster_game/clusterbomb.ogg",length=3.760}}
L["creep"]={{path="chatsounds/autoadd/steam_monster_game/creep/creep1.ogg",length=1.133},{path="chatsounds/autoadd/steam_monster_game/creep/creep2.ogg",length=1.507},{path="chatsounds/autoadd/steam_monster_game/creep/creep3.1.ogg",length=1.507},{path="chatsounds/autoadd/steam_monster_game/creep/creep3.ogg",length=1.133},{path="chatsounds/autoadd/steam_monster_game/creep/creep4.ogg",length=1.507},{path="chatsounds/autoadd/steam_monster_game/creep/creep5.ogg",length=0.760},{path="chatsounds/autoadd/steam_monster_game/creep/creep6.ogg",length=1.133},{path="chatsounds/autoadd/steam_monster_game/creep/creep7.ogg",length=0.760},{path="chatsounds/autoadd/steam_monster_game/creep/creep8.1.ogg",length=1.133},{path="chatsounds/autoadd/steam_monster_game/creep/creep8.ogg",length=1.133},{path="chatsounds/autoadd/steam_monster_game/creep/creep9.ogg",length=0.853}}
L["enemydied"]={{path="chatsounds/autoadd/steam_monster_game/enemydied.ogg",length=1.507}}
L["napalm"]={{path="chatsounds/autoadd/steam_monster_game/napalm.ogg",length=6.000}}
L["nuke"]={{path="chatsounds/autoadd/steam_monster_game/nuke.ogg",length=1.507}}
L["pickupgold"]={{path="chatsounds/autoadd/steam_monster_game/pickupgold.ogg",length=1.133}}
L["shipspawn"]={{path="chatsounds/autoadd/steam_monster_game/shipspawn.ogg",length=1.507}}
L["standardupgrade"]={{path="chatsounds/autoadd/steam_monster_game/standardupgrade.ogg",length=1.507}}
L["upgradeability"]={{path="chatsounds/autoadd/steam_monster_game/upgradeability.ogg",length=0.760}}
L["wrongselection"]={{path="chatsounds/autoadd/steam_monster_game/wrongselection.ogg",length=0.760}}
L["youdied"]={{path="chatsounds/autoadd/steam_monster_game/youdied.ogg",length=1.507}}
c.EndList()