c.StartList("steammonstergame")
L["clickattack"]={{path="chatsounds/autoadd/steammonstergame/clickattack/clickattack.ogg",length=0.200},{path="chatsounds/autoadd/steammonstergame/clickattack/clickattack2.ogg",length=0.760}}
L["clusterbomb"]={{path="chatsounds/autoadd/steammonstergame/clusterbomb.ogg",length=3.760}}
L["creep"]={{path="chatsounds/autoadd/steammonstergame/creep/creep1.ogg",length=1.133},{path="chatsounds/autoadd/steammonstergame/creep/creep2.ogg",length=1.507},{path="chatsounds/autoadd/steammonstergame/creep/creep3.1.ogg",length=1.507},{path="chatsounds/autoadd/steammonstergame/creep/creep3.ogg",length=1.133},{path="chatsounds/autoadd/steammonstergame/creep/creep4.ogg",length=1.507},{path="chatsounds/autoadd/steammonstergame/creep/creep5.ogg",length=0.760},{path="chatsounds/autoadd/steammonstergame/creep/creep6.ogg",length=1.133},{path="chatsounds/autoadd/steammonstergame/creep/creep7.ogg",length=0.760},{path="chatsounds/autoadd/steammonstergame/creep/creep8.1.ogg",length=1.133},{path="chatsounds/autoadd/steammonstergame/creep/creep8.ogg",length=1.133},{path="chatsounds/autoadd/steammonstergame/creep/creep9.ogg",length=0.853}}
L["enemydied"]={{path="chatsounds/autoadd/steammonstergame/enemydied.ogg",length=1.507}}
L["napalm"]={{path="chatsounds/autoadd/steammonstergame/napalm.ogg",length=6.000}}
L["nuke"]={{path="chatsounds/autoadd/steammonstergame/nuke.ogg",length=1.507}}
L["pickupgold"]={{path="chatsounds/autoadd/steammonstergame/pickupgold.ogg",length=1.133}}
L["shipspawn"]={{path="chatsounds/autoadd/steammonstergame/shipspawn.ogg",length=1.507}}
L["standardupgrade"]={{path="chatsounds/autoadd/steammonstergame/standardupgrade.ogg",length=1.507}}
L["upgradeability"]={{path="chatsounds/autoadd/steammonstergame/upgradeability.ogg",length=0.760}}
L["wrongselection"]={{path="chatsounds/autoadd/steammonstergame/wrongselection.ogg",length=0.760}}
L["youdied"]={{path="chatsounds/autoadd/steammonstergame/youdied.ogg",length=1.507}}
c.EndList()