c.StartList("tga")
L["aeiou"]={{path="chatsounds/autoadd/tga/aeiou.ogg",length=0.624}}
L["aeiou2"]={{path="chatsounds/autoadd/tga/aeiou2.ogg",length=0.528}}
L["aeiou3"]={{path="chatsounds/autoadd/tga/aeiou3.ogg",length=0.600}}
L["angrykid"]={{path="chatsounds/autoadd/tga/angrykid.ogg",length=10.940}}
L["ass2"]={{path="chatsounds/autoadd/tga/ass2.ogg",length=0.384}}
L["cactus"]={{path="chatsounds/autoadd/tga/cactus.ogg",length=0.601}}
L["chineseearthquake"]={{path="chatsounds/autoadd/tga/chineseearthquake.ogg",length=2.400}}
L["dadnoplease"]={{path="chatsounds/autoadd/tga/dadnoplease.ogg",length=1.248}}
L["ebay"]={{path="chatsounds/autoadd/tga/ebay.ogg",length=0.504}}
L["ebrbrbrbr"]={{path="chatsounds/autoadd/tga/ebrbrbrbr.ogg",length=1.464}}
L["football"]={{path="chatsounds/autoadd/tga/football.ogg",length=0.768}}
L["hallo"]={{path="chatsounds/autoadd/tga/hallo.ogg",length=0.781}}
L["homer says scream"]={{path="chatsounds/autoadd/tga/homer says scream.ogg",length=1.060}}
L["hoseshoseshoseshoseshoses"]={{path="chatsounds/autoadd/tga/hoseshoseshoseshoseshoses.ogg",length=2.928}}
L["johnmadden"]={{path="chatsounds/autoadd/tga/johnmadden.ogg",length=0.739}}
L["johnmadden2"]={{path="chatsounds/autoadd/tga/johnmadden2.ogg",length=0.960}}
L["meow"]={{path="chatsounds/autoadd/tga/meow.ogg",length=0.252}}
L["motdintro"]={{path="chatsounds/autoadd/tga/motdintro.ogg",length=27.077}}
L["snaaaaake"]={{path="chatsounds/autoadd/tga/snaaaaake.ogg",length=1.200}}
L["snaake"]={{path="chatsounds/autoadd/tga/snaake.ogg",length=0.512}}
L["snake"]={{path="chatsounds/autoadd/tga/snake.ogg",length=0.512}}
L["snayyyk"]={{path="chatsounds/autoadd/tga/snayyyk.ogg",length=2.040}}
L["spotted"]={{path="chatsounds/autoadd/tga/spotted.ogg",length=1.334}}
L["sssss"]={{path="chatsounds/autoadd/tga/sssss.ogg",length=2.831}}
L["stfu"]={{path="chatsounds/autoadd/tga/stfu.ogg",length=2.149}}
L["whyyes"]={{path="chatsounds/autoadd/tga/whyyes.ogg",length=0.776}}
L["woof"]={{path="chatsounds/autoadd/tga/woof.ogg",length=0.198}}
L["wubububu"]={{path="chatsounds/autoadd/tga/wubububu.ogg",length=1.081}}
L["yoshi"]={{path="chatsounds/autoadd/tga/yoshi.ogg",length=0.452}}
L["youlose2"]={{path="chatsounds/autoadd/tga/youlose2.ogg",length=4.987}}
c.EndList()