c.StartList("the_sims")
L["sims awkward"]={{path="chatsounds/autoadd/the_sims/sims awkward/sims awkward1.ogg",length=4.136},{path="chatsounds/autoadd/the_sims/sims awkward/sims awkward2.ogg",length=3.114}}
L["sims danger"]={{path="chatsounds/autoadd/the_sims/sims danger/sims danger1.ogg",length=5.706},{path="chatsounds/autoadd/the_sims/sims danger/sims danger2.ogg",length=5.938}}
L["sims death"]={{path="chatsounds/autoadd/the_sims/sims death/sims death1.ogg",length=6.111},{path="chatsounds/autoadd/the_sims/sims death/sims death2.ogg",length=6.891}}
L["sims empty fridge"]={{path="chatsounds/autoadd/the_sims/sims empty fridge/sims empty fridge1.ogg",length=3.801},{path="chatsounds/autoadd/the_sims/sims empty fridge/sims empty fridge2.ogg",length=2.902},{path="chatsounds/autoadd/the_sims/sims empty fridge/sims empty fridge3.ogg",length=4.081},{path="chatsounds/autoadd/the_sims/sims empty fridge/sims empty fridge4.ogg",length=3.013}}
L["sims fainted"]={{path="chatsounds/autoadd/the_sims/sims fainted/sims fainted1.ogg",length=11.063},{path="chatsounds/autoadd/the_sims/sims fainted/sims fainted2.ogg",length=8.301}}
L["sims fight begins"]={{path="chatsounds/autoadd/the_sims/sims fight begins.ogg",length=2.331}}
L["sims fire"]={{path="chatsounds/autoadd/the_sims/sims fire/sims fire1.ogg",length=7.272},{path="chatsounds/autoadd/the_sims/sims fire/sims fire2.ogg",length=6.876}}
L["sims kiss"]={{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss1.ogg",length=9.357},{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss2.ogg",length=8.857},{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss3.ogg",length=9.880},{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss4.ogg",length=9.524},{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss5.ogg",length=8.981},{path="chatsounds/autoadd/the_sims/sims kiss/sims kiss6.ogg",length=10.096}}
L["sims kiss failure"]={{path="chatsounds/autoadd/the_sims/sims kiss failure.ogg",length=4.952}}
L["sims marriage"]={{path="chatsounds/autoadd/the_sims/sims marriage/sims marriage1.ogg",length=8.616},{path="chatsounds/autoadd/the_sims/sims marriage/sims marriage2.ogg",length=5.082}}
L["sims pet dies"]={{path="chatsounds/autoadd/the_sims/sims pet dies.ogg",length=5.560}}
L["sims proposal"]={{path="chatsounds/autoadd/the_sims/sims proposal/sims proposal1.ogg",length=8.024},{path="chatsounds/autoadd/the_sims/sims proposal/sims proposal2.ogg",length=8.512},{path="chatsounds/autoadd/the_sims/sims proposal/sims proposal3.ogg",length=7.577}}
L["sims relationship failure"]={{path="chatsounds/autoadd/the_sims/sims relationship failure.ogg",length=4.322}}
L["sims skill point earned"]={{path="chatsounds/autoadd/the_sims/sims skill point earned/sims skill point earned1.ogg",length=8.430},{path="chatsounds/autoadd/the_sims/sims skill point earned/sims skill point earned2.ogg",length=8.091},{path="chatsounds/autoadd/the_sims/sims skill point earned/sims skill point earned3.ogg",length=8.661},{path="chatsounds/autoadd/the_sims/sims skill point earned/sims skill point earned4.ogg",length=8.512},{path="chatsounds/autoadd/the_sims/sims skill point earned/sims skill point earned5.ogg",length=7.686}}
L["sims spooky"]={{path="chatsounds/autoadd/the_sims/sims spooky/sims spooky1.ogg",length=6.714},{path="chatsounds/autoadd/the_sims/sims spooky/sims spooky2.ogg",length=7.112},{path="chatsounds/autoadd/the_sims/sims spooky/sims spooky3.ogg",length=6.813}}
L["sims success"]={{path="chatsounds/autoadd/the_sims/sims success/sims success1.ogg",length=6.117},{path="chatsounds/autoadd/the_sims/sims success/sims success2.ogg",length=6.264},{path="chatsounds/autoadd/the_sims/sims success/sims success3.ogg",length=6.796}}
L["sims toddler grows"]={{path="chatsounds/autoadd/the_sims/sims toddler grows.ogg",length=7.156}}
L["sims toilet failure"]={{path="chatsounds/autoadd/the_sims/sims toilet failure/sims toilet failure1.ogg",length=2.880},{path="chatsounds/autoadd/the_sims/sims toilet failure/sims toilet failure2.ogg",length=3.046}}
c.EndList()