c.StartList("vinesauce_speen")
L["and i like to speen"]={{path="chatsounds/autoadd/vinesauce_speen/and i like to speen.ogg",length=3.211}}
L["hey everybody haha"]={{path="chatsounds/autoadd/vinesauce_speen/hey everybody haha.ogg",length=2.440}}
L["my name is genome soldier"]={{path="chatsounds/autoadd/vinesauce_speen/my name is genome soldier.ogg",length=2.319}}
L["ok ill just spin"]={{path="chatsounds/autoadd/vinesauce_speen/ok ill just spin.ogg",length=2.069}}
L["speen"]={{path="chatsounds/autoadd/vinesauce_speen/speen/1.ogg",length=0.954},{path="chatsounds/autoadd/vinesauce_speen/speen/10.ogg",length=1.327},{path="chatsounds/autoadd/vinesauce_speen/speen/11.ogg",length=2.241},{path="chatsounds/autoadd/vinesauce_speen/speen/12.ogg",length=1.256},{path="chatsounds/autoadd/vinesauce_speen/speen/13.ogg",length=0.985},{path="chatsounds/autoadd/vinesauce_speen/speen/14.ogg",length=1.099},{path="chatsounds/autoadd/vinesauce_speen/speen/15.ogg",length=0.842},{path="chatsounds/autoadd/vinesauce_speen/speen/16.ogg",length=1.384},{path="chatsounds/autoadd/vinesauce_speen/speen/17.ogg",length=1.185},{path="chatsounds/autoadd/vinesauce_speen/speen/2.ogg",length=0.896},{path="chatsounds/autoadd/vinesauce_speen/speen/3.ogg",length=1.185},{path="chatsounds/autoadd/vinesauce_speen/speen/4.ogg",length=1.063},{path="chatsounds/autoadd/vinesauce_speen/speen/5.ogg",length=2.387},{path="chatsounds/autoadd/vinesauce_speen/speen/6.ogg",length=1.113},{path="chatsounds/autoadd/vinesauce_speen/speen/7.ogg",length=1.013},{path="chatsounds/autoadd/vinesauce_speen/speen/8.ogg",length=1.413},{path="chatsounds/autoadd/vinesauce_speen/speen/9.ogg",length=1.627}}
L["speen distorted"]={{path="chatsounds/autoadd/vinesauce_speen/speen distorted.ogg",length=3.539}}
L["today we going to spin to spin we going today"]={{path="chatsounds/autoadd/vinesauce_speen/today we going to spin to spin we going today.ogg",length=4.124}}
L["wow that thing spun like a motherfucker"]={{path="chatsounds/autoadd/vinesauce_speen/wow that thing spun like a motherfucker.ogg",length=3.083}}
L["yeah you walk away"]={{path="chatsounds/autoadd/vinesauce_speen/yeah you walk away.ogg",length=1.127}}
L["you know i could say something like speen"]={{path="chatsounds/autoadd/vinesauce_speen/you know i could say something like speen.ogg",length=2.084}}
L["you know what you did"]={{path="chatsounds/autoadd/vinesauce_speen/you know what you did.ogg",length=1.185}}
c.EndList()