c.StartList("warsow")
L["bobot"]={{path="chatsounds/autoadd/warsow/bobot/dash_1.ogg",length=0.161},{path="chatsounds/autoadd/warsow/bobot/dash_2.ogg",length=0.188},{path="chatsounds/autoadd/warsow/bobot/death.ogg",length=0.493},{path="chatsounds/autoadd/warsow/bobot/drown.ogg",length=1.463},{path="chatsounds/autoadd/warsow/bobot/falldeath.ogg",length=3.948},{path="chatsounds/autoadd/warsow/bobot/fall_0.ogg",length=0.356},{path="chatsounds/autoadd/warsow/bobot/fall_1.ogg",length=0.314},{path="chatsounds/autoadd/warsow/bobot/fall_2.ogg",length=0.426},{path="chatsounds/autoadd/warsow/bobot/gasp.ogg",length=1.405},{path="chatsounds/autoadd/warsow/bobot/jump_1.ogg",length=0.284},{path="chatsounds/autoadd/warsow/bobot/jump_2.ogg",length=0.311},{path="chatsounds/autoadd/warsow/bobot/pain100.ogg",length=0.238},{path="chatsounds/autoadd/warsow/bobot/pain25.ogg",length=0.714},{path="chatsounds/autoadd/warsow/bobot/pain50.ogg",length=0.380},{path="chatsounds/autoadd/warsow/bobot/pain75.ogg",length=0.355},{path="chatsounds/autoadd/warsow/bobot/wj_1.ogg",length=0.429},{path="chatsounds/autoadd/warsow/bobot/wj_2.ogg",length=0.344}}
L["electrobolt"]={{path="chatsounds/autoadd/warsow/electrobolt/electrobolt_strong.ogg",length=1.206},{path="chatsounds/autoadd/warsow/electrobolt/electrobolt_weak.ogg",length=1.105}}
L["instagun"]={{path="chatsounds/autoadd/warsow/instagun.ogg",length=1.417}}
L["machinegun fire"]={{path="chatsounds/autoadd/warsow/machinegun fire.ogg",length=0.500}}
L["padpork"]={{path="chatsounds/autoadd/warsow/padpork/dash_1.ogg",length=0.483},{path="chatsounds/autoadd/warsow/padpork/dash_2.ogg",length=0.285},{path="chatsounds/autoadd/warsow/padpork/death.ogg",length=0.842},{path="chatsounds/autoadd/warsow/padpork/drown.ogg",length=0.610},{path="chatsounds/autoadd/warsow/padpork/falldeath.ogg",length=3.713},{path="chatsounds/autoadd/warsow/padpork/fall_0.ogg",length=0.356},{path="chatsounds/autoadd/warsow/padpork/fall_1.ogg",length=0.703},{path="chatsounds/autoadd/warsow/padpork/fall_2.ogg",length=0.722},{path="chatsounds/autoadd/warsow/padpork/jump_1.ogg",length=0.452},{path="chatsounds/autoadd/warsow/padpork/jump_2.ogg",length=0.558},{path="chatsounds/autoadd/warsow/padpork/pain100.ogg",length=0.558},{path="chatsounds/autoadd/warsow/padpork/pain25.ogg",length=0.842},{path="chatsounds/autoadd/warsow/padpork/pain50.ogg",length=0.714},{path="chatsounds/autoadd/warsow/padpork/pain75.ogg",length=0.783},{path="chatsounds/autoadd/warsow/padpork/wj_1.ogg",length=0.500},{path="chatsounds/autoadd/warsow/padpork/wj_2.ogg",length=0.322}}
L["warsow menu"]={{path="chatsounds/autoadd/warsow/warsow menu/menu_1.ogg",length=32.010},{path="chatsounds/autoadd/warsow/warsow menu/menu_2.ogg",length=43.146}}
L["warsow postmatch"]={{path="chatsounds/autoadd/warsow/warsow postmatch/postmatch_1.ogg",length=20.767},{path="chatsounds/autoadd/warsow/warsow postmatch/postmatch_2.ogg",length=21.333},{path="chatsounds/autoadd/warsow/warsow postmatch/postmatch_3.ogg",length=27.429}}
L["weak to strong"]={{path="chatsounds/autoadd/warsow/weak to strong.ogg",length=0.331}}
c.EndList()