c.StartList("wayo")
L["bom bom bom"]={{path="chatsounds/autoadd/wayo/bom bom bom/bom bom bom 2.ogg",length=0.898},{path="chatsounds/autoadd/wayo/bom bom bom/bom bom bom 3.ogg",length=0.910},{path="chatsounds/autoadd/wayo/bom bom bom/bom bom bom.ogg",length=1.787}}
L["bom bom bom let me hear you say wayo"]={{path="chatsounds/autoadd/wayo/bom bom bom let me hear you say wayo/bom bom bom let me hear you say wayo 2.ogg",length=3.538},{path="chatsounds/autoadd/wayo/bom bom bom let me hear you say wayo/bom bom bom let me hear you say wayo 3.ogg",length=3.602},{path="chatsounds/autoadd/wayo/bom bom bom let me hear you say wayo/bom bom bom let me hear you say wayo.ogg",length=3.611}}
L["bom bom bom now every body say wayo"]={{path="chatsounds/autoadd/wayo/bom bom bom now every body say wayo/bom bom bom now every body say wayo 4.ogg",length=3.590},{path="chatsounds/autoadd/wayo/bom bom bom now every body say wayo/bom bom bom now every body say wayo 5.ogg",length=3.607},{path="chatsounds/autoadd/wayo/bom bom bom now every body say wayo/bom bom bom now every body say wayo 6.ogg",length=3.609},{path="chatsounds/autoadd/wayo/bom bom bom now every body say wayo/bom bom bom now every body say wayo 7.ogg",length=3.565},{path="chatsounds/autoadd/wayo/bom bom bom now every body say wayo/bom bom bom now every body say wayo.ogg",length=3.590}}
L["bom bom bom now let me hear you say wayo"]={{path="chatsounds/autoadd/wayo/bom bom bom now let me hear you say wayo/bom bom bom now let me hear you say wayo 2.ogg",length=3.587},{path="chatsounds/autoadd/wayo/bom bom bom now let me hear you say wayo/bom bom bom now let me hear you say wayo 3.ogg",length=3.573},{path="chatsounds/autoadd/wayo/bom bom bom now let me hear you say wayo/bom bom bom now let me hear you say wayo 4.ogg",length=3.597},{path="chatsounds/autoadd/wayo/bom bom bom now let me hear you say wayo/bom bom bom now let me hear you say wayo.ogg",length=2.747}}
L["i say bom bom bom now every body say wayo"]={{path="chatsounds/autoadd/wayo/i say bom bom bom now every body say wayo/i say bom bom bom now every body say wayo 5.ogg",length=2.451},{path="chatsounds/autoadd/wayo/i say bom bom bom now every body say wayo/i say bom bom bom now every body say wayo 6.ogg",length=2.414},{path="chatsounds/autoadd/wayo/i say bom bom bom now every body say wayo/i say bom bom bom now every body say wayo.ogg",length=2.451}}
L["i say bom bom bom now let me hear you say wayo"]={{path="chatsounds/autoadd/wayo/i say bom bom bom now let me hear you say wayo.ogg",length=2.719}}
L["let let let let let me hear you say wayo"]={{path="chatsounds/autoadd/wayo/let let let let let me hear you say wayo.ogg",length=3.598}}
L["wayo"]={{path="chatsounds/autoadd/wayo/wayo/3.ogg",length=0.904},{path="chatsounds/autoadd/wayo/wayo/4.ogg",length=0.585},{path="chatsounds/autoadd/wayo/wayo/wayo 1.ogg",length=0.670},{path="chatsounds/autoadd/wayo/wayo/wayo 2.ogg",length=1.053}}
c.EndList()