c.StartList("wurm")
L["applaud"]={{path="chatsounds/autoadd/wurm/applaud.ogg",length=2.684}}
L["call"]={{path="chatsounds/autoadd/wurm/call.ogg",length=0.442}}
L["chuckle"]={{path="chatsounds/autoadd/wurm/chuckle.ogg",length=0.758}}
L["cry"]={{path="chatsounds/autoadd/wurm/cry.ogg",length=3.438}}
L["curse"]={{path="chatsounds/autoadd/wurm/curse.ogg",length=1.245}}
L["disagree"]={{path="chatsounds/autoadd/wurm/disagree.ogg",length=1.261}}
L["fart"]={{path="chatsounds/autoadd/wurm/fart.ogg",length=2.322}}
L["insult"]={{path="chatsounds/autoadd/wurm/insult.ogg",length=1.586}}
L["kiss"]={{path="chatsounds/autoadd/wurm/kiss.ogg",length=0.356}}
L["laugh"]={{path="chatsounds/autoadd/wurm/laugh.ogg",length=5.022}}
L["slap"]={{path="chatsounds/autoadd/wurm/slap.ogg",length=0.211}}
L["spit"]={{path="chatsounds/autoadd/wurm/spit.ogg",length=1.849}}
L["tease"]={{path="chatsounds/autoadd/wurm/tease.ogg",length=1.681}}
L["wave"]={{path="chatsounds/autoadd/wurm/wave.ogg",length=1.905}}
c.EndList()