c.StartList("zelda_ww")
L["aaaahhhh"]={{path="chatsounds/autoadd/zelda_ww/aaaahhhh.ogg",length=3.088}}
L["angry"]={{path="chatsounds/autoadd/zelda_ww/angry.ogg",length=3.055}}
L["bawl"]={{path="chatsounds/autoadd/zelda_ww/bawl.ogg",length=4.662}}
L["bottle close"]={{path="chatsounds/autoadd/zelda_ww/bottle close.ogg",length=0.538}}
L["bottle open"]={{path="chatsounds/autoadd/zelda_ww/bottle open.ogg",length=0.130}}
L["bounce"]={{path="chatsounds/autoadd/zelda_ww/bounce.ogg",length=0.409}}
L["bye"]={{path="chatsounds/autoadd/zelda_ww/bye.ogg",length=0.866}}
L["come on"]={{path="chatsounds/autoadd/zelda_ww/come on.ogg",length=0.871}}
L["dizzy"]={{path="chatsounds/autoadd/zelda_ww/dizzy.ogg",length=1.343}}
L["gah"]={{path="chatsounds/autoadd/zelda_ww/gah.ogg",length=0.437}}
L["gasp"]={{path="chatsounds/autoadd/zelda_ww/gasp.ogg",length=0.610}}
L["giggle"]={{path="chatsounds/autoadd/zelda_ww/giggle.ogg",length=0.768}}
L["glaugh"]={{path="chatsounds/autoadd/zelda_ww/glaugh/ww_ganondorf_final_triforcelaugh1.ogg",length=3.146},{path="chatsounds/autoadd/zelda_ww/glaugh/ww_ganondorf_final_triforcelaugh2.ogg",length=3.290},{path="chatsounds/autoadd/zelda_ww/glaugh/ww_ganondorf_final_triforcelaugh3.ogg",length=10.929},{path="chatsounds/autoadd/zelda_ww/glaugh/ww_ganondorf_fortress_laugh.ogg",length=1.306},{path="chatsounds/autoadd/zelda_ww/glaugh/ww_ganondorf_foundzelda.ogg",length=6.598}}
L["grouch"]={{path="chatsounds/autoadd/zelda_ww/grouch.ogg",length=1.129}}
L["haahahaha"]={{path="chatsounds/autoadd/zelda_ww/haahahaha.ogg",length=2.412}}
L["hah"]={{path="chatsounds/autoadd/zelda_ww/hah.ogg",length=0.432}}
L["haha"]={{path="chatsounds/autoadd/zelda_ww/haha.ogg",length=1.098}}
L["happygasp"]={{path="chatsounds/autoadd/zelda_ww/happygasp.ogg",length=0.777}}
L["heey"]={{path="chatsounds/autoadd/zelda_ww/heey/ww_korl_heey1.ogg",length=1.727},{path="chatsounds/autoadd/zelda_ww/heey/ww_korl_heey2.ogg",length=0.880}}
L["hey"]={{path="chatsounds/autoadd/zelda_ww/hey/ww_korl_hey.ogg",length=0.405},{path="chatsounds/autoadd/zelda_ww/hey/ww_medli_hey.ogg",length=0.315},{path="chatsounds/autoadd/zelda_ww/hey/ww_postman_hey.ogg",length=0.451}}
L["hi"]={{path="chatsounds/autoadd/zelda_ww/hi.ogg",length=0.653}}
L["hiee"]={{path="chatsounds/autoadd/zelda_ww/hiee.ogg",length=0.912}}
L["hmm"]={{path="chatsounds/autoadd/zelda_ww/hmm.ogg",length=0.490}}
L["hmmm"]={{path="chatsounds/autoadd/zelda_ww/hmmm.ogg",length=1.198}}
L["hmmmm"]={{path="chatsounds/autoadd/zelda_ww/hmmmm.ogg",length=1.583}}
L["hmn"]={{path="chatsounds/autoadd/zelda_ww/hmn.ogg",length=0.538}}
L["hmnn"]={{path="chatsounds/autoadd/zelda_ww/hmnn.ogg",length=0.979}}
L["hoo"]={{path="chatsounds/autoadd/zelda_ww/hoo.ogg",length=2.678}}
L["hooray yay"]={{path="chatsounds/autoadd/zelda_ww/hooray yay.ogg",length=1.721}}
L["hoy"]={{path="chatsounds/autoadd/zelda_ww/hoy/ww_aryll_hoy1.ogg",length=0.914},{path="chatsounds/autoadd/zelda_ww/hoy/ww_aryll_hoy2.ogg",length=1.365}}
L["huh"]={{path="chatsounds/autoadd/zelda_ww/huh/ww_salvatore_huh.ogg",length=0.430},{path="chatsounds/autoadd/zelda_ww/huh/ww_tingle_huh.ogg",length=0.474}}
L["huhuhahahah"]={{path="chatsounds/autoadd/zelda_ww/huhuhahahah.ogg",length=1.830}}
L["hup"]={{path="chatsounds/autoadd/zelda_ww/hup.ogg",length=0.294}}
L["hwah"]={{path="chatsounds/autoadd/zelda_ww/hwah.ogg",length=0.454}}
L["kerboom"]={{path="chatsounds/autoadd/zelda_ww/kerboom.ogg",length=1.686}}
L["kooloolim"]={{path="chatsounds/autoadd/zelda_ww/kooloolim.ogg",length=0.776}}
L["kyraa"]={{path="chatsounds/autoadd/zelda_ww/kyraa.ogg",length=1.655}}
L["kyraw"]={{path="chatsounds/autoadd/zelda_ww/kyraw.ogg",length=1.410}}
L["muhuhuh"]={{path="chatsounds/autoadd/zelda_ww/muhuhuh.ogg",length=1.300}}
L["oh"]={{path="chatsounds/autoadd/zelda_ww/oh.ogg",length=1.429}}
L["ohhh"]={{path="chatsounds/autoadd/zelda_ww/ohhh.ogg",length=2.040}}
L["ooh"]={{path="chatsounds/autoadd/zelda_ww/ooh.ogg",length=1.546}}
L["ooyy"]={{path="chatsounds/autoadd/zelda_ww/ooyy.ogg",length=1.125}}
L["oy"]={{path="chatsounds/autoadd/zelda_ww/oy.ogg",length=0.768}}
L["oyoy"]={{path="chatsounds/autoadd/zelda_ww/oyoy.ogg",length=1.891}}
L["pah"]={{path="chatsounds/autoadd/zelda_ww/pah.ogg",length=0.220}}
L["que"]={{path="chatsounds/autoadd/zelda_ww/que.ogg",length=0.962}}
L["secret"]={{path="chatsounds/autoadd/zelda_ww/secret.ogg",length=2.523}}
L["shoo"]={{path="chatsounds/autoadd/zelda_ww/shoo.ogg",length=0.769}}
L["sneer"]={{path="chatsounds/autoadd/zelda_ww/sneer.ogg",length=0.499}}
L["sploosh"]={{path="chatsounds/autoadd/zelda_ww/sploosh.ogg",length=1.365}}
L["struggle"]={{path="chatsounds/autoadd/zelda_ww/struggle/ww_link_struggle1.ogg",length=0.501},{path="chatsounds/autoadd/zelda_ww/struggle/ww_link_struggle2.ogg",length=0.486},{path="chatsounds/autoadd/zelda_ww/struggle/ww_link_struggle3.ogg",length=0.628}}
L["surprised"]={{path="chatsounds/autoadd/zelda_ww/surprised.ogg",length=0.543}}
L["tetrawink"]={{path="chatsounds/autoadd/zelda_ww/tetrawink.ogg",length=1.916}}
L["thank you"]={{path="chatsounds/autoadd/zelda_ww/thank you.ogg",length=1.382}}
L["uhhm"]={{path="chatsounds/autoadd/zelda_ww/uhhm.ogg",length=1.294}}
L["uhhuh"]={{path="chatsounds/autoadd/zelda_ww/uhhuh.ogg",length=0.825}}
L["upset"]={{path="chatsounds/autoadd/zelda_ww/upset.ogg",length=1.445}}
L["wait"]={{path="chatsounds/autoadd/zelda_ww/wait.ogg",length=0.798}}
L["woooo"]={{path="chatsounds/autoadd/zelda_ww/woooo.ogg",length=3.549}}
L["worried"]={{path="chatsounds/autoadd/zelda_ww/worried.ogg",length=0.658}}
L["wow"]={{path="chatsounds/autoadd/zelda_ww/wow.ogg",length=1.505}}
L["wuhahahaha"]={{path="chatsounds/autoadd/zelda_ww/wuhahahaha.ogg",length=1.642}}
L["wwfanfare"]={{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_heartcontainer.ogg",length=3.518},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_item.ogg",length=2.495},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_newsong.ogg",length=2.921},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_pearl.ogg",length=3.084},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_rupee.ogg",length=1.805},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_smallitem.ogg",length=2.602},{path="chatsounds/autoadd/zelda_ww/wwfanfare/ww_fanfare_treasurechest.ogg",length=2.170}}
L["yay"]={{path="chatsounds/autoadd/zelda_ww/yay/ww_link_yay.ogg",length=0.517},{path="chatsounds/autoadd/zelda_ww/yay/ww_tingle_yay.ogg",length=1.249}}
L["yoop"]={{path="chatsounds/autoadd/zelda_ww/yoop.ogg",length=0.506}}
c.EndList()