c.StartList("portal")
L["as part of an optional test protocol we are pleased to present an amusing fact"]={{path="vo/aperture_ai/07_part1_get_device_component-2.wav",length=5.5448752834467,},}
L["jeep barnett a few playtesters put a portal on the floor here and used the rising stair pit to skip the rest of the puzzle well usually rework a level if playtesters discover a way to bypass chunks of the puzzle too easily but in this and a few other cases where skipping ahead arguably takes more skill than solving the puzzle properly we let the ninja solution stand"]={{path="commentary/prtl-comment066.wav",length=21.314036281179,},}
L["i feel sorry for you really because youre not even in the right place"]={{path="vo/aperture_ai/escape_01_part1_nag07-1.wav",length=4.3790929705215,},}
L["you should have turned left before"]={{path="vo/aperture_ai/escape_01_part1_nag08-1.wav",length=2.5263945578231,},}
L["i wouldnt bother with that thing my guess is that touching it will just make your life even worse somehow"]={{path="vo/aperture_ai/escape_02_spherenag1-01.wav",length=5.6533333333333,},}
L["do not look directly at the operational end of the device"]={{path="vo/aperture_ai/01_part1_get_portal_gun-6.wav",length=3.6920634920635,},}
L["because i dont think youre going where you think youre going"]={{path="vo/aperture_ai/escape_00_part1_nag09-1.wav",length=3.8805215419501,},}
L["garret rickey we noticed through our playtests that many of our players werent aware of the fact that you could place portals while falling since placing portals as you are falling is essential to accomplishing flings and many other portal tricks we implemented this puzzle so that the only way to solve it was to use the midair placement tactic it took numerous iterations and lots of tuning before this consistently played well"]={{path="commentary/prtl-comment070.wav",length=19.292879818594,},}
L["kerry davis this room was designed to make players understand that entrance and exit portals arent tied to the color of the portal playtesters often assumed that orange portals were exitonly so we created this puzzle to force players to enter an orange portal"]={{path="commentary/prtl-comment026.wav",length=12.956734693878,},}
L["someday well remember this and laugh and laugh and laugh oh boy well you may as well come on back"]={{path="vo/aperture_ai/escape_01_part1_nag10-1.wav",length=9.6533333333333,},}
L["one tablespoon allpurpose rhubarb"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-28.wav",length=3.2972335600907,},}
L["ellen mclain voice of glados in the sound booth youre only connected to the production team by an intercom and they can talk about you and you dont know what theyre saying but you trust that theyre being kind and you know theyll theyll push a button and then theyll say something to me they say a direction no that wasnt right do it again give us three more reads and a lot of time what happens is theyll they would play the computergenerated sound for me on one line and then im supposed to recreate that three times with the director saying ok well you know more sarcastic or more angry or or more irritated so you stand in the booth hour after hour after hour theyre always very nice they let you have water in here and maybe a pencil to take a few notes and of course you want it to be interesting because you want them to hire you again"]={{path="commentary/prtl-comment106.wav",length=60.073492063492,},}
L["never mind its a mystery ill solve later by myself because youll be dead"]={{path="vo/aperture_ai/escape_02_spheredrop1-03.wav",length=5.0317006802721,},}
L["ow ow ow"]={{path="npc/turret_floor/turret_fizzler_1.wav",length=2.0824716553288,},}
L["testing cannot continue until your companion cube has been incinerated"]={{path="vo/aperture_ai/13_part1_endnag-3.wav",length=4.3421315192744,},}
L["you havent escaped you know"]={{path="vo/aperture_ai/escape_00_part1_nag05-1.wav",length=2.4318140589569,},}
L["low rumble"]={{path="vo/escape/portal_escape_seg03-4.wav",length=8,},}
L["one 1825 ounce package chocolate cake mix"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-01.wav",length=4.6904308390023,},}
L["your specimen has been processed and we are now ready to begin the test proper"]={{path="vo/aperture_ai/00_part1_entry-3.wav",length=4.888253968254,},}
L["rrr i hate youpain laughter"]={{path="vo/aperture_ai/escape_02_spheredestroy4-01.wav",length=2.0266666666667,},}
L["portalgun secondary fire"]={{path="weapons/portalgun/portalgun_shoot_red1.wav",length=0.8220634920635,},}
L["oh well if you want my advice you should just lie down in front of a rocket trust me itll be a lot less painful than the neurotoxin"]={{path="vo/aperture_ai/escape_02_spheredestroy1-08.wav",length=9.4293424036281,},}
L["garret rickey we use these moving platforms to add time pressure to puzzles a sequence of simple decisions feels much more climactic under time pressure in contrast to most puzzles in portal which can be solved at the players leisure puzzles that arent time bound can be more complex but at the expense of being less dramatic"]={{path="commentary/prtl-comment097.wav",length=16.642902494331,},}
L["fiberglass surface resins"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-20.wav",length=2.2755555555556,},}
L["portalgun upgraded"]={{path="weapons/portalgun/portalgun_powerup1.wav",length=1.3081405895692,},}
L["this is your last chance"]={{path="vo/aperture_ai/escape_01_part1_nag06-1.wav",length=1.7155555555556,},}
L["one cross borehole electromagnetic imaging rhubarb"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-32.wav",length=5.1548299319728,},}
L["garret rickey the combination of the prtldestroying fields which we call fizzlers and the elevators serve a dual purpose they provide a clearly identifiable endpoint for each testchamber while also addressing the more practical problem of how to keep players from portaling across level loads we eventually integrated the fizzlers into several of our puzzle designs"]={{path="commentary/prtl-comment020.wav",length=17.345306122449,},}
L["i could take a bath in the stuff put it on cereal rub it right into my eyes honestly its not deadly at all to me"]={{path="vo/aperture_ai/escape_02_miscbabble-12.wav",length=8.3450113378685,},}
L["mechanical arm"]={{path="vo/escape/portal_escape_seg03-6.wav",length=8.4,},}
L["for instance the floor here will kill you try to avoid it"]={{path="vo/aperture_ai/07_part1_entry-3.wav",length=3.9751473922902,},}
L["the enrichment center is required to remind you that you will be baked garbled cake"]={{path="vo/aperture_ai/14_part1_entry-2.wav",length=6.5177551020408,},}
L["its funny actually when you think about it"]={{path="vo/aperture_ai/escape_01_part1_nag09-1.wav",length=3.1385487528345,},}
L["nine large egg yolks"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-22.wav",length=1.6253968253968,},}
L["you chose this path now i have a surprise for you deploying surprise in five four"]={{path="vo/aperture_ai/escape_02_entry-04.wav",length=6.0665079365079,},}
L["an entry called how to kill someone with your bare hands"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-25.wav",length=4.6189795918367,},}
L["an intubation associate will be dispatched to revive you with peptic salve and adrenaline"]={{path="vo/aperture_ai/08_part1_entry-3.wav",length=6.1813378684807,},}
L["the experiment is nearing its conclusion"]={{path="vo/aperture_ai/14_part1_entry-1.wav",length=3.0122448979592,},}
L["rocket locked"]={{path="weapons/rocket/rocket_locked_beep1.wav",length=1.0774149659864,},}
L["jeremy bennett glados the rogue disk operating system that now runs aperture science went through a bunch of design iterations earlier versions included a floating brain a sprawling spidery mechanism and an upsidedown version of botticellis rise of venus built out of robot parts and wire evenutally we settled on a huge mechanical device with a delicate robotic figure dangling out of it which successfully conveys both gladoss raw power and her femininity"]={{path="commentary/prtl-comment013.wav",length=24.261950113379,},}
L["the device has been modified so that it can now manufacture two linked portals at once"]={{path="vo/aperture_ai/07_part1_get_device_component-1.wav",length=5.2762585034014,},}
L["vital testing apparatus destroyed"]={{path="vo/aperture_ai/generic_security_camera_destroyed-5.wav",length=2.4571201814059,},}
L["jeep barnett one bizarre fact of game design is that without some serious prompting players will rarely look up in this case the prompt is a ladder most players will investigate where the ladder goes which is up the ladder actually falls apart as soon as its touched but by then its served its purpose"]={{path="commentary/prtl-comment002.wav",length=17.259954648526,},}
L["the enrichment center apologizes for the inconvenience and wishes you the best of luck"]={{path="vo/aperture_ai/11_part1_entry-3.wav",length=5.5193197278912,},}
L["critical error"]={{path="npc/turret_floor/turret_disabled_2.wav",length=1.5266893424036,},{path="npc/turret_floor/turret_disabled_4.wav",length=1.7008390022676,},{path="npc/turret_floor/turret_disabled_5.wav",length=2.1546712018141,},{path="npc/turret_floor/turret_disabled_6.wav",length=1.8053514739229,},{path="npc/turret_floor/turret_disabled_7.wav",length=1.640589569161,},{path="npc/turret_floor/turret_disabled_8.wav",length=2.8,},}
L["david kircher for the first few months of development we rendered the views through portals to two offscreen textures this approach was easy to implement and was compatible with a wide range of graphics hardware unfortunately this method was incompatible with antialiasing and consumed a large amount of video memory in order to handle recursive views through several portals because of these disadvantages we switched to a system which renders portal views recursively into the frame buffer with the aid of the stencil buffer to isolate pixels corresponding to a given portal this is a more effective scheme because it is compatible with antialiasing and does not consume any additional video memory for offscreen textures"]={{path="commentary/prtl-comment036.wav",length=34.561541950113,},}
L["good people dont end up here"]={{path="vo/aperture_ai/escape_01_part1_nag02-1.wav",length=2.8186848072562,},}
L["weighted storage cube destroyed"]={{path="vo/aperture_ai/generic_crate_lost-1.wav",length=1.941746031746,},}
L["hey its me"]={{path="npc/turret_floor/turret_shotat_1.wav",length=1.7093424036281,},{path="npc/turret_floor/turret_shotat_2.wav",length=1.3653514739229,},{path="npc/turret_floor/turret_shotat_3.wav",length=1.4080045351474,},}
L["growl"]={{path="vo/aperture_ai/escape_02_sphere_anger-08.wav",length=1.0071655328798,},{path="vo/aperture_ai/escape_02_sphere_anger-03.wav",length=1.102947845805,},{path="vo/aperture_ai/escape_02_sphere_anger-09.wav",length=0.6037188208617,},{path="vo/aperture_ai/escape_02_sphere_anger-19.wav",length=0.8707482993197,},{path="vo/aperture_ai/escape_02_sphere_anger-04.wav",length=0.6225850340136,},{path="vo/aperture_ai/escape_02_sphere_anger-11.wav",length=1.149387755102,},{path="vo/aperture_ai/escape_02_sphere_anger-07.wav",length=0.6501587301587,},}
L["first however note the incandescent particle field across the exit"]={{path="vo/aperture_ai/00_part1_success-2.wav",length=4.6613378684807,},}
L["hey look at that thing no that other thing"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-07.wav",length=2.0781859410431,},}
L["but we both know that isnt going to happen"]={{path="vo/aperture_ai/escape_02_entry-03.wav",length=3.1680045351474,},}
L["stop squirming and die like an adult or im going to delete your backup"]={{path="vo/aperture_ai/escape_02_spheredestroy4-07.wav",length=3.4133333333333,},}
L["ha im making more thats going to take a few minutes though meanwhile oh look its your old pal the rocket turret"]={{path="vo/aperture_ai/escape_02_spheredestroy1-ancillary2.wav",length=6.7192743764172,},}
L["all right keep doing whatever it is you think youre doing"]={{path="vo/aperture_ai/escape_02_spheredestroy1-09.wav",length=3.7973469387755,},}
L["are you even listening to me"]={{path="vo/aperture_ai/escape_02_spherenag1-15.wav",length=1.9093424036281,},}
L["enrichment center regulations require both hands to be empty before any cake can be served garbled"]={{path="vo/aperture_ai/15_part1_entry-3.wav",length=7.438231292517,},}
L["through no fault of the enrichment center you have managed to trap yourself in this room"]={{path="vo/aperture_ai/07_part1_trapped-1.wav",length=5.0614965986395,},}
L["erik wolpaw before the player escapes the fire pit the ai dialog is all delivered in a computerized monotone after the escape however glados gets progressively more expressive until by the end shes cycling through a whole mess of emotions the role required an actor capable of mimicking the computergenerated voice while still infusing it with some real character and since we planned to end the game with a song she also needed to have a good singing voice the woman we cast ellen mcclane is a great mimic a terrific actor and a classically trained operatic soprano so that worked out pretty good"]={{path="commentary/prtl-comment095.wav",length=31.867755102041,},}
L["once again the enrichment center offers its most sincere apologies on the occasion of this unsolvable test environment"]={{path="vo/aperture_ai/05_part1_nag2-1.wav",length=8.4192517006803,},}
L["despite the best efforts of the enrichment center staff to ensure the safe performance of all authorized activities you have managed to ensnare yourself permanently inside this room"]={{path="vo/aperture_ai/08_part1_trapped-1.wav",length=10.540249433107,},}
L["garret rickey portal momentum ended up being the hardest concept to convey for this series of puzzles which went through more design iterations than virtually any other part of the game we introduce the idea of redirecting your momentum using portals slowly step by step we even have the ai voice pretty explicitly explain the elements of the puzzle something we avoided throughout most of the rest of the game"]={{path="commentary/prtl-comment048.wav",length=19.928526077098,},}
L["incinerate your companion cube"]={{path="vo/aperture_ai/13_part1_endnag-8.wav",length=2.0897959183673,},}
L["lights click on"]={{path="vo/escape/portal_escape_seg03-5.wav",length=8,},}
L["stand back the portal will open in three two one"]={{path="vo/aperture_ai/00_part1_entry-7.wav",length=5.7414512471655,},}
L["do you smell something burning"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-15.wav",length=1.3351473922902,},}
L["adjustable aluminum head positioner"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-34.wav",length=2.91410430839,},}
L["chet faliszek for training purposes theres generally just one correct solution to these early puzzles the original version of this room didnt have the glass barrier playtesters would often stand on the button to open the door and then shoot a blue portal through the opening bypassing the box entirely since this puzzle was meant illustrate the relationship between boxes and buttons that solution while clever was a failure so we added the glass barrier to prevent it later in the game however the puzzles become more openended"]={{path="commentary/prtl-comment032.wav",length=27.469206349206,},}
L["one teaspoon grated orange rhubarb"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-29.wav",length=3.2043537414966,},}
L["you cant hurt me"]={{path="vo/aperture_ai/escape_00_part1_nag06-1.wav",length=1.5258049886621,},}
L["energy cascades"]={{path="vo/escape/portal_escape_seg01-5.wav",length=8,},}
L["pain noise you think youre doing some damage two plus two is ten in base four im fine"]={{path="vo/aperture_ai/escape_02_spheredestroy3-01.wav",length=9.4560544217687,},}
L["fish shaped organic compounds and sediment shaped sediment"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-15.wav",length=5.8978684807256,},}
L["please proceed to the aperture science vital apparatus vent for a replacement"]={{path="vo/aperture_ai/generic_crate_lost-2.wav",length=5.8241950113379,},}
L["maybe you should marry that thing since you love it so much do you want to marry it well i wont let you how does that feel"]={{path="vo/aperture_ai/escape_02_spherenag1-07.wav",length=6.7626757369615,},}
L["stop what you are doing and assume the party escort submission position"]={{path="vo/aperture_ai/15_part1_partyreminder-1.wav",length=4.4990022675737,},}
L["two tablespoons rhubarb juice"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-33.wav",length=2.9960997732426,},}
L["do you see that thing that fell out of me what is that its not the surprise ive never seen it before"]={{path="vo/aperture_ai/escape_02_spheredrop1-02.wav",length=5.5702494331066,},}
L["ding off"]={{path="vo/aperture_ai/ding_off.wav",length=0.19,},}
L["kim swift in these new areas we werent using the surfaces the player is familiar with the rules for which new surfaces portals can be placed on and which surfaces are offlimits needed to be taught so we created this area both to show the player they have escaped into the guts of the facility and to retrain them in which surfaces are valid for portal placement"]={{path="commentary/prtl-comment098.wav",length=18.717437641723,},}
L["ding on"]={{path="vo/aperture_ai/ding_on.wav",length=0.19,},}
L["exit portal"]={{path="player/portal_exit1.wav",length=0.7483446712018,},{path="player/portal_exit2.wav",length=1.5877097505669,},}
L["very very good a complimentary victory lift has been activated in the main chamber"]={{path="vo/aperture_ai/09_part1_success-1.wav",length=5.9140589569161,},}
L["paul graham during development wed often run across some piece of level design that would break the portal system for instance this ceilingtoceiling transition was an unexpected edge case that ended up requiring a lot of effort to make work we tried never to take the easy route of simply changing the level design to work with existing portal technology we knew that once the game was out in the wild custom map creators would stress the system in ways we hadnt even considered so we made it as flexible as possible"]={{path="commentary/prtl-comment005.wav",length=29.190884353741,},}
L["fish shaped candies"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-10.wav",length=1.2829024943311,},}
L["lets be honest neither one of us knows what that thing does just put it in the corner and ill deal with it later"]={{path="vo/aperture_ai/escape_02_spherenag1-05.wav",length=7.04,},}
L["we are throwing a party in honor of your tremendous success"]={{path="vo/aperture_ai/15_part1_partyspeech-3.wav",length=4.3479138321995,},}
L["portal fizzled"]={{path="weapons/portalgun/portal_fizzle2.wav",length=1.3077777777778,},}
L["now that you are in control of both portals this next test could take a very very long time"]={{path="vo/aperture_ai/08_part1_entry-1.wav",length=6.739410430839,},}
L["who are you"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-01.wav",length=1.2306575963719,},}
L["realm lovejoy breaking this tube gives players a chance to test out their newly trained rocketredirecting and glassbreaking skills in a slightly different context which helps cement the training"]={{path="commentary/prtl-comment008.wav",length=9.7740589569161,},}
L["you on the other hand are going to find its deadliness a lot less funny"]={{path="vo/aperture_ai/escape_02_miscbabble-13.wav",length=4.3413378684807,},}
L["crashing debris"]={{path="vo/escape/portal_escape_seg02-2.wav",length=4,},}
L["we hope your brief detention in the relaxation vault has been a pleasant one"]={{path="vo/aperture_ai/00_part1_entry-2.wav",length=4.2590476190476,},}
L["huh there isnt enough neurotoxin to kill you so i guess you win"]={{path="vo/aperture_ai/escape_02_spheredestroy1-ancillary1.wav",length=4.6439909297052,},}
L["roar"]={{path="vo/aperture_ai/escape_02_sphere_anger-14.wav",length=1.369977324263,},{path="vo/aperture_ai/escape_02_sphere_anger-21.wav",length=0.8054421768707,},{path="vo/aperture_ai/escape_02_sphere_anger-15.wav",length=0.8126984126984,},{path="vo/aperture_ai/escape_02_sphere_anger-20.wav",length=1.0448979591837,},}
L["very good you are now in possession of the aperture science handheld portal device"]={{path="vo/aperture_ai/01_part1_get_portal_gun-1.wav",length=7.6320181405896,},}
L["fan spinning"]={{path="ambient/machines/fan4.wav",length=0.7692970521542,},}
L["ticking timer"]={{path="ambient/machines/ticktock1.wav",length=0.6699319727891,},}
L["this aperture science material emancipation grid will vaporize any unauthorized equipment that passes through it for instance the aperture science weighted storage cube"]={{path="vo/aperture_ai/00_part1_success-3.wav",length=12.287596371882,},}
L["kim swift we designed the postescape levels to give players brief glimpses of the inner workings of the enrichment center this particular area exposes part of the storage cube distribution system these little vignettes help make this section of the game visually distinct from the testing chambers while reinforcing the idea that players are now behindthescenes"]={{path="commentary/prtl-comment001.wav",length=18.254489795918,},}
L["well done be advised that the next test requires exposure to uninsulated electrical parts that may be dangerous under certain conditions"]={{path="vo/aperture_ai/14_part1_end-1.wav",length=9.6348752834467,},}
L["congratulations the test is now over"]={{path="vo/aperture_ai/15_part1_into_the_fire-1.wav",length=2.8120408163265,},}
L["oh whats in here"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-17.wav",length=2.4148752834467,},}
L["welcome to test chamber four"]={{path="vo/aperture_ai/02_part1_entry-1.wav",length=2.0275283446712,},}
L["it was a morality core they installed after i flooded the enrichment center with a deadly neurotoxin to make me stop flooding the enrichment center with a deadly neurotoxin"]={{path="vo/aperture_ai/escape_02_spheredestroy1-05.wav",length=10.11201814059,},}
L["realm lovejoy these frostedglass observation rooms make the player feel as if theyre being watched at all times while keeping the identity of these watchers a mystery the rooms serve a practical purpose as well since we often use them as convenient and logical light sources for the test chambers"]={{path="commentary/prtl-comment019.wav",length=15.786009070295,},}
L["nice job breaking it hero"]={{path="vo/aperture_ai/escape_02_miscbabble-08.wav",length=1.8080045351474,},}
L["an escape hatch will open in three two one"]={{path="vo/aperture_ai/07_part1_trapped-2.wav",length=4.122335600907,},}
L["file deleted"]={{path="vo/aperture_ai/file_deleted.wav",length=0.7598866213152,},}
L["kim swift its absolutely critical that players quickly wrap their heads around what a portal is we noticed early playtesters grasped the concept much more quickly when they caught a glimpse of themselves through a portal so we deliberately positioned this first portal to ensure that players will invariably see themselves"]={{path="commentary/prtl-comment021.wav",length=15.79231292517,},}
L["excellent please proceed into the chamberlock after completing each test"]={{path="vo/aperture_ai/00_part1_success-1.wav",length=5.4380045351474,},}
L["oh im gonna kill you"]={{path="vo/aperture_ai/escape_01_first_hit_nag03-1.wav",length=3.0334920634921,},}
L["lars jensvold we designed this room to draw the players eyes to the box the light from the observation room casts horizontal shadows that point at the box which is directly lit by a warm light from the ceiling this warm light helps the box stand out against the predominantly cool test chamber lighting the varying sized squares of the off limits surface also help direct the players attention upward"]={{path="commentary/prtl-comment068.wav",length=21.762244897959,},}
L["however it cannot accompany you for the rest of the test and unfortunately must be euthanized"]={{path="vo/aperture_ai/13_part1_end-2.wav",length=6.8731065759637,},}
L["audible warning devices are required on all mobile equipment however alarms and flashing hazard lights have been found to agitate the high energy pellet and have therefore been disabled for your safety"]={{path="vo/aperture_ai/03_part2_entry-1.wav",length=12.790430839002,},}
L["as part of a required test protocol our previous statement suggesting that we would not monitor this chamber was an outright fabrication"]={{path="vo/aperture_ai/02_part2_success-1.wav",length=9.0422448979592,},}
L["dont forget garnishes such as"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-08.wav",length=2.4845351473923,},}
L["please proceed to the chamberlock mind the gap"]={{path="vo/aperture_ai/01_part2_entry-1.wav",length=3.4519274376417,},}
L["kim swift this particular section went through several iterations because its the first place where players are required to perform possibly the trickiest portal maneuver the double fling originally the room also featured an energy ball redirection puzzle combined with the new double fling skill however it proved to be too much for most playtesters overwhelmed players tend not to digest new information so we simplified the puzzle to require only the double fling to nudge players in the right direction we also included visual hints such as the previously introduced single fling theme the pushed out concrete slab with a checkerboard landing zone"]={{path="commentary/prtl-comment069.wav",length=35.134920634921,},}
L["momentum a function of mass and velocity is conserved between portals in laymans terms speedy thing goes in speedy thing comes out"]={{path="vo/aperture_ai/06_part1_success_2-1.wav",length=9.7508163265306,},}
L["erik wolpaw even though portal tells a simple story we created a lot of backstory for aperture science for its employees for its rivalry with the hated black mesa and for where all of this fits into the cosmology of half life this first portal game doesnt reveal all of it but we crammed a lot of little details into the environments this area for instance called the ratman den hints that there may be other people trapped in the facility"]={{path="commentary/prtl-comment077.wav",length=22.547278911565,},}
L["the enrichment center reminds you that the weighted companion cube cannot speak"]={{path="vo/aperture_ai/13_part1_middle-2b-1.wav",length=4.84,},}
L["place the device on the ground then lie on your stomach with your arms at your sides"]={{path="vo/aperture_ai/15_part1_partyspeech-4.wav",length=4.9772789115646,},}
L["all i know is im the only thing standing between us and them well i was"]={{path="vo/aperture_ai/escape_02_spheredestroy4-04.wav",length=6.8480045351474,},}
L["maybe you could settle for that and well just call it a day"]={{path="vo/aperture_ai/escape_02_entry-02.wav",length=3.1680045351474,},}
L["good job as part of a required test protocol we will stop enhancing the truth in three two one"]={{path="vo/aperture_ai/02_part2_success-2.wav",length=9.6866439909297,},}
L["most importantly under no circumstances should you bzzzpt"]={{path="vo/aperture_ai/01_part1_get_portal_gun-8.wav",length=4.8280498866213,},}
L["fish shaped crackers"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-09.wav",length=1.2509750566893,},}
L["one and two third cups granulated sugar"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-06.wav",length=3.4829931972789,},}
L["blue portal open"]={{path="weapons/portalgun/portal_open1.wav",length=1.8926984126984,},}
L["ewww whats wrong with your legs"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-08.wav",length=1.5267120181406,},}
L["speaking of curiosity youre curious about what happens after you die right guess what i know"]={{path="vo/aperture_ai/escape_02_spheredestroy2-03.wav",length=8.1706802721088,},}
L["well done remember the aperture science bring your daughter to work day is the perfect time to have her tested"]={{path="vo/aperture_ai/01_part2_success-1.wav",length=6.1013378684807,},}
L["there really was a cake on entry to boss room"]={{path="vo/aperture_ai/escape_01_death_nag01-1.wav",length=5.5057823129252,},}
L["dont believe me here ill put you on hellooo thats you thats how dumb you sound"]={{path="vo/aperture_ai/escape_02_spheredestroy3-05.wav",length=5.3754195011338,},}
L["please be careful"]={{path="vo/aperture_ai/03_part1_entry-2.wav",length=1.2614058956916,},}
L["what are you doing"]={{path="vo/aperture_ai/escape_00_part1_nag04-1.wav",length=1.5258049886621,},}
L["erik wolpaw creating the ai voice was a multistep process first we ran every line of dialog through an automatic texttospeech program in the studio we cued the actress who plays glados ellen mcclane with the computergenerated sound file shed mimic it and then over the course of several takes adjust her performance to clean up any words that were unintelligible in the computer version for instance heres a line as ellen delivered it once the recording was done we processed all of the dialog to give it an extra computery edge heres that same line as it appears in the game with the pitch constrained pitch modulation suppressed and the formant moved up "]={{path="commentary/prtl-comment000.wav",length=58.545419501134,},}
L["spectacular you appear to understand how a portal affects forward momentum or to be more precise how it does not"]={{path="vo/aperture_ai/06_part1_success_1-1.wav",length=8.3809523809524,},}
L["slaughter electric needle injector"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-35.wav",length=2.7573696145125,},}
L["neurotoxin cough cough so deadly cough choking laughter im kidding"]={{path="vo/aperture_ai/escape_02_miscbabble-10.wav",length=10.028798185941,},}
L["good now use the aperture science unstationary scaffold to reach the chamberlock"]={{path="vo/aperture_ai/03_part2_platform_activated-1.wav",length=6.6371428571429,},}
L["thats it im done reasoning with you"]={{path="vo/aperture_ai/escape_02_miscbabble-16.wav",length=2.9024943310658,},}
L["youre going to find out first hand before id finish explaining it though so i wont bother"]={{path="vo/aperture_ai/escape_02_spheredestroy2-04.wav",length=4.7360090702948,},}
L["portal failed"]={{path="weapons/portalgun/portal_invalid_surface3.wav",length=0.9902040816327,},}
L["the symptoms most commonly produced by enrichment center testing are superstition perceiving inanimate objects as alive and hallucinations"]={{path="vo/aperture_ai/13_part1_middle-1.wav",length=9.48,},}
L["leave it alone"]={{path="vo/aperture_ai/escape_02_spherenag1-12.wav",length=1.4613378684807,},}
L["hello and again welcome to the aperture science computeraided enrichment center"]={{path="vo/aperture_ai/00_part1_entry-1.wav",length=5.9050340136054,},}
L["make no further attempt to leave the testing area"]={{path="vo/aperture_ai/15_part1_partyspeech-6.wav",length=3.1785941043084,},}
L["realm lovejoy even though we didnt want portal to be too combat heavy we wanted to add at least a light combat mechanic after a few lessthansuccessful attempts to actually realize this light combat concept we settled on turrets as a good compromise the turrets can be defeated with tricky portal maneuvers but theyre also susceptible to a more straightforward berserker approach"]={{path="commentary/prtl-comment080.wav",length=21.518752834467,},}
L["well you found me congratulations was it worth it"]={{path="vo/aperture_ai/escape_02_entry-00.wav",length=3.6480045351474,},}
L["peppy music"]={{path="ambient/music/looping_radio_mix.wav",length=21.999319727891,},}
L["high pitched squeal"]={{path="vo/escape/portal_escape_seg01-4.wav",length=8,},}
L["go ahead and break it hero i dont care"]={{path="vo/aperture_ai/escape_01_part1_nag12-1.wav",length=2.8403401360544,},}
L["come on leave it alone"]={{path="vo/aperture_ai/escape_02_spherenag1-11.wav",length=1.8826757369615,},}
L["calming wind"]={{path="vo/escape/portal_escape_seg01-6.wav",length=9.4666666666667,},}
L["all subjects intending to handle highenergy gamma leaking portal technology must be informed that they may be informed of applicable regulatory compliance issues"]={{path="vo/aperture_ai/09_part1_entry-1.wav",length=9.8084126984127,},}
L["all your other friends couldnt come either because you dont have any other friends because of how unlikable you are"]={{path="vo/aperture_ai/escape_02_miscbabble-24.wav",length=6.1997278911565,},}
L["for your own safety and the safety of others please refrain from touching bzzzzzt"]={{path="vo/aperture_ai/00_part1_entry-5.wav",length=5.2749659863946,},}
L["look youre wasting your time and believe me you dont have a whole lot left to waste"]={{path="vo/aperture_ai/escape_02_spheredestroy3-02.wav",length=6.9760090702948,},}
L["oh hey youre the lady from the test hi"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-11.wav",length=2.9024943310658,},}
L["realm lovejoy in this puzzle we wanted players to realize that using portals they can travel long distances in a short step originally we had stairs from the ground level to the upper rooms many playtesters however were able to run from one room to the other quickly enough to consider it a solution without ever thinking to use the even easier portal method by changing the stairs to very slow moving lifts we were able to level the travel time for all player experience levels thus making the intended solution more clear"]={{path="commentary/prtl-comment071.wav",length=27.973650793651,},}
L["rest assured that an independent panel of ethicists has absolved the enrichment center aperture science employees and all test subjects of any moral responsibility for the companion cube euthanizing process"]={{path="vo/aperture_ai/13_part1_endnag-1.wav",length=13.688163265306,},}
L["air rushing"]={{path="player/fling_whoosh.wav",length=3.144126984127,},{path="ambient/wind/tube_suck.wav",length=3.144126984127,},}
L["that thing youre attacking isnt important to me its the fluid catalytic cracking unit it makes shoes for orphans"]={{path="vo/aperture_ai/escape_01_part1_nag11-1.wav",length=8.7824036281179,},}
L["unbelievable you subject name here must be the pride of subject hometown here"]={{path="vo/aperture_ai/03_part1_success-1.wav",length=6.9187755102041,},}
L["fish shaped dirt"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-12.wav",length=1.3931972789116,},}
L["whats that"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-04.wav",length=0.8475283446712,},}
L["david kircher this is a great spot to appreciate the recursive nature of portals if you place a portal on each side of this hallway youll notice the portals seem to go on forever similar to the effect you get in a hall of mirrors in actuality we support a maximum of nine recursive portal views down any chain of portals we achieve the impression of infinite recursion by copying part of the previously rendered frame onto the final portal in the recursive chain its not absolutely perfect but its inexpensive and effective"]={{path="commentary/prtl-comment061.wav",length=25.298095238095,},}
L["birds sing"]={{path="vo/escape/portal_escape_seg02-3.wav",length=4,},}
L["that will deodorize and preserve putrid tissue"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-41.wav",length=3.6687528344671,},}
L["where are you taking that thing"]={{path="vo/aperture_ai/escape_02_spherenag1-10.wav",length=1.4773469387755,},}
L["youre still shuffling around a little but believe me youre dead"]={{path="vo/aperture_ai/escape_02_spheredestroy4-09.wav",length=2.8048752834467,},}
L["please do not attempt to remove testing apparatus from the testing area"]={{path="vo/aperture_ai/generic_crate_vaporized_in_emancipation_grid-1.wav",length=4.6151473922902,},}
L["kim swift one of the things we learned from narbacular drop our student project that became portal was that beginning players often thought portals took them into other spaces or even other dimensions to help fight that notion we start players in a visually unique room with memorable objects so that when they walk through a portal for the first time they have a clear point of reference which communicates the idea that theyre still in the same basic location for instance the radio which is playing an instrumental version of still alive helps as well by providing some audio continuity"]={{path="commentary/prtl-comment015.wav",length=29.511451247166,},}
L["target lost"]={{path="npc/turret_floor/turret_retire_1.wav",length=0.8475056689342,},{path="npc/turret_floor/turret_retire_2.wav",length=2.3451927437642,},{path="npc/turret_floor/turret_retire_4.wav",length=1.2001587301587,},{path="npc/turret_floor/turret_retire_5.wav",length=1.5786848072562,},{path="npc/turret_floor/turret_retire_6.wav",length=1.4506802721088,},{path="npc/turret_floor/turret_retire_7.wav",length=1.7066666666667,},}
L["once again excellent work"]={{path="vo/aperture_ai/02_part1_success-1.wav",length=2.2969387755102,},}
L["sounds echo and fade"]={{path="vo/escape/portal_escape_seg02-4.wav",length=6.1333333333333,},}
L["it was a fun test and were all impressed at how much you won the test is over come back"]={{path="vo/aperture_ai/escape_00_part1_nag16-1.wav",length=7.1499092970522,},}
L["good job on that by the way back to computer voice sarcasm sphere selftest complete"]={{path="vo/aperture_ai/escape_02_spheredestroy4-06.wav",length=3.8893424036281,},}
L["the enrichment center is committed to the well being of all participants"]={{path="vo/aperture_ai/10_part1_entry-1.wav",length=4.380589569161,},}
L["two cups all purpose flower"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-07.wav",length=1.9947845804989,},}
L["injector needle driver"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-37.wav",length=2.031746031746,},}
L["youre not a good person you know that right"]={{path="vo/aperture_ai/escape_01_part1_nag01-1.wav",length=3.2330839002268,},}
L["these intra dimensional gates have proven to be completely safe"]={{path="vo/aperture_ai/01_part1_get_portal_gun-3.wav",length=3.9912244897959,},}
L["fantastic you remained resolute and resourceful in an atmosphere of extreme pessimism"]={{path="vo/aperture_ai/05_part1_success-1.wav",length=7.4709977324263,},}
L["fish shaped ethyl benzene"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-13.wav",length=1.8808163265306,},}
L["you dont even care do you"]={{path="vo/aperture_ai/escape_01_part1_nag05-1.wav",length=3.1671882086168,},{path="vo/aperture_ai/escape_02_miscbabble-05.wav",length=2.2613378684807,},}
L["place your companion cube in the incinerator"]={{path="vo/aperture_ai/13_part1_endnag-7.wav",length=2.4497052154195,},}
L["remember when the platform was sliding into the fire pit and i said goodbye and you were like no way and then i was all i was just pretending to murder you that was great"]={{path="vo/aperture_ai/escape_nags_08.wav",length=11.723832199547,},}
L["this isnt brave its murder what did i ever do to you"]={{path="vo/aperture_ai/escape_02_miscbabble-03.wav",length=5.0346712018141,},{path="vo/aperture_ai/escape_01_part1_nag03-1.wav",length=5.8008616780045,},}
L["all aperture technologies remain safely operational up to 4000 degrees kelvin"]={{path="vo/aperture_ai/15_part1_into_the_fire-2.wav",length=5.7983219954649,},}
L["do not touch the operational end of the device"]={{path="vo/aperture_ai/01_part1_get_portal_gun-5.wav",length=2.9851020408163,},}
L["okay fine do touch it pick it up and just stuff it back into me"]={{path="vo/aperture_ai/escape_02_spherenag1-04.wav",length=4.6186848072562,},}
L["hiss"]={{path="vo/aperture_ai/escape_02_sphere_anger-18.wav",length=0.6965986394558,},{path="vo/aperture_ai/escape_02_sphere_anger-10.wav",length=0.8126984126984,},{path="vo/aperture_ai/escape_02_sphere_anger-16.wav",length=0.7894784580499,},{path="vo/aperture_ai/escape_02_sphere_anger-12.wav",length=0.8359183673469,},{path="vo/aperture_ai/escape_02_sphere_anger-05.wav",length=1.0913378684807,},{path="vo/aperture_ai/escape_02_sphere_anger-17.wav",length=0.7778684807256,},}
L["ooh that thing has numbers on it"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-06.wav",length=2.0549659863946,},}
L["greg coomer an important design goal of these postescape levels was to give players the sense that they were running wild inside the guts of the facility with that in mind we added plenty of nooks and crannies for players to crawl into or place portals through this ended up being a tricky lighting challenge as the areas needed to be bright enough to navigate while still being dim enough to feel like obscure disused sections of the building"]={{path="commentary/prtl-comment006.wav",length=23.254784580499,},}
L["fish shaped solid waste"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-11.wav",length=1.764716553288,},}
L["nick maggiore early versions of portal featured more detailed cluttered environments much like half life 2 we quickly realized that unnecessary objects scattered all over the place distracted players to the point where it actually interfered with the portal training process so we simplified the art style to favor clean focused test chambers the modular approach we settled on makes it look plausible that the chambers can reform dynamically on these pistons"]={{path="commentary/prtl-comment029.wav",length=23.344761904762,},}
L["good news i figured out what that thing that you just burned up did"]={{path="vo/aperture_ai/escape_02_spheredestroy1-04.wav",length=4.9280045351474,},}
L["robin walker perhaps the most important purpose of this final test chamber is to cement the double fling maneuver training for previous flings we employed a visual cue a pushed out a section of wall in preparation for the more freeform behindthescenes levels however we take the training wheels off to proceed players must realize that they can double fling almost anywhere they want to with or without hints"]={{path="commentary/prtl-comment074.wav",length=21.590045351474,},}
L["the device however has not"]={{path="vo/aperture_ai/01_part1_get_portal_gun-4.wav",length=1.8539229024943,},}
L["please note that we have added a consequence for failure any contact with the chamber floor will result in an unsatisfactory mark on your official testing record followed by death good luck"]={{path="vo/aperture_ai/04_part1_entry-1.wav",length=12.526213151927,},}
L["crickets chirp"]={{path="vo/escape/portal_escape_seg02-1.wav",length=4,},}
L["when the testing is over you will be missed"]={{path="vo/aperture_ai/08_part1_success-2.wav",length=3.1831519274376,},}
L["make no attempt to solve it"]={{path="vo/aperture_ai/05_part1_entry-2.wav",length=2.0563945578231,},}
L["unfortunately as much as id love to now i cant get the neurotoxin into your head any faster"]={{path="vo/aperture_ai/escape_02_spheredestroy2-02.wav",length=6.8906802721088,},}
L["cake and grief counseling will be available at the conclusion of the test"]={{path="vo/aperture_ai/10_part1_entry-2.wav",length=4.5696598639456,},}
L["this is your fault it didnt have to be like this"]={{path="vo/aperture_ai/escape_00_part2_nag03-1.wav",length=4.1579365079365,},}
L["and it contains proven preservatives deep penetration agents and gas and odor control chemicals"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-40.wav",length=7.5697052154195,},}
L["its not too late to turn back"]={{path="vo/aperture_ai/escape_00_part1_nag12-1.wav",length=2.7092517006803,},}
L["didnt we have some fun though"]={{path="vo/aperture_ai/escape_nags_07.wav",length=1.9146712018141,},}
L["three slash four cup vegetable oil"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-03.wav",length=2.6412698412698,},}
L["have i lied to you i mean in this room trust me leave that thing alone"]={{path="vo/aperture_ai/escape_02_spherenag1-08.wav",length=4.8,},}
L["time out for a second that wasnt supposed to happen"]={{path="vo/aperture_ai/escape_02_spheredrop1-01.wav",length=3.04,},}
L["oh whats that"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-03.wav",length=0.8591383219955,},}
L["look were both stuck in this place ill use lasers to inscribe a line down the center of the facility and one half will be where you live and ill live in the other half"]={{path="vo/aperture_ai/escape_02_miscbabble-01.wav",length=10.773333333333,},}
L["you shouldnt be here this isnt safe for you"]={{path="vo/aperture_ai/escape_00_part1_nag11-1.wav",length=4.5850793650794,},}
L["enter portal"]={{path="player/portal_enter1.wav",length=0.4407936507937,},{path="player/portal_enter2.wav",length=0.683537414966,},}
L["oh surprise "]={{path="vo/aperture_ai/post_escape_bridge_05.wav",length=0.3773242630385,},}
L["cordless electric needle injector"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-36.wav",length=2.8096145124717,},}
L["two cups rhubarb sliced"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-26.wav",length=2.4613151927438,},}
L["randy lundeen to make puzzles deeper than just teleporting to the exit we had to include surfaces that wont hold a portal which are formally introduced here we experimented with several surface designs before we settled on this one whose visual noise and reflectivity make it easy to identify at a distance"]={{path="commentary/prtl-comment038.wav",length=16.124603174603,},}
L["while safety is one of many enrichment center goals the aperture science high energy pellet seen to the left of the chamber can and has caused permanent disabilities such as vaporization"]={{path="vo/aperture_ai/03_part1_entry-1.wav",length=13.21126984127,},}
L["jeep barnett this massive turret ambush was originally a lot more massive with turrets that dropped from the ceiling and popped out of surprise hatches in fact for a while it was the games climactic battle through playtesting we learned that this type of pure combat experience didnt really fit with the preceding few hours of player training over several iterations we toned down the combat and made the room more about using portal momentum to fling yourself great distances a skill that playtesters really enjoyed using and thats a key component of what eventually became our final battle"]={{path="commentary/prtl-comment012.wav",length=33.93619047619,},}
L["unless you have a plan for building some supercomputer parts in a big hurry this place isnt going to be safe much longer"]={{path="vo/aperture_ai/escape_02_spheredestroy4-05.wav",length=7.5946712018141,},}
L["certain objects may be vital to your success do not destroy testing apparatus"]={{path="vo/aperture_ai/generic_security_camera_destroyed-4.wav",length=5.2421315192744,},}
L["alpha resins"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-18.wav",length=1.5789569160998,},}
L["for more information please attend an enrichment center electrical safety seminar"]={{path="vo/aperture_ai/14_part1_end-2.wav",length=5.6185487528345,},}
L["can you hear me"]={{path="vo/aperture_ai/post_escape_bridge_02.wav",length=0.8359183673469,},{path="vo/aperture_ai/post_escape_bridge_06.wav",length=0.8359183673469,},}
L["it says so right here in your personnel file unlikable liked by no one a bitter unlikable loner whos passing shall not be mourned"]={{path="vo/aperture_ai/escape_02_miscbabble-25.wav",length=9.9729705215419,},}
L["uh oh somebody cut the cake i told them to wait for you but they did it anyway there is still some left though if you hurry back"]={{path="vo/aperture_ai/escape_00_part1_nag17-1.wav",length=8.8896598639456,},}
L["youre doing very well"]={{path="vo/aperture_ai/01_part1_entry-1.wav",length=2.1374376417234,},}
L["whos gonna make the cake when im gone you"]={{path="vo/aperture_ai/escape_02_miscbabble-15.wav",length=3.7653514739229,},}
L["very impressive please note that any appearance of danger is merely a device to enhance your testing experience"]={{path="vo/aperture_ai/04_part1_success-1.wav",length=6.8480045351474,},}
L["your entire life has been a mathematical error a mathematical error im about to correct"]={{path="vo/aperture_ai/escape_02_spheredestroy4-11.wav",length=8.6760997732426,},}
L["ellen mclain voice of glados sarcasm glados is sarcastic a lot and thats so much fun but while i was trying to do this trying to build in all these emotions i still had to maintain the computer sound and maintain the pronunciation of repeated phrases you know aperture science and the enrichment center"]={{path="commentary/prtl-comment104.wav",length=29.17693877551,},}
L["goodbye"]={{path="vo/aperture_ai/15_part1_into_the_fire-5.wav",length=0.9918367346939,},}
L["unsaturated polyester resin"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-19.wav",length=3.1579138321995,},}
L["the companion cube cannot continue through the testing state and local statutory regulations prohibit it from simply remaining here alone and companionless you must euthanize it"]={{path="vo/aperture_ai/13_part1_endnag-5.wav",length=12.120816326531,},}
L["i invited your best friend the companion cube of course he couldnt come because you murdered him"]={{path="vo/aperture_ai/escape_02_miscbabble-23.wav",length=6.5248072562358,},}
L["one large rhubarb"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-31.wav",length=1.7182766439909,},}
L["thrashing debris"]={{path="vo/escape/portal_escape_seg01-3.wav",length=8,},}
L["welcome to the final test"]={{path="vo/aperture_ai/15_part1_entry-1.wav",length=1.7237641723356,},}
L["pant"]={{path="vo/aperture_ai/escape_02_sphere_anger-00.wav",length=1.2219501133787,},}
L["more intense pain sound"]={{path="vo/aperture_ai/escape_01_second_hit_nag01-1.wav",length=1.480022675737,},}
L["ouch"]={{path="npc/turret_floor/turret_tipped_2.wav",length=1.7472789115646,},{path="npc/turret_floor/turret_tipped_4.wav",length=1.4323129251701,},{path="npc/turret_floor/turret_tipped_5.wav",length=1.7920181405896,},{path="npc/turret_floor/turret_tipped_6.wav",length=2.3893424036281,},}
L["rocket launch"]={{path="weapons/rocket/rocket_fire1.wav",length=0.7048072562358,},}
L["the part of you that could have survived indefinitely is gone i just struck you from the permanent record"]={{path="vo/aperture_ai/escape_02_spheredestroy4-10.wav",length=5.4931972789116,},}
L["although the euthanizing process is remarkably painful eight out of ten aperture science engineers believe that the companion cube is most likely incapable of feeling much pain"]={{path="vo/aperture_ai/13_part1_endnag-4.wav",length=10.86693877551,},}
L["a complimentary escape hatch will open in three two one"]={{path="vo/aperture_ai/08_part1_trapped-2.wav",length=4.9449206349206,},}
L["im not kidding now turn back or i will kill you"]={{path="vo/aperture_ai/escape_00_part2_nag01-1.wav",length=3.690589569161,},}
L["searching"]={{path="npc/turret_floor/turret_search_1.wav",length=1.6268253968254,},{path="npc/turret_floor/turret_search_2.wav",length=1.3728571428571,},{path="npc/turret_floor/turret_search_4.wav",length=0.8300907029478,},}
L["you are kidding me"]={{path="vo/aperture_ai/escape_02_spheredestroy1-01.wav",length=1.0320181405896,},}
L["rushing wind"]={{path="vo/escape/portal_escape_seg01-1.wav",length=8,},}
L["ellen mclain voice of glados so when they told me that there was going to be a song at the end i thought well allright whos going to write the song and they told me there was going to be a song written by jonathan coulton and i listened to a song that jonathan had written and it was very funny very clever so i thought at that point well you know thisll be okay but i am an opera singer so usually i sing opera singing and i thought well will i be able to have the right style for the song so i was concerned but then before the recording they sent me an mp3 file of the song and i listened to it with jonathan singing it but i loved the little song and at home as i practiced the little song i tried to you know get back to gladoss voice you know aperture science just this tiny little passiveaggressive computer whos all alone until people try to come in and murder her so of course she gets upset but she seems she seems to have this real affinity for cake and and i want to play the game because i want to recreate the cake recipe and then put portal on it and be able to serve it to my friends when they come over to my house"]={{path="commentary/prtl-comment107.wav",length=86.365328798186,},}
L["the difference between us is that i can feel pain"]={{path="vo/aperture_ai/escape_02_miscbabble-04.wav",length=3.2853514739229,},{path="vo/aperture_ai/escape_01_part1_nag04-1.wav",length=3.4676870748299,},}
L["if you become light headed from thirst feel free to pass out"]={{path="vo/aperture_ai/08_part1_entry-2.wav",length=3.9357369614512,},}
L["two slash three cups granulated rhubarb"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-27.wav",length=3.1579138321995,},}
L["death scream"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-18.wav",length=1.4976870748299,},}
L["in dangerous testing environments the enrichment center promises to always provide useful advice"]={{path="vo/aperture_ai/07_part1_entry-2.wav",length=6.8966213151927,},}
L["do not submerge the device in liquid even partially"]={{path="vo/aperture_ai/01_part1_get_portal_gun-7.wav",length=3.5102721088435,},}
L["red portal open"]={{path="weapons/portalgun/portal_open2.wav",length=1.8346485260771,},{path="weapons/portalgun/portal_open3.wav",length=1.234693877551,},}
L["rocket locking"]={{path="weapons/rocket/rocket_locking_beep1.wav",length=0.1448072562358,},}
L["pain sound"]={{path="vo/aperture_ai/escape_01_first_hit_nag01-1.wav",length=0.7208390022676,},}
L["youre doing quite well"]={{path="vo/aperture_ai/02_part1_entry-2.wav",length=1.5450566893424,},}
L["im going to kill you and all the cake is gone"]={{path="vo/aperture_ai/escape_00_part2_nag02-1.wav",length=3.5211337868481,},}
L["ellen mclain voice of glados as an actor you know you come in you do what youre told you want to make your money and sometimes you get good direction and sometimes you dont get good direction but it doesnt matter and you certainly dont tell the production team any of this but you come in and theyll you know theyll give you a lame line reading and youre supposed to find some emotional value in that but this is not what this team did they would come in for example and give me the direction explosively indignant thats a wonderful direction for an actor so i must say that the production team won me over because so often i get bogus direction but this time i was actually directed and had fun at all the sessions"]={{path="commentary/prtl-comment103.wav",length=51.940544217687,},}
L["mechanical overload"]={{path="vo/escape/portal_escape_seg01-2.wav",length=8,},}
L["por favor bordn de fallar muchos gracias de fallar gracias"]={{path="vo/aperture_ai/00_part1_entry-6.wav",length=3.0106349206349,},}
L["you euthanized your faithful companion cube more quickly than any test subject on record congratulations"]={{path="vo/aperture_ai/13_part1_euthanized-1.wav",length=6.6409070294785,},}
L["the device is now more valuable than the organs and combined incomes of everyone in subject hometown here"]={{path="vo/aperture_ai/07_part1_get_device_component-3.wav",length=7.5868934240363,},}
L["nick maggiore this is the first map in which we experimented with solving the puzzle in as few portal placements as possible we tried to fit that concept into the story mode but were never quite able to sell it instead of abandoning the idea altogether we added the concept to a series of postgame challenge maps"]={{path="commentary/prtl-comment063.wav",length=16.323628117914,},}
L["scott dalton we found that rather than looking into a portal to see where it went playtesters would often leap blindly to their doom in response to this observation the moral of this puzzle is look before you leap the safe orange portal is out of the players view from this balcony that forces them to peer through a portal to see it which trains players in the remoteviewing capabilities of portals"]={{path="commentary/prtl-comment054.wav",length=18.726893424036,},}
L["greg coomer using gravity to fall into one portal so that you come rocketing out the other portal a skill we call flinging was another difficult concept to train we designed a specific visual cue a pushed out concrete block above a pit with checkerboard concrete tile to indicate to players that its time to use the fling maneuver repeated several times this cue helps players associate pushed out concrete slabs with flinging in much the same way that players learn to associate cubes with buttons"]={{path="commentary/prtl-comment053.wav",length=29.477732426304,},}
L["well done android the enrichment center once again reminds you that android hell is a real place where you will be sent at the first sign of defiance"]={{path="vo/aperture_ai/11_part1_success-1.wav",length=9.9381405895692,},}
L["that has got to be the dumbest thing thatwhoah whoah whoah whoah the voice has subtly changed smoother more seductive less computerized"]={{path="vo/aperture_ai/escape_02_spheredestroy1-03.wav",length=7.2855555555556,},}
L["is anyone there"]={{path="vo/aperture_ai/post_escape_bridge_03.wav",length=1.149387755102,},}
L["one cup granulated sugar"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-24.wav",length=2.0607709750567,},}
L["thank you for participating in this aperture science computeraided enrichment activity"]={{path="vo/aperture_ai/15_part1_into_the_fire-4.wav",length=5.3727891156463,},}
L["youre not smart youre not a scientist youre not a doctor youre not even a fulltime employee where did your life go so wrong"]={{path="vo/aperture_ai/escape_02_spheredestroy3-07.wav",length=7.1893424036281,},}
L["are you trying to escape chuckle things have changed since the last time you left the building whats going on out there will make you wish you were back in here"]={{path="vo/aperture_ai/escape_02_spheredestroy4-02.wav",length=9.4040816326531,},}
L["because despite your violent behavior the only thing youve managed to break so far is my heart"]={{path="vo/aperture_ai/escape_02_entry-01.wav",length=5.7493424036281,},}
L["jason brashill in early versions of this map playtesters would charge down the stairs without noticing what was creating the portals we introduced a mandatory pause in the action what we call a gate to help ensure that players stop and notice the portal gun making a blue portal a particle effect and a loud noise help draw their attention"]={{path="commentary/prtl-comment024.wav",length=18.910022675737,},}
L["please place the weighted storage cube on the fifteen hundred megawatt aperture science heavy duty supercolliding super button"]={{path="vo/aperture_ai/00_part2_entry-1.wav",length=7.3139909297052,},}
L["twelve medium geosynthetic membranes"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-23.wav",length=3.7151927437642,},}
L["lift moving"]={{path="ambient/machines/beam_platform_loop1.wav",length=0.7939229024943,},}
L["i am being serious now that crazy thing is not part of any test protocol"]={{path="vo/aperture_ai/escape_02_spherenag1-09.wav",length=4.7040136054422,},}
L["the enrichment center promises to always provide a safe testing environment"]={{path="vo/aperture_ai/07_part1_entry-1.wav",length=5.2751927437642,},}
L["pumping pistons"]={{path="vo/escape/portal_escape_seg03-3.wav",length=8,},}
L["as part of a required test protocol we will not monitor the next test chamber you will be entirely on your own good luck"]={{path="vo/aperture_ai/02_part1_success-2.wav",length=8.3227664399093,},}
L["jeep barnett originally these scaffolds ran on electrified tracks but crafty playtesters would hop along the rails to the exit bypassing the puzzle entirely we tried to solve this by killing players as soon as they touched the rails that solution ended up being too much of an over correction as even skilled playtesters were getting frustrated by these onehit kills in the more complex puzzles later in the game making the scaffolds run along immaterial beams of light solved both problems"]={{path="commentary/prtl-comment043.wav",length=28.503628117914,},}
L["you did it the weighted companion cube certainly brought you good luck"]={{path="vo/aperture_ai/13_part1_end-1.wav",length=4.5736281179138,},}
L["i know youre there i can feel you here"]={{path="vo/aperture_ai/escape_00_part1_nag03-1.wav",length=3.3687301587302,},}
L["one cup lemon juice"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-17.wav",length=1.6950566893424,},}
L["paul graham sometimes little details make a huge difference for instance we had to add the left side to this wall to give players a visual representation of how thick it is without it playtesters frequently thought the hall had just gotten impossibly narrower panicked and stopped making rational decisions"]={{path="commentary/prtl-comment094.wav",length=17.065306122449,},}
L["so get comfortable while i warm up the neurotoxin emitters "]={{path="vo/aperture_ai/escape_02_spheredestroy1-06.wav",length=4.4053514739229,},}
L["did you know you can donate one or all of your vital organs to the aperture science self esteem fund for girls its true"]={{path="vo/aperture_ai/10_part1_success-1.wav",length=8.1066666666667,},}
L["air whipping past"]={{path="vo/escape/portal_escape_seg03-2.wav",length=8,},}
L["snort"]={{path="vo/aperture_ai/escape_02_sphere_anger-06.wav",length=0.928798185941,},}
L["is that a gun"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-13.wav",length=0.795283446712,},}
L["lars jensvold this room is designed to build anticipation for the big moment when players finally get the fully powered portal gun the puzzle path brings you in a circle around the device so that its virtually always in sight right up until you grab it"]={{path="commentary/prtl-comment056.wav",length=12.387936507937,},}
L["robin walker portal is effectively an extended player training exercise we spend a huge portion of the game introducing a series of gameplay tools then layering these tools into increasingly difficult puzzles this layering starts here where we train the button/box mechanic before introducing the more complicated concept of portals"]={{path="commentary/prtl-comment016.wav",length=17.569818594104,},}
L["okay the test is over you win go back to the recovery annex for your cake"]={{path="vo/aperture_ai/escape_00_part1_nag15-1.wav",length=6.0336961451247,},}
L["hello"]={{path="vo/aperture_ai/post_escape_bridge_01.wav",length=0.5804988662132,},{path="vo/aperture_ai/escape_00_part1_nag01-1.wav",length=0.8322675736961,},}
L["i sincerely hope you werent expecting a response because im not talking to you"]={{path="vo/aperture_ai/escape_02_miscbabble-19.wav",length=4.7833106575964,},}
L["bay raitt we put the player character in an orange jumpsuit to reinforce the fact that shes a test subject visually the warmer orange colors help her pop out against the colder tones of the environment some playtesters were wondering why she could fall so far without getting hurt the way she would in halflife 2 in response we added mechanized heel springs to her lower legs afterwards there was no longer any question about why she could survive such long falls"]={{path="commentary/prtl-comment018.wav",length=22.639455782313,},}
L["deploying"]={{path="npc/turret_floor/turret_deploy_1.wav",length=0.7534693877551,},{path="npc/turret_floor/turret_deploy_2.wav",length=1.146462585034,},{path="npc/turret_floor/turret_deploy_4.wav",length=1.4860544217687,},{path="npc/turret_floor/turret_deploy_5.wav",length=1.9866666666667,},{path="npc/turret_floor/turret_deploy_6.wav",length=1.5040136054422,},}
L["pedestal rotating"]={{path="ambient/machines/portalgun_rotate1.wav",length=1.330612244898,},}
L["while it has been a faithful companion your companion cube cannot accompany you through the rest of the test if it could talk and the enrichment center takes this opportunity to remind you that it cannot it would tell you to go on without it because it would rather die in a fire than become a burden to you"]={{path="vo/aperture_ai/13_part1_endnag-2.wav",length=17.64716553288,},}
L["youre not going the right way"]={{path="vo/aperture_ai/escape_00_part1_nag07-1.wav",length=2.2997732426304,},}
L["three slash four cups butter or margarine"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-05.wav",length=2.8908843537415,},}
L["four large eggs one cup semisweet chocolate chips"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-04.wav",length=4.2260317460317,},}
L["coming through"]={{path="npc/turret_floor/turret_collide_1.wav",length=1.5786848072562,},{path="npc/turret_floor/turret_collide_2.wav",length=1.1613378684807,},{path="npc/turret_floor/turret_collide_3.wav",length=1.0666666666667,},{path="npc/turret_floor/turret_collide_4.wav",length=1.22,},{path="npc/turret_floor/turret_collide_5.wav",length=0.7866666666667,},}
L["weeeeeeeeeeeeeeeeeeeeeebzzt"]={{path="vo/aperture_ai/07_part2_success-1.wav",length=2.6997732426304,},}
L["as part of a previously mentioned required test protocol we can no longer lie to you"]={{path="vo/aperture_ai/08_part1_success-1.wav",length=6.1119274376417,},}
L["someone is going to get badly hurt"]={{path="vo/aperture_ai/escape_00_part1_nag14-1.wav",length=2.5572562358277,},}
L["snarl"]={{path="vo/aperture_ai/escape_02_sphere_anger-01.wav",length=1.544126984127,},}
L["it has been replaced with a livefire course designed for military androids"]={{path="vo/aperture_ai/11_part1_entry-2.wav",length=5.3866666666667,},}
L["the enrichment center reminds you that the weighted companion cube will never threaten to stab you and in fact cannot speak"]={{path="vo/aperture_ai/13_part1_middle-2.wav",length=8.3732199546485,},}
L["this weighted companion cube will accompany you through the test chamber please take care of it"]={{path="vo/aperture_ai/13_part1_pickup-1.wav",length=6.0624263038549,},}
L["hello again to reiterate our previous warning this test garbled momentum garbled"]={{path="vo/aperture_ai/06_part1_entry-1.wav",length=7.9447845804989,},}
L["what was that did you say something"]={{path="vo/aperture_ai/escape_02_miscbabble-18.wav",length=2.3916553287982,},}
L["gabe newell welcome to insert game name here hopefully you have already had a chance to enjoy the offbeat perspective and new game mechanic of portal to listen to a commentary node put your crosshair over the floating commentary symbol and press your use key to stop a commentary node put your crosshair over the rotating node and press the use key again some commentary nodes may take control of the game in order to show something to you in these cases simply press your use key again to stop the commentary please let me know what you think after you have had a chance to play as we think we are just at the beginning of taking advantage of this type of gameplay i can be reached at gabenvalvesoftwarecom thanks and have fun"]={{path="commentary/prtl-comment017.wav",length=46.015736961451,},}
L["before we start however keep in mind that although fun and learning are the primary goals of all enrichment center activities serious injuries may occur"]={{path="vo/aperture_ai/00_part1_entry-4.wav",length=10.19410430839,},}
L["we wont have to try to kill each other or even talk if we dont feel like it"]={{path="vo/aperture_ai/escape_02_miscbabble-02.wav",length=4.0700680272109,},}
L["please be advised that a noticeable taste of blood is not part of any test protocol but is an unintended side effect of the aperture science material emancipation grill which may in semi rare cases emancipate dental fillings crowns tooth enamel and teeth"]={{path="vo/aperture_ai/01_part1_entry-2.wav",length=18.652947845805,},}
L["shall not be mourned thats exactly what it says very formal very official"]={{path="vo/aperture_ai/escape_02_miscbabble-26.wav",length=7.6393650793651,},}
L["bill van buren these rocket sentries originally fired lasers we switched from lasers to rockets after we introduced the glassbreaking mechanic mainly because glass shattering in a massive rocket explosion turned out to be a lot more satisfying than glass just slowly being melted by a laser originally they also spoke just like the bullet turrets because players often redirect the rockets with their backs to the turret however a distinct uncluttered sound cue was required the voice simply added too much noise to the rocket redirect mechanic"]={{path="commentary/prtl-comment007.wav",length=30.398775510204,},}
L["maybe you think youre helping yourself but youre not this isnt helping anyone"]={{path="vo/aperture_ai/escape_00_part1_nag13-1.wav",length=6.3738095238095,},}
L["injector needle gun"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-38.wav",length=1.7995464852608,},}
L["there was even going to be a party for you a big party that all your friends were invited to"]={{path="vo/aperture_ai/escape_02_miscbabble-22.wav",length=5.9675283446712,},}
L["stop okay enough i deleted it no matter what happens now youre dead"]={{path="vo/aperture_ai/escape_02_spheredestroy4-08.wav",length=5.1626757369615,},}
L["for your own safety do not destroy vital testing apparatus"]={{path="vo/aperture_ai/generic_security_camera_destroyed-3.wav",length=4.1624036281179,},}
L["groan"]={{path="vo/aperture_ai/escape_02_sphere_anger-near_fire02.wav",length=0.4905215419501,},}
L["youve been wrong about every single thing youve ever done including this thing"]={{path="vo/aperture_ai/escape_02_spheredestroy3-06.wav",length=3.8933333333333,},}
L["and volatile malted milk impoundments"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-21.wav",length=3.2507936507937,},}
L["with it you can create your own portals"]={{path="vo/aperture_ai/01_part1_get_portal_gun-2.wav",length=2.89410430839,},}
L["paul graham this puzzle requires players to redirect an energy ball through multiple portal placements the multiple steps caused many early playtesters to panic and accidentally redirect a ball right into themselves with deadly results we redesigned the test chamber so that portals can only be placed in the top half of the room which solved the problem by generally leaving players out of the balls reach"]={{path="commentary/prtl-comment072.wav",length=20.674829931973,},}
L["ill tell you what that thing isnt it isnt yours so leave it alone"]={{path="vo/aperture_ai/escape_02_spherenag1-16.wav",length=4.5120181405896,},}
L["david kircher when rendering the players view through a portal we must render a separate image using a virtual camera which looks out of the opposite portal to obtain a correct image and efficient rendering performance we render only what is visible through the limited field of view of the opposite portal and exclude objects which lie between the virtual camera and the plane of the opposite portal"]={{path="commentary/prtl-comment027.wav",length=18.840997732426,},}
L["in the event that the weighted companion cube does speak the enrichment center urges you to disregard its advice"]={{path="vo/aperture_ai/13_part1_middle-2b-2.wav",length=7.4775283446712,},}
L["stop the device will detonate if removed from the testing area"]={{path="vo/aperture_ai/15_part1_partyfinalstop-1.wav",length=5.2326530612245,},}
L["pressurized steam"]={{path="vo/escape/portal_escape_seg03-1.wav",length=8,},}
L["david kircher integrating portals with the source engines physics system was a complex process that required several iterations to achieve the right balance of performance and correctness because portals can be placed virtually anywhere in the game environment the physics system had to be modified to allow dynamic changes to its representation of colliding geometry such as the walls and floor around this box and any objects which may lie on the opposite side of the portal initial implementations of this dynamic collision generation system could take up to one half of one second or 500 milliseconds to compute the correct collision this may not sound like a long time in everyday life but this pause during portal creation was quite noticeable in the context of the game ultimately we designed a system that creates temporary hybrid physics environments in bubbles around the portals using less accurate collision than that produced by sources standard collision generation but was accurate enough in practice and reduced the time to create the dynamic collision representation from 500 milliseconds to just 10 milliseconds which is an imperceptible pause during portal creation"]={{path="commentary/prtl-comment035.wav",length=55.392925170068,},}
L["cranial caps"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-39.wav",length=1.2887074829932,},}
L["paul graham because our test chamber environments were simplified for training purposes we created visual hot spots within the rooms to guide players attention the design is essentially a balance between round objects and sharp objects the sharp objects representing background elements and the round objects such as doors and moveable props comprising our points of visual interest"]={{path="commentary/prtl-comment041.wav",length=20.429569160998,},}
L["chet faliszek we designed this hall so that players had to use a box as a shield but many playtesters read it as an avoidtheenergyball timing puzzle and simply left the box behind we solved this in large part by having the ai talk about the box a lot once the dialog went in playtesters went from routinely abandoning the box to never wanting it to leave their side since we werent going to make players lug a box around for the rest of the game we added a scene at the end of the level where players are forced to kill the box"]={{path="commentary/prtl-comment084.wav",length=27.524353741497,},}
L["the talking is over"]={{path="vo/aperture_ai/escape_02_miscbabble-20.wav",length=1.2132426303855,},}
L["david kircher we previously talked about how we handle static portal collision but collision with moving objects on the other side of the portal is a completely different and equally hard problem walking onto this scaffold was a very iffy proposition for the first few months of development we solve the problem of colliding with these dynamic objects by cloning the objects from one portal to the other and strictly controlling what objects are allowed to collide with each other and how theyre allowed to collide"]={{path="commentary/prtl-comment044.wav",length=23.366031746032,},}
L["bill van buren originally these exit portal surfaces were static geometry in the final position but playtesters stubbornly refused to look up to find them this is another example of the classic gamedesign problem of coaxing players to look up by putting the portals on moving pistons we were able to start them in a position that players were more likely to see"]={{path="commentary/prtl-comment051.wav",length=20.775487528345,},}
L["we are very very happy for your success"]={{path="vo/aperture_ai/15_part1_partyspeech-2.wav",length=3.6600907029478,},}
L["heres a hint youre gonna want to pack as much living as you can into the next couple of minutes"]={{path="vo/aperture_ai/escape_02_spheredestroy2-05.wav",length=6.1653514739229,},}
L["killing you and giving you good advice arent mutually exclusive the rocket really is the way to go"]={{path="vo/aperture_ai/escape_02_spheredestroy1-10.wav",length=6.6133333333333,},}
L["that thing is probably some kind of raw sewage container go ahead and rub your face all over it"]={{path="vo/aperture_ai/escape_02_spherenag1-06.wav",length=4.8853514739229,},}
L["chris chin player training doesnt always stick especially after the introduction of a big new concept for instance after theyd acquired the fully powered portal device playtesters often forgot about the fling maneuver since its such an important skill this puzzle is designed to reintroduce the idea of flinging"]={{path="commentary/prtl-comment057.wav",length=17.170136054422,},}
L["do you think i am trying to trick you with reverse psychology i mean seriously now"]={{path="vo/aperture_ai/escape_02_spherenag1-03.wav",length=5.28,},}
L["pull and peel licorice"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-14.wav",length=2.1362358276644,},}
L["realm lovejoy after players escape we let them solve an old chamber in a new way this reintroduction of a familiar space which can now be solved in an incorrect way helps convey the sense that players are cheating the system while forging their own path through the facility"]={{path="commentary/prtl-comment096.wav",length=14.586870748299,},}
L["did you just toss the aperture science thing we dont know what it does into the aperture science emergency intelligence incinerator"]={{path="vo/aperture_ai/escape_02_spheredestroy1-02.wav",length=6.9622222222222,},}
L["bzzt garble fling garble fling garble bzzt"]={{path="vo/aperture_ai/07_part2_entry-1.wav",length=4.5854421768707,},}
L["ellen mclain voice of glados i know that i was told that you know sort of the idea of valve is that everything everything is planned everything is worked out in advance but thats a big fat lie because the initial idea is started and they bring an actor into the studio and they say you know say these words for us say this computer generated voice for us okay ill do that well then that gives the creators other ideas and its its a rolling process you roll from one idea into the next idea"]={{path="commentary/prtl-comment101.wav",length=34.751859410431,},}
L["the enrichment center regrets to inform you that this next test is impossible"]={{path="vo/aperture_ai/05_part1_entry-1.wav",length=5.3042403628118,},}
L["robin walker because we very deliberately introduce and train each gameplay concept once players reach this spot were confident that they know what a portal is and roughly how it works early versions of portal let players stumble through the beginning of the game without always understanding what was going on which really compromised teaching new concepts the puzzle you just finished was designed so that stumbling around will virtually always lead to a dead end completing the puzzle requires walking through a minimum of five portals in a specific order this kind of gating in which a solid understanding of key gameplay concepts is required for success helped standardize the learning curve of the game tremendously"]={{path="commentary/prtl-comment023.wav",length=36.425827664399,},}
L["whats your point anyway survival well then the last thing you want to do is hurt me"]={{path="vo/aperture_ai/escape_02_spheredestroy3-03.wav",length=6.2004535147392,},}
L["ellen mclain voice of glados in the beginning when i came in i was just supposed to recreate the sound of a computergenerated voice just recreate it and thats what i did and there was no emotion involved i just listened to the sound of the computer and i repeated what i heard but as the game continued i was supposed to get more and more emotion into the computer into glados and she developed into a very sweet passiveaggressive person"]={{path="commentary/prtl-comment102.wav",length=34.389455782313,},}
L["where do you think youre going"]={{path="vo/aperture_ai/escape_00_part1_nag08-1.wav",length=2.0156916099773,},}
L["yipe"]={{path="vo/aperture_ai/escape_02_sphere_anger-near_fire01.wav",length=0.441179138322,},}
L["thank you for helping us help you help us all"]={{path="vo/aperture_ai/10_part1_entry-3.wav",length=2.9143537414966,},}
L["candy coated peanut butter pieces shaped like fish"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-16.wav",length=4.530612244898,},}
L["when you are done you will drop the device in the equipment recovery annex"]={{path="vo/aperture_ai/15_part1_entry-2.wav",length=5.1309297052154,},}
L["your business is appreciated"]={{path="ambient/machines/usetoilet_thank.wav",length=2.6296371882086,},}
L["portalgun primary fire"]={{path="weapons/portalgun/portalgun_shoot_blue1.wav",length=0.6997732426304,},}
L["im not angry just go back to the testing area"]={{path="vo/aperture_ai/escape_00_part1_nag10-1.wav",length=4.2146712018141,},}
L["perfect please move quickly to the chamberlock as the effects of prolonged exposure to the button are not part of this test"]={{path="vo/aperture_ai/00_part2_success-1.wav",length=10.19589569161,},}
L["i dont want to tell you youre business but if it were me id leave that thing alone"]={{path="vo/aperture_ai/escape_02_spherenag1-02.wav",length=4.2560090702948,},}
L["chris chin even though layering player training was a design goal from the start we still ended up introducing some concepts too quickly for instance this used to be the first energyball redirection puzzle playtesting revealed that this puzzle introduced too many new concepts at once which ended up frustrating a lot of playtesters in response we inserted two test chambers before this one to make the energyball redirection training more gradual"]={{path="commentary/prtl-comment040.wav",length=24.748390022676,},}
L["fluorescent light hum"]={{path="ambient/machines/fluorescent_hum_2.wav",length=0.0166666666667,},{path="ambient/machines/fluorescent_hum_1.wav",length=0.0166666666667,},}
L["when i said deadly neurotoxin the deadly was in massive sarcasm quotes"]={{path="vo/aperture_ai/escape_02_miscbabble-11.wav",length=6.0160090702948,},}
L["pain noise"]={{path="vo/aperture_ai/escape_02_ballhitpain-02.wav",length=8.9629024943311,},}
L["starting now theres going to be a lot less conversation and a lot more killing"]={{path="vo/aperture_ai/escape_02_miscbabble-17.wav",length=5.1780498866213,},}
L["randy lundeen originally these catwalks were decorative but playtesters consistently thought they were significant and often spent a lot of time trying to reach them we didnt want to stand between people and their desire to walk on the catwalks so we redesigned the area to make catwalks not only accessible but also necessary to proceed"]={{path="commentary/prtl-comment010.wav",length=17.330453514739,},}
L["a party associate will arrive shortly to collect you for your party"]={{path="vo/aperture_ai/15_part1_partyspeech-5.wav",length=4.9735827664399,},}
L["search mode activated"]={{path="npc/turret_floor/turret_autosearch_1.wav",length=1.1642403628118,},{path="npc/turret_floor/turret_autosearch_2.wav",length=0.8951700680272,},{path="npc/turret_floor/turret_autosearch_4.wav",length=2.6528571428571,},{path="npc/turret_floor/turret_autosearch_5.wav",length=2.4933333333333,},{path="npc/turret_floor/turret_autosearch_6.wav",length=2.5866666666667,},}
L["jeremy bennett when we moved from largely placeholder art to our final visual design this was the first level to get a facelift we chose this map because it had many of our gameplay elements integrated into a relatively small space the test chamber art direction was designed to make everything appear purposefully placed the simple design helps focus players on the puzzles it also provides a nice contrast to the later much less sterile behindthescenes environments which contributes to a clear sense of progression"]={{path="commentary/prtl-comment059.wav",length=26.273378684807,},}
L["are you still listening"]={{path="vo/aperture_ai/post_escape_bridge_07.wav",length=1.0797278911565,},}
L["what is that"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-02.wav",length=0.7343310657596,},{path="vo/aperture_ai/escape_02_sphere_curiosity-05.wav",length=1.0739229024943,},}
L["grunt"]={{path="vo/aperture_ai/escape_02_sphere_anger-13.wav",length=0.5456689342404,},}
L["the enrichment center apologizes for this clearly broken test chamber"]={{path="vo/aperture_ai/05_part1_nag1-1.wav",length=5.0885034013605,},}
L["gnash"]={{path="vo/aperture_ai/escape_02_sphere_anger-02.wav",length=0.7546485260771,},}
L["id just like to point out that you were given every opportunity to succeed"]={{path="vo/aperture_ai/escape_02_miscbabble-21.wav",length=4.2956916099773,},}
L["scott dalton as the end of the game draws closer we increase the ratio of timepressured puzzles like this turret ambush to give players the sense that theyre approaching a climactic encounter"]={{path="commentary/prtl-comment009.wav",length=8.7858503401361,},}
L["three tablespoons rhubarb on fire"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-30.wav",length=3.4365532879819,},}
L["did you hear me i said you dont care are you listening"]={{path="vo/aperture_ai/escape_02_miscbabble-06.wav",length=3.9466666666667,},}
L["no one will blame you for giving up in fact quitting at this point is a perfectly reasonable response"]={{path="vo/aperture_ai/05_part1_nag4-1.wav",length=9.4162811791383,},}
L["rest assured that there is absolutely no chance of a dangerous equipment malfunction prior to your victory candescence"]={{path="vo/aperture_ai/15_part1_into_the_fire-3.wav",length=7.5183673469388,},}
L["paul graham we wanted players to feel safe while standing in a portal so we never kill them or destroy objects within a portal thats closing instead we either push or teleport objects out of a portal as it closes"]={{path="commentary/prtl-comment022.wav",length=12.219727891157,},}
L["put me down"]={{path="npc/turret_floor/turret_pickup_1.wav",length=1.1320181405896,},{path="npc/turret_floor/turret_pickup_3.wav",length=2.0480045351474,},{path="npc/turret_floor/turret_pickup_6.wav",length=1.9626757369615,},{path="npc/turret_floor/turret_pickup_7.wav",length=1.1093424036281,},{path="npc/turret_floor/turret_pickup_8.wav",length=2.2053514739229,},{path="npc/turret_floor/turret_pickup_9.wav",length=1.1453514739229,},{path="npc/turret_floor/turret_pickup_10.wav",length=1.1960090702948,},}
L["i have an infinite capacity for knowledge and even im not sure whats going on outside"]={{path="vo/aperture_ai/escape_02_spheredestroy4-03.wav",length=5.4102494331066,},}
L["destroy your companion cube or the testing cannot continue"]={{path="vo/aperture_ai/13_part1_endnag-6.wav",length=3.308843537415,},}
L["erik wolpaw the fiction behind this red phone is that while glados was being developed it was somebodys job to sit by it and if it ever looked like the ai was becoming sentient and godlike that person would pick up the phone and call somebody to come help at the point in time where the actual game takes place its become obvious that the aperture science red phone plan didnt 100 work out"]={{path="commentary/prtl-comment014.wav",length=19.243265306122,},}
L["quit now and cake will be served immediately"]={{path="vo/aperture_ai/05_part1_nag5-1.wav",length=3.8580272108844,},}
L["no further compliance information is required or will be provided and you are an excellent test subject"]={{path="vo/aperture_ai/09_part1_entry-2.wav",length=8.7419274376417,},}
L["i have your brain scanned and permanently backed up in case something terrible happens to you which its just about to"]={{path="vo/aperture_ai/escape_02_spheredestroy3-04.wav",length=7.0613378684807,},}
L["what are you doing stop it i i we are pleased that you made it through the final challenge where we pretended we were going to murder you"]={{path="vo/aperture_ai/15_part1_partyspeech-1.wav",length=11.724217687075,},}
L["ellen mclain voice of glados i went to portals umm i googled portal ingame and i went to the trailer and i just loved it i loved hearing my voice laughter and as i told the production team i have never played a computer game in my life but i want to play this one laughter"]={{path="commentary/prtl-comment105.wav",length=21.354240362812,},}
L["frankly this chamber was a mistake if we were you we would quit now"]={{path="vo/aperture_ai/05_part1_nag3-1.wav",length=5.6885714285714,},}
L["at the enrichment center we promise never to value your safety above your unique ideas and creativity however do not destroy vital testing apparatus"]={{path="vo/aperture_ai/generic_security_camera_destroyed-1.wav",length=11.140453514739,},}
L["just ignore that thing and stand still"]={{path="vo/aperture_ai/escape_02_spherenag1-13.wav",length=1.9413378684807,},}
L["roughlanding"]={{path="player/futureshoes1.wav",length=0.7129931972789,},{path="player/futureshoes2.wav",length=0.7899092970522,},}
L["to ensure the safe performance of all authorized activities do not destroy vital testing apparatus"]={{path="vo/aperture_ai/generic_security_camera_destroyed-2.wav",length=6.4672562358277,},}
L["elevator chime"]={{path="ambient/alarms/portal_elevator_chime.wav",length=2.6834013605442,},}
L["where are you"]={{path="vo/aperture_ai/escape_00_part1_nag02-1.wav",length=1.1096825396825,},}
L["where are we going"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-16.wav",length=0.8649433106576,},{path="vo/aperture_ai/escape_02_sphere_curiosity-09.wav",length=0.7662585034014,},}
L["okay were even now you can stop"]={{path="vo/aperture_ai/escape_01_second_hit_nag02-1.wav",length=3.0809977324263,},{path="vo/aperture_ai/escape_02_miscbabble-09.wav",length=2.6453514739229,},}
L["chet faliszek for portal we wanted to create a turret that was different from the traditional hl2 turrets the hl2 turrets are nothing more than mindless mounted guns in portal we wanted the turrets to have personality to be characters the first step was a redesign of the look once we had the look of the new turrets they seemed less like menacing machine guns and more like cute robots and robots can never really be cute until they are talking robots so the next step was creating the vocal characteristics of the turrets working with ellen mcclain we settled on an innocent sounding voice with dialogue to match this juxtaposition of killing machine and innocent nonaggressive personality ends up making the portal turret a memorable character"]={{path="commentary/prtl-comment076.wav",length=39.775782312925,},}
L["i let you survive this long because i was curious about your behavior well youve managed to destroy that part of me"]={{path="vo/aperture_ai/escape_02_spheredestroy2-01.wav",length=8.64,},}
L["that thing you burned up isnt important to me its the fluid catalytic cracking unit it made shoes for orphans"]={{path="vo/aperture_ai/escape_02_miscbabble-07.wav",length=8.6826757369615,},}
L["activated"]={{path="npc/turret_floor/turret_active_1.wav",length=0.5630158730159,},{path="npc/turret_floor/turret_active_2.wav",length=1.5792970521542,},{path="npc/turret_floor/turret_active_4.wav",length=0.9619727891156,},{path="npc/turret_floor/turret_active_5.wav",length=3.1493424036281,},{path="npc/turret_floor/turret_active_6.wav",length=0.9560090702948,},{path="npc/turret_floor/turret_active_7.wav",length=1.7066666666667,},{path="npc/turret_floor/turret_active_8.wav",length=1.9626757369615,},}
L["a replacement aperture science weighted storage cube will be delivered shortly"]={{path="vo/aperture_ai/generic_crate_vaporized_in_emancipation_grid-2.wav",length=5.1756235827664,},}
L["huh that core may have had some ancillary responsibilities i cant shut off the turret defenses"]={{path="vo/aperture_ai/escape_02_spheredestroy1-07.wav",length=6.1440136054422,},}
L["assume the party escort submission position or you will miss the party"]={{path="vo/aperture_ai/15_part1_partyspeech-7.wav",length=4.2303854875283,},}
L["due to mandatory scheduled maintenance the appropriate chamber for this testing sequence is currently unavailable"]={{path="vo/aperture_ai/11_part1_entry-1.wav",length=7.1680045351474,},}
L["kerry davis a problem we came across with virtually any puzzle involving boxes and doors was that players could portal the boxes to the other side of the door thereby trapping themselves in a room with buttons but no boxes we set up special triggers to detect and handle these cases and then added the box delivery tubes to ensure players could always be supplied with the required tools"]={{path="commentary/prtl-comment060.wav",length=19.574421768707,},}
L["think about it if that thing is important why dont i know about it"]={{path="vo/aperture_ai/escape_02_spherenag1-14.wav",length=3.8826757369615,},}
L["the vital apparatus vent will deliver a weighted companion cube in three two one"]={{path="vo/aperture_ai/13_part1_entry-1.wav",length=6.9696145124717,},}
L["garret rickey through playtesting we discovered that fatigue set in if we didnt break up the more complicated deliberately paced puzzles with problems that required the player to perform a much simpler task under time pressure these pistons proved to be a good foundation for that simpler type of puzzle because they feature a moving surface they also gave us an opportunity to employ some unusual portal transitions such as ceilingtoceiling"]={{path="commentary/prtl-comment004.wav",length=21.675827664399,},}
L["scream"]={{path="vo/aperture_ai/escape_02_sphere_death_scream.wav",length=1.4628571428571,},}
L["are you still standing there"]={{path="vo/aperture_ai/post_escape_bridge_09.wav",length=1.2596825396825,},{path="vo/aperture_ai/post_escape_bridge_08.wav",length=1.2596825396825,},}
L["one can prepared coconut pecan frosting"]={{path="vo/aperture_ai/escape_02_sphere_cakemix-02.wav",length=3.5526530612245,},}
L["jason brashill originally a weighted button was used to open the far door but playtesters so strongly associated boxes with buttons that theyd get stuck searching hopelessly for a box we changed the big button to a pedestal mounted push button thus removing the box association but playtesters still had trouble realizing they needed to shoot a portal through the door adding a ticking timer sound when the door was open cued players that the puzzle expected them to act during that time which solved the problem"]={{path="commentary/prtl-comment058.wav",length=28.314965986395,},}
L["clock tick"]={{path="ambient/machines/tick1.wav",length=0.0690249433107,},}
L["jeep barnett the awful end of the companion cube serves a dual purpose it adds a lot more sinister character to our already pretty sinister ai while simultaneously training players to use the incinerator a key component of the final level the training has a nice dramatic payoff since players later get to avenge the death of their good friend the companion cube by stuffing some of the ais important parts into exactly the same type of incinerator"]={{path="commentary/prtl-comment083.wav",length=26.136553287982,},}
L["whats that noise"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-12.wav",length=0.9926530612245,},}
L["are you coming back"]={{path="vo/aperture_ai/escape_02_sphere_curiosity-10.wav",length=1.0623129251701,},}
L["please escort your companion cube to the aperture science emergency intelligence incinerator"]={{path="vo/aperture_ai/13_part1_end-3.wav",length=6.1068480725624,},}
L["it also says you were adopted so thats funny too"]={{path="vo/aperture_ai/escape_02_miscbabble-27.wav",length=3.4713832199546,},}
c.EndList()
