c.StartList("valeria")
L["booth is hosting another one of his open houses go and try out his wares there may be a weapon you overlooked that might suit you"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_open_house.mp3",length=4.2547812461853}}
L["comparing harvier and turners technique is like comparing pollock and kandinsky both are masters but one is significantly more messy not every assassination calls for a bloodbath when i call on you i expect your kills to be clean and precise"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_pollock_turner.mp3",length=9.3083610534668}}
L["evil criminal terrorist the reality is that i am non of these things my name is valeria jenner and i am the voice of the phoenix and the phoenix is the voice of freedom its said you have talents that can be of use to the struggle its time for you to prove  you have the skis you acclaim to have"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_two_sides.mp3",length=10.02819442749}}
L["fear is a construct of the mind and its something our enemies wield with alarming grace you see when people are scared they turn to those with authorities for solutions because theyre conditioned to feel powerless thats why engaging with nuclear options is critical once we show that the ivory tower can do nothing to save them they will rise to help themselves"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_fear_turner.mp3",length=64.487998962402}}
L["felix launched a campaign against us in the maghreb operation vanguard he called it it was a killing field one by one turner executed our brothers and sisters as they valiantly tried to place an explosive device it was in that moment a question took route in his mind what cause could motivate these people to throw their lives away with such determination he sought me out and i provided answers"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_maghreb_turner.mp3",length=13.464750289917}}
L["fire is the weapon of the revolution like us fire breathes like us fire spreads yes it takes lives but without fire we would sit in darkness and die in the cold do not be afraid of fire master it"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_flames.mp3",length=11.072750091553}}
L["history may be written by the victors but that doesnt mean we have to buy the book we lost the battle in maghreb but we gained the loyalty of turner now turner is dead but we have gained you the coalition believes that they have struck a blow against us but like the story of turners defection like the story of our namesake defeat is never the end the phoenix can never die"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_history_turner.mp3",length=12.338582992554}}
L["i dont know how but felix learned about our bank heist and now his jack booted thugs are on route it falls on you two to steal your resolve and cut the oppressors down"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_bank_turner.mp3",length=5.5931668281555}}
L["if you want to fight for change theres something i need you to do kill a man with a knife feel his blood in your hands do not ignore it do not sugar coat it accept it for the phoenix not lie not to the sleeping world nor to ourselves"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_knife.mp3",length=8.6698331832886}}
L["like it or not the arms dealer named booth plays a pivotal role in the struggle yes he plays both sides but without his wares we wouldnt be able to topple tyrants work with him use him but never trust him"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_booth.mp3",length=4.6215415000916}}
L["marcus chapel is sebastian hennequet best friend loyal courages and an expert marksman he is also insanely predictable which is why i was able to lure him here stalk him and end his life so that hennequet will live out the rest of his in sorrow and misery"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_blunt_turner.mp3",length=9.7013120651245}}
L["people want to believe that change comes from within the system but you and i know better the system protects corporate stooges like under hill and murphey as they line their pockets promoting industries that cripple the common man today their ivory tower begins to fall"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_underhill_turner.mp3",length=8.6814441680908}}
L["some conflicts feel never ending the same dance that continues over and over lesser men look to this and see of utility but the phoenix sees hope as long as people are willing to die for what they feel is right the cause is not lost we are not defined by our failures until the moment we refuse to stand back up"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_conflict.mp3",length=11.973968505859}}
L["that journalist we captured during operation vanguard seems to have more friends than we thought her safe house has been compromised and felixs thugs are coming in force support isnt coming its up to you two to hold the line"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_journalist_turner.mp3",length=6.3826665878296}}
L["the capture of lord william is one of the phoenixes greatest triumphs turner led a small unit to williams estate dragging that snivelling worn out from his ivory tower the coalition task force tried in vain to save him but turner laid them low with the ssg 08"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_cobble_turner.mp3",length=8.2866945266724}}
L["the media loves to label everything civilian casualties military casualties when the reality is that a life is a life everyone on this earth plays a role in the struggle and we are all culpable for our actions the men and women we capture are not random people caught in the wrong place at the wrong time they are targeted for a reason and we must never let them be taken from us"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_labels_turner.mp3",length=12.86102771759}}
L["the phoenix has no need of cowards often our victorys hinge on relentless aggression thats where smgs come in light enough to move swiftly but a fast enough rate of fire to keep our enemies pinned down"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_smg.mp3",length=5.8486108779907}}
L["the phoenix is the symbol of rebirth every skirmish we engage in whether it is our fifth or our fiftieth is a new beginning seize that opportunity and strike our oppressors down then break their morale by turning their own weapons against them"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_rebirth.mp3",length=7.903555393219}}
L["the world is not yet ready for our message but that doesnt mean our message does not need to be spread in time fear will give way to understanding and the phoenix will be regarded as the heroes we are"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_message.mp3",length=7.271906375885}}
L["theres someone id like you to meet a defector from the coalition task force named chase turner but before you do i have a final test for you stand with your new brothers and sisters against your old ones dont let our hostages be taken from us"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_meet_mentor.mp3",length=7.8687224388123}}
L["titans of industry all flock to the elysee resort a temple of excess designed to cuddle ceos who made their fortune on the back of labourers theyd laugh as they clink glasses full of champaign each flute filled with one ones salaries of their employees but soon they would stop laughing"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_elysee_turner.mp3",length=8.565333366394}}
L["turner is dead struck down by a father who couldnt bare to see his son outshine him our reckoning will be coming for mister hennequet but for now i want him to hurt like we do ive located one of his star pupils an operator named jackson find him kill him and bring justice for the phoenix"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_dead_turner.mp3",length=11.229468345642}}
L["turner played a important role in the struggle now it falls on you to walk in his footsteps master the awp carry on a great mans legacy"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_role_turner.mp3",length=5.5119166374207}}
L["we fight to unseat tyrants with resources superior to our own thats why we need to leverage surprise striking fast and hard lie in wait with your shotgun and act decisively"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_tyrants.mp3",length=6.4175000190735}}
L["we have shown the world that the struggle is not fruitless now anarchists have spread throughout europe eager to break the governments gilded cage"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_fruitless_turner.mp3",length=4.6295557022095}}
L["we never know what resources well have  available on the fiend so it is important to be able to fight with a variety of weapons not just the ones youre familiar with"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_resources.mp3",length=5.1037502288818}}
L["your loyalty has been proven and now the phoenix has special need of you a nuclear facility we aim to take over has recently remodelled the toxic room im sending you and a fellow brother to secure the engineers for the redesign we need to know what changes are coming"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_loyalty.mp3",length=8.5305004119873}}
L["youre not the first person whos eyes were opened to there hypocrisy that surrounds us to understand that for freedom to truly reign we must burn down governments burn down religion burn down the bourgeoisie and only from those ashes can mankind rise pure and clean its your turn to follow the path of the phoenix its your turn to light the spark of revolution"]={{path="campaign/bloodhound/valeria/op_bloodhound_valeria_spark.mp3",length=12.522531509399}}
c.EndList()